#!/usr/bin/env python3
"""Talentos de arquétipos do Player Core 2, páginas físicas globais 200–223.

Tradução editorial manual a partir do OCR local do PDF fornecido. Este arquivo não
habilita efeitos no motor: todas as entradas são material de consulta revisado.
"""
import json
import pathlib
import re
import unicodedata

rows=[]
def slug(s):
 s=unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()
 return re.sub(r'(^-|-$)','',re.sub(r'[^a-z0-9]+','-',s))
def add(en,pt,nivel,pagina,arquetipo,texto,resumo,*,pre='',acoes='',tracos=None,gatilho='',requisitos='',frequencia='',ambiguidade=''):
 rows.append({'id':slug(pt),'nome':pt,'nomeOriginal':en,'nivel':nivel,'pagina':pagina,'paginaPdf':pagina,'paginaImpressa':pagina-1,
  'tipo':'talento-arquetipo','arquetipo':arquetipo,'preRequisitos':pre,'acoes':acoes,'gatilho':gatilho,'requisitos':requisitos,
  'frequencia':frequencia,'tracos':['arquétipo']+(tracos or []),'descricao':texto,'resumo':[resumo],
  'fonte':'player-core-2','revisao':'revisado' if not ambiguidade else 'ocr-ambiguo','somenteConsulta':True,
  'revisaoFonte':'Tradução manual do OCR local do PDF fornecido; efeito preservado integralmente.'+((' Ambiguidade: '+ambiguidade) if ambiguidade else '')})

# Ritualista — p. 212
add('Ritualist Dedication','Dedicação de Ritualista',2,212,'Ritualista','Você recebe +2 de circunstância em todas as verificações para realizar um ritual e aprende dois rituais incomuns de 2ª graduação ou menor. Deve cumprir todos os pré-requisitos para ser o conjurador primário do ritual escolhido e não pode ensiná-lo nem permitir que outra pessoa seja o conjurador primário, a menos que ela também conheça o ritual. No 8º nível e a cada 4 níveis seguintes, aprende mais dois rituais sob as mesmas restrições, de graduação máxima igual à metade de seu nível.','Bônus em rituais e dois rituais novos a cada quatro níveis desde o 8º.',pre='especialista em Arcanismo, Natureza, Ocultismo ou Religião',tracos=['incomum','dedicação'])
add('Flexible Ritualist','Ritualista Flexível',4,212,'Ritualista','Ao conjurar um ritual, pode reduzir em 1 o número de conjuradores secundários. Deve cumprir os requisitos daquele conjurador e faz a verificação secundária normalmente exigida dele. Não pode substituir um conjurador secundário que seja alvo da magia, como no ritual Expiação.','Substitui um conjurador secundário, mas assume seus requisitos e sua verificação.',pre='Dedicação de Ritualista')
add('Resourceful Ritualist','Ritualista Engenhoso',6,212,'Ritualista','Pode tentar verificações de rituais que exijam proficiência especialista sendo treinado, proficiência mestre sendo especialista, ou proficiência lendária sendo mestre.','Executa rituais que exigem um grau de proficiência acima do seu.',pre='Dedicação de Ritualista',tracos=['perícia'])
add('Efficient Rituals','Rituais Eficientes',6,212,'Ritualista','Se um ritual normalmente exigir 1 dia, pode realizá-lo em 4 horas. Se exigir mais de 1 dia, leva metade dos dias, arredondada para cima. No 14º nível, um ritual com tempo medido em dias passa a exigir o mesmo número de horas; se resultar em mais de 8 horas, divida-o entre vários dias como de costume.','Reduz drasticamente o tempo necessário para realizar rituais.',pre='Dedicação de Ritualista')
add('Assured Ritualist','Ritualista Seguro',10,212,'Ritualista','Sendo o conjurador primário, depois de todas as verificações secundárias serem roladas, escolha uma que tenha resultado em falha ou falha crítica e melhore o resultado em um grau de sucesso.','Melhora em um grau uma verificação secundária malsucedida.',pre='Ritualista Flexível')
add('Enterprising Ritualist','Ritualista Empreendedor',14,212,'Ritualista','Quando o Custo de um ritual tiver valor em po, reduza em 10% o valor gasto. Se obtiver sucesso crítico na verificação primária, reduza o valor consumido novamente na mesma quantia. Por exemplo, Ressuscitar uma criatura de 14º nível custaria 945 po em vez de 1.050 po, ou 840 po com sucesso crítico.','Reduz em 10% o custo monetário de rituais, novamente em um sucesso crítico.',pre='Dedicação de Ritualista')

# Batedor — p. 213
add('Scout Dedication','Dedicação de Batedor',2,213,'Batedor','Pode realizar simultaneamente as atividades de exploração Batedor e Evitar Ser Notado. O bônus de iniciativa concedido por Batedor passa de +1 para +2.','Combina exploração furtiva e reconhecimento e melhora o bônus de iniciativa.',pre='treinado em Furtividade e Sobrevivência',tracos=['dedicação'])
add("Scout's Charge",'Investida do Batedor',4,213,'Batedor','Escolha um inimigo. Ande, use Fintar contra ele e faça um Golpe contra ele. Para Fintar, pode usar Furtividade no lugar de Enganação, aproveitando o terreno para surpreendê-lo.','Anda, Finta com Enganação ou Furtividade e então Golpeia.',pre='Dedicação de Batedor',acoes=2,tracos=['floreio'])
add('Terrain Scout','Batedor de Terreno',4,213,'Batedor','Recebe duas vezes o talento de perícia Espreitador de Terreno, escolhendo terreno diferente em cada vez. Ao Evitar Ser Notado durante exploração, se aliados usarem Seguir o Especialista para acompanhá-lo, escolha um deles para receber o benefício de um de seus talentos Espreitador de Terreno.','Recebe dois terrenos e compartilha um deles com um aliado que o segue.',pre='Dedicação de Batedor')
add('Fleeting Shadow','Sombra Fugaz',6,213,'Batedor','Você se Esconde e então Esgueira duas vezes.','Esconde-se e Esgueira duas vezes.',pre='Dedicação de Batedor',acoes=2,tracos=['floreio'])
add("Scout's Speed",'Velocidade do Batedor',6,213,'Batedor','Recebe +3 m de estado no Deslocamento. Para calcular sua velocidade de viagem, esse bônus aumenta para +6 m.','Aumenta o Deslocamento em combate e ainda mais durante viagens.',pre='Dedicação de Batedor')
add("Scout's Pounce",'Bote do Batedor',10,213,'Batedor','Ande até seu Deslocamento e então faça dois Golpes. Se estava escondido ou despercebido pelo alvo, ele fica desprevenido contra ambos. A penalidade por ataques múltiplos se aplica normalmente a cada ataque.','Sai das sombras, move-se e desfere dois Golpes.',pre='Dedicação de Batedor',acoes=2,tracos=['floreio'],requisitos='escondido ou despercebido por todos os oponentes e a mais de 3 m de qualquer inimigo')

# Trapaceiro de Pergaminhos — p. 214
add('Scroll Trickster Dedication','Dedicação de Trapaceiro de Pergaminhos',2,214,'Trapaceiro de Pergaminhos','Recebe o talento Enganar Item Mágico e +2 de circunstância nas verificações para Enganar pergaminhos. Uma falha crítica ao Enganar Item Mágico com um pergaminho se torna falha.','Aprende a ativar pergaminhos com mais segurança.',pre='treinado em Arcanismo, Natureza, Ocultismo ou Religião',tracos=['dedicação'])
add('Basic Scroll Cache','Reserva Básica de Pergaminhos',6,214,'Trapaceiro de Pergaminhos','Durante preparações diárias, cria um pergaminho temporário com magia de 1ª graduação. A magia deve ser comum, acessível ou conjurável por você, e você deve ser treinado na perícia de ao menos uma tradição dela. Pode usar Aprender uma Magia para ampliar as opções mesmo sem ser conjurador. O pergaminho desaparece nas próximas preparações e não serve para Aprender a Magia. No 8º nível, cria também um segundo pergaminho, de 2ª graduação.','Prepara diariamente pergaminhos temporários de 1ª e depois 2ª graduação.',pre='Dedicação de Trapaceiro de Pergaminhos')
add('Skim Scroll','Leitura Dinâmica de Pergaminho',8,214,'Trapaceiro de Pergaminhos','Interaja para sacar um pergaminho e então use Enganar Item Mágico nele.','Saca e tenta ativar um pergaminho em duas ações.',pre='Dedicação de Trapaceiro de Pergaminhos',acoes=2)
add('Expert Scroll Cache','Reserva Especialista de Pergaminhos',12,214,'Trapaceiro de Pergaminhos','Além dos pergaminhos da Reserva Básica, cria diariamente um pergaminho de 3ª graduação. No 14º nível, adiciona um de 4ª; no 16º, um de 5ª.','Amplia a reserva diária com pergaminhos de 3ª a 5ª graduação.',pre='Reserva Básica de Pergaminhos')
add('Master Scroll Cache','Reserva Mestre de Pergaminhos',18,214,'Trapaceiro de Pergaminhos','Além das Reservas Básica e Especialista, cria diariamente um pergaminho de 6ª graduação. No 20º nível, adiciona um de 7ª.','Amplia a reserva diária com pergaminhos de 6ª e 7ª graduação.',pre='Reserva Especialista de Pergaminhos')

# Sucateiro — p. 215
add('Scrounger Dedication','Dedicação de Sucateiro',2,215,'Sucateiro','Pode Criar sem ferramentas ou oficina apropriadas e memoriza todas as fórmulas, pagando normalmente para aprendê-las. Recebe Remendar com Sucata: em 10 minutos, Cria com materiais disponíveis um item temporário que tenha memorizado ou cuja fórmula conheça; deve ser comum, não mágico, de até metade de seu nível, e ser arma, armadura ou equipamento de aventura não consumível; alternativamente, cria 10 munições. Não cria informação nem magia. O item é malfeito, mas pode designar uma criatura sem a penalidade de usá-lo, e dura 1d4 horas, roladas secretamente pelo MJ.','Cria rapidamente equipamento mundano temporário usando sucata.',pre='treinado em Ofício',tracos=['incomum','dedicação'])
add('Reverse Engineering','Engenharia Reversa',4,215,'Sucateiro','Recebe +2 de circunstância em Ofício para obter uma fórmula por engenharia reversa e precisa de apenas 1 dia de preparação, em vez de 2. Com sucesso crítico, pode criar a fórmula e remontar o item original, em vez de receber a fórmula e matéria-prima de metade do valor.','Obtém fórmulas mais rápido e pode preservar o objeto em sucesso crítico.',pre='Dedicação de Sucateiro; especialista em Ofício',tracos=['perícia'])
add('Magical Scrounger','Sucateiro Mágico',6,215,'Sucateiro','Uma vez por dia, pode Remendar com Sucata um item mágico temporário. Ele deve ser comum, mágico, de até metade de seu nível e poder ser segurado, empunhado ou vestido. Requisitos de Criação continuam obrigatórios. Não pode ser consumível, runa nem item com runas; se precisar ser vestido ou afixado, removê-lo depois destrói o item.','Cria uma vez por dia um item mágico temporário limitado.',pre='Dedicação de Sucateiro; Criação Mágica',frequencia='uma vez por dia')
add('Expert Disassembly','Desmontagem Especialista',7,215,'Sucateiro','Pode usar Ofício no lugar de Ladroagem para Desabilitar um Dispositivo ou Abrir uma Fechadura.','Substitui Ladroagem por Ofício em dispositivos e fechaduras.',pre='Dedicação de Sucateiro; mestre em Ofício',tracos=['perícia'])

# Sentinela — p. 216
add('Sentinel Dedication','Dedicação de Sentinela',2,216,'Sentinela','Torna-se treinado em armaduras leves e médias; se já era, torna-se treinado em pesadas. Sempre que uma característica de classe conceder especialista ou maior em qualquer armadura, recebe a mesma proficiência nos tipos concedidos por este talento. Se uma característica conceder especialista em defesa sem armadura e você tiver 13º nível ou mais, também se torna especialista nesses tipos.','Concede e faz progredir proficiência com armaduras.',tracos=['dedicação'])
add('Steel Skin','Pele de Aço',4,216,'Sentinela','Você não fica fatigado por dormir vestindo armadura.','Pode dormir de armadura sem sofrer fadiga.',pre='Dedicação de Sentinela; treinado em Sobrevivência',tracos=['perícia'])
add('Armor Specialist','Especialista em Armadura',6,216,'Sentinela','Recebe os efeitos de especialização de todas as armaduras em que é proficiente.','Ativa os efeitos de especialização de suas armaduras.',pre='Dedicação de Sentinela')
add('Armored Rebuff','Repulsa Blindada',8,216,'Sentinela','Tente Atletismo para Empurrar o inimigo que acionou a reação, mesmo sem uma mão livre. Em caso de sucesso, não pode Andar para segui-lo, pois o golpe rebatido é que o empurra.','Rebate uma falha crítica inimiga e tenta Empurrar sem mão livre.',pre='Dedicação de Sentinela',acoes='reação',gatilho='inimigo adjacente obtém falha crítica em Golpe corpo a corpo contra você',requisitos='vestindo armadura média ou pesada')
add('Mighty Bulwark','Baluarte Poderoso',10,216,'Sentinela','O bônus do traço baluarte aumenta de +3 para +4 e se aplica a todas as salvaguardas de Reflexos, não apenas às que causam dano.','Melhora baluarte para +4 e o aplica a todo Reflexos.',pre='Dedicação de Sentinela')

# Armadilheiro — p. 217
add('Snarecrafter Dedication','Dedicação de Armadilheiro',2,217,'Armadilheiro','Recebe Criação de Laços. Ao instalar um laço, a CD de salvaguarda usa a maior entre sua CD de classe e a do laço. Um laço que exigiria 1 minuto pode ser Criado com 3 ações Interagir. Nas preparações diárias, prepara gratuitamente quatro laços de seu livro para uso rápido; seis se mestre em Ofício e oito se lendário. Ao elevar Ofício a especialista, mestre ou lendário, adiciona três fórmulas de laço de seu nível ou menor. Patrulheiros podem usar Sobrevivência no lugar de Ofício em pré-requisitos e funções deste arquétipo.','Prepara laços gratuitos e os instala rapidamente usando sua melhor CD.',pre='treinado em Ofício',tracos=['dedicação'])
add('Surprise Snare','Laço Surpresa',4,217,'Armadilheiro','Instale um laço preparado para uso rápido no espaço ocupado por um inimigo. Deve ser um laço cujo tempo normal de Criação seja 1 minuto ou menos; ele é acionado automaticamente.','Instala e dispara um laço diretamente sob um inimigo.',pre='Dedicação de Armadilheiro',acoes=2,tracos=['manuseio'])
add('Remote Trigger','Gatilho Remoto',6,217,'Armadilheiro','Pode Golpear um laço para acioná-lo prematuramente. Se você o criou, acerta automaticamente; se outra pessoa o criou, faça Golpe à distância contra a CD de Ofício dela e só aciona em caso de acerto.','Dispara um laço à distância, automaticamente se for seu.',pre='Dedicação de Armadilheiro')
add('Giant Snare','Laço Gigante',10,217,'Armadilheiro','Ao preparar laços para uso rápido, pode preparar alguns como gigantes. Cada um ocupa área de 3 m por 3 m e consome duas preparações; pode ser acionado por quem entre em qualquer parte e seus efeitos abrangem toda a área.','Troca duas preparações por um laço de área 3 m por 3 m.',pre='Dedicação de Armadilheiro')
add('Lightning Snares','Laços Relâmpago',12,217,'Armadilheiro','Um laço que normalmente exige 1 minuto para Criar pode ser Criado usando uma única ação Interagir.','Cria com uma ação laços cujo tempo seria 1 minuto.',pre='Dedicação de Armadilheiro; mestre em Ofício')
add('Plentiful Snares','Laços Abundantes',12,217,'Armadilheiro','Dobre a quantidade de laços preparados concedida por Dedicação de Armadilheiro.','Dobra seus laços gratuitos preparados diariamente.',pre='Dedicação de Armadilheiro')

# Diletante de Talismãs — p. 218
add('Talisman Dabbler Dedication','Dedicação de Diletante de Talismãs',2,218,'Diletante de Talismãs','Pode Criar talismãs, conhece de memória as fórmulas de todos os talismãs comuns de seu nível ou menor e não precisa de livro para elas. Nas preparações, cria dois talismãs temporários de nível de item até metade do seu, cujas fórmulas conheça; desaparecem nas próximas preparações. A CD deles usa a maior entre sua CD de classe, CD de magia e CD do talismã. Ao Afixar um Talismã durante 10 minutos, pode afixar ou remover até quatro em qualquer combinação.','Conhece fórmulas comuns e prepara dois talismãs temporários por dia.',tracos=['dedicação'])
add('Quick Fix','Afixação Rápida',4,218,'Diletante de Talismãs','Recebe Afixação Rápida mesmo sem cumprir os pré-requisitos. Com ela, pode afixar ou remover até quatro talismãs em 1 minuto. No 12º nível, pode Afixar um Talismã como atividade de 3 ações independentemente de sua proficiência em Ofício.','Afixa ou remove quatro talismãs rapidamente.',pre='Dedicação de Diletante de Talismãs')
add('Deeper Dabbler','Diletante Aprofundado',8,218,'Diletante de Talismãs','Cria dois talismãs adicionais durante as preparações diárias. Pode selecionar este talento uma segunda vez no 14º nível ou acima.','Acrescenta dois talismãs temporários diários e pode ser repetido no 14º.',pre='Dedicação de Diletante de Talismãs')
add('Talismanic Sage','Sábio Talismânico',14,218,'Diletante de Talismãs','Ao Afixar um Talismã, pode tratar especialmente um item para permitir que tenha dois talismãs ativos ao mesmo tempo. O tratamento termina quando usar esta habilidade para tratar outro item.','Permite dois talismãs ativos simultaneamente em um item tratado.',pre='Dedicação de Diletante de Talismãs')

# Vigilante — p. 219–220
add('Vigilante Dedication','Dedicação de Vigilante',2,219,'Vigilante','Você possui identidade social e identidade vigilante, ambas reais. Para descobrir a outra, alguém deve Buscar e testar Percepção contra sua CD de Enganação, que é 20 + seu modificador de proficiência. Trocar exige 1 minuto, fora da vista, e efeitos de aparência não reduzem o tempo. Recordar Conhecimento e detecção tratam as identidades separadamente. Talentos de classe e vigilante pertencem à identidade vigilante e usá-los na social pode expô-lo. Se exposto publicamente, perde os benefícios de disfarce, mas pode gastar 1 semana de recesso criando nova identidade social.','Mantém duas identidades mecanicamente separadas e protegidas por Enganação.',pre='treinado em Enganação',tracos=['incomum','dedicação'])
add('Hidden Magic','Magia Oculta',4,220,'Vigilante','Nas preparações diárias, ajusta quaisquer itens mágicos para parecerem não mágicos até as próximas preparações. Para enxergar a magia com Detectar Magia ou Ler Aura, o conjurador precisa passar em Percepção contra sua CD de Enganação.','Esconde diariamente as auras mágicas de seus equipamentos.',pre='Dedicação de Vigilante; especialista em Arcanismo, Natureza, Ocultismo ou Religião',tracos=['perícia'])
add('Minion Guise','Disfarce de Lacaio',4,220,'Vigilante','Na identidade social, concede identidade social a companheiro animal, familiar, mascote ou outro lacaio de classe ou talento. Ao trocar, muda sua aparência para criatura socialmente aceitável do mesmo tipo. Ordenar habilidades mágicas ou de combate incomuns pode expor sua identidade.','Disfarça um lacaio junto com sua identidade social.',pre='Dedicação de Vigilante; companheiro animal ou familiar; especialista em Enganação',tracos=['perícia'])
add('Safe House','Refúgio Seguro',4,220,'Vigilante','Estabelece esconderijo de dois cubos de 3 m em local acessível. Protege pessoas e objetos como Véu de Privacidade, usando Enganação na CD de neutralização e metade de seu nível, arredondada para cima, na graduação. Montar ou mover exige uma semana. O tamanho aumenta para 4 cubos com especialista, 8 com mestre e 16 com lendário em Enganação.','Cria um refúgio protegido de detecção mágica e ampliado por proficiência.',pre='Dedicação de Vigilante')
add('Social Purview','Âmbito Social',4,220,'Vigilante','Escolha um arquétipo cujos pré-requisitos cumpra. Recebe sua dedicação e pode escolher seus talentos sem ter obtido talentos vigilantes suficientes para outra dedicação. Eles pertencem à identidade social: usá-los nela não ameaça o segredo, mas usá-los como vigilante pode expô-lo.','Vincula outro arquétipo à sua identidade social.',pre='Dedicação de Vigilante',tracos=['perícia'])
add('Startling Appearance','Aparição Surpreendente',6,220,'Vigilante','Faça um Golpe contra a criatura que não o notou; ela está desprevenida contra ele. Se acertar, permanece desprevenida pelo restante do seu turno e fica assustada 1, ou assustada 2 em acerto crítico.','Ataca de surpresa e mantém o alvo desprevenido e assustado.',pre='Dedicação de Vigilante',acoes=2,requisitos='não notado pela criatura-alvo')
add('Quick Change','Troca Rápida',7,220,'Vigilante','Troca de identidade com atividade de 3 ações em vez de 1 minuto. Se for lendário em Enganação, faz a troca com uma ação.','Troca de identidade em três ações, ou uma se lendário.',pre='Dedicação de Vigilante; mestre em Enganação')
add('Subjective Truth','Verdade Subjetiva',7,220,'Vigilante','Desde que sua afirmação seja verdadeira do ponto de vista da identidade atual, pode enganar efeitos que revelam mentiras, como Anel da Verdade.','Engana magia detectora de mentiras com verdades da identidade atual.',pre='Dedicação de Vigilante; mestre em Enganação',tracos=['perícia'])
add('Many Guises','Muitos Disfarces',8,220,'Vigilante','Ao trocar identidade, pode assumir uma pessoa mundana genérica de sua ancestralidade, qualquer gênero e profissão comum. Magias e habilidades o detectam como essa identidade, salvo neutralização contra a mesma CD de Enganação da dedicação. Usar habilidades de classe ou dedicação encerra o disfarce.','Assume identidades mundanas genéricas resistentes a detecção.',pre='Dedicação de Vigilante')
add('Frightening Appearance','Aparição Aterrorizante',12,220,'Vigilante','Ao usar Aparição Surpreendente, pode tentar Desmoralizar cada inimigo em emanação de 3 m que não o notava antes do Golpe.','Desmoraliza todos os inimigos próximos surpreendidos por sua aparição.',pre='especialista em Intimidação; Aparição Surpreendente')
add('Stunning Appearance','Aparição Atordoante',16,220,'Vigilante','Ao usar Aparição Surpreendente e acertar inimigo de seu nível ou menor, ele fica atordoado 1, ou atordoado 2 em acerto crítico.','A aparição atordoa inimigos de nível não superior ao seu.',pre='Aparição Surpreendente')

# Viking — p. 221
add('Viking Dedication','Dedicação de Viking',2,221,'Viking','Recebe Conhecimento Adicional para Conhecimento de Navegação e de Guerra. Ao usar Deslocamento terrestre, ignora terreno difícil de água rasa, como pântanos ou praias. Um sucesso em Atletismo para Nadar se torna sucesso crítico.','Concede conhecimentos, mobilidade em água rasa e melhora Nadar.',pre='treinado em Atletismo',tracos=['dedicação'])
add('Hurling Charge','Investida de Arremesso',4,221,'Viking','Faça um Golpe à distância com a arma arremessável, Ande e Interaja para sacar outra arma; Interagir não aciona reações. Se estiver em fúria e terminar adjacente a inimigo, ele fica desprevenido contra seu próximo Golpe com a arma sacada até o fim do próximo turno.','Arremessa, avança e saca outra arma sem provocar reações.',pre='Dedicação de Viking',acoes=2,requisitos='empunhando arma arremessável')
add('Viking Weapon Familiarity','Familiaridade com Armas Vikings',4,221,'Viking','Recebe Bloqueio com Escudo. Para proficiência, trata machado de batalha, machadinha, espada longa, broquel de escudo, cravos de escudo e espada curta como armas simples. No 5º nível, acertos críticos com elas recebem o efeito de especialização crítica.','Concede Bloqueio com Escudo e familiaridade com armas vikings.',pre='Dedicação de Viking')
add('Second Shield','Segundo Escudo',6,221,'Viking','Interaja para sacar um escudo que carrega ou um escudo sem dono ao alcance. Pode sacar objeto que o MJ aceite como escudo improvisado, como mesa ou cadeira. O novo escudo não fica erguido até usar Erguer Escudo.','Saca imediatamente um escudo substituto ou improvisado quando o atual quebra.',pre='Dedicação de Viking',acoes='reação',gatilho='seu Bloqueio com Escudo quebra ou destrói seu escudo')
add('Into the Fray','No Meio da Peleja',8,221,'Viking','Salte, Ande ou Nade. Durante o movimento, faça dois Golpes corpo a corpo em pontos quaisquer: um com a arma de uma mão e outro com escudo ou arma anexada a ele. Devem atingir inimigos diferentes. Ambos contam para a penalidade por ataques múltiplos, mas ela só aumenta depois dos dois.','Move-se e ataca dois inimigos diferentes com arma e escudo.',pre='Dedicação de Viking',acoes=2,requisitos='arma corpo a corpo de uma mão e escudo em mãos diferentes')

# Improvisador de Armas — p. 222
add('Weapon Improviser Dedication','Dedicação de Improvisador de Armas',2,222,'Improvisador de Armas','Não sofre a penalidade normal de –2 em ataques com armas improvisadas. O dado mínimo de dano delas é 1d6, ou 1d4 se forem ágeis.','Remove a penalidade e estabelece dano mínimo de armas improvisadas.',pre='treinado em armas marciais',tracos=['dedicação'])
add('Improvised Pummel','Pancada Improvisada',4,222,'Improvisador de Armas','Ao Golpear com arma improvisada empunhada, recebe +1 de item no ataque e pode causar dois dados de dano de arma. Em acerto crítico, a arma quebra após os efeitos; se Dureza maior que seu nível, artefato, amaldiçoada ou difícil de destruir, não quebra, mas o crítico vira acerto normal. Pode recusar os benefícios. No 12º nível o bônus vira +2; no 16º causa três dados. Com bandagens de golpes poderosos, use o maior bônus e pode usar seus dados; runas de propriedade se aplicam ao usar esses dados, se compatíveis segundo o MJ.','Fortalece um Golpe improvisado, arriscando quebrar a arma no crítico.',pre='Dedicação de Improvisador de Armas')
add('Surprise Strike','Golpe Surpresa',6,222,'Improvisador de Armas','Ao Golpear com arma improvisada uma criatura que não o viu Golpear com uma delas ou desconheça sua habilidade, ela fica desprevenida contra esse Golpe.','O primeiro uso inesperado de arma improvisada deixa o alvo desprevenido.',pre='Dedicação de Improvisador de Armas')
add('Improvised Critical','Crítico Improvisado',8,222,'Improvisador de Armas','Pode aplicar especialização crítica a armas improvisadas. Para cada objeto, o MJ define o efeito mais apropriado conforme seu tipo.','Concede especialização crítica determinada pelo formato do objeto.',pre='Dedicação de Improvisador de Armas')
add('Makeshift Strike','Golpe de Ocasião',8,222,'Improvisador de Armas','Interaja para pegar objeto sem dono ao alcance que possa servir como arma improvisada e então Golpeie com ele.','Apanha um objeto e Golpeia com ele em duas ações.',pre='Dedicação de Improvisador de Armas',acoes=2)
add('Shattering Strike','Golpe Estilhaçante',10,222,'Improvisador de Armas','A arma improvisada se despedaça e é destruída, causando 3d6 perfurante adicional à criatura atingida. Esse dano extra aplicado no crítico não é dobrado.','Destrói a arma quebrada para acrescentar 3d6 perfurante não dobrado.',pre='Pancada Improvisada',acoes='reação',gatilho='arma improvisada empunhada fica quebrada por sucesso crítico em Pancada Improvisada')

# Lutador — p. 223 (a página termina no talento Quebrador de Cotovelo)
add('Wrestler Dedication','Dedicação de Lutador',2,223,'Lutador','Torna-se especialista em Atletismo e recebe Lutador Titânico. Não sofre –2 de circunstância por fazer ataque letal com ataques desarmados não letais. Recebe +2 de circunstância na CD de Fortitude contra tentativas de Agarrá-lo ou Engoli-lo Inteiro.','Especializa Atletismo e melhora combate desarmado e resistência a agarrões.',pre='treinado em Atletismo',tracos=['dedicação'])
add('Disengaging Twist','Torção de Desengajamento',4,223,'Lutador','Tente Atletismo para Escapar da condição acionadora, com +2 de circunstância na verificação.','Reage a um agarrão tentando Escapar com +2.',pre='Dedicação de Lutador',acoes='reação',gatilho='uma criatura lhe dá a condição agarrado ou restringido')
add('Elbow Breaker','Quebra-Cotovelo',4,223,'Lutador','Faça Golpe corpo a corpo desarmado contra a criatura agarrada ou restringida. Em sucesso crítico, derrube um item segurado por ela no espaço dela. Em sucesso, tentativas posteriores de Desarmar esse item recebem +2 de circunstância e o alvo sofre –2 de circunstância em ataques com ele ou verificações que exijam pegada firme. A criatura encerra o efeito ao Interagir para ajustar a pegada; caso contrário, dura enquanto segurar o item.','Golpeia um alvo agarrado para soltar ou enfraquecer sua pegada.',pre='Dedicação de Lutador',acoes=2,requisitos='ter uma criatura agarrada ou restringida')

# Arqueiro Místico — p. 200
add('Enchanting Shot','Disparo Encantador',8,200,'Arqueiro Místico','Faça um Golpe com arco ou besta. No acerto, causa 2d6 mental adicional; no crítico, também deixa atordoado 1. O dano vira 3d6 com runa impactante maior ou 4d6 com impactante superior.','Golpe causa dano mental adicional e pode atordoar.',pre='Dedicação de Arqueiro Místico',acoes=2,tracos=['emoção','mágico','mental'])
add('Magic Ammunition','Munição Mágica',8,200,'Arqueiro Místico','Escolha três munições mágicas comuns de até 4º nível do GM Core ou deste livro; o MJ pode permitir outras apropriadas. Recebe Transformar Munição: uma ação, mágico, uma vez por rodada; transforma flecha ou virote não mágico em um tipo escolhido, que deve ser disparado até o fim do turno. Ativações ainda custam ações e o tipo pode ser normalmente incompatível com o projétil. Pode selecionar este talento várias vezes, escolhendo mais três tipos a cada vez.','Transforma projéteis em três tipos escolhidos de munição mágica.',pre='Dedicação de Arqueiro Místico',frequencia='Transformar Munição: uma vez por rodada')
add('Precious Ammunition','Munição Preciosa',8,200,'Arqueiro Místico','Encante uma munição em sua posse: escolha ferro frio ou prata; se dispará-la até o fim do turno, conta como esse material. No 14º nível, pode escolher adamantina.','Converte temporariamente a munição em material precioso.',pre='Dedicação de Arqueiro Místico',acoes=1)
add('Eldritch Reload','Recarga Mística',10,200,'Arqueiro Místico','Interaja para recarregar uma arma empunhada.','Recarrega depois de usar magia ou munição mágica.',pre='Dedicação de Arqueiro Místico',acoes=1,requisitos='última ação foi Disparo Místico, Conjurar de espaço ou ativar munição mágica',ambiguidade='nível deslocado no OCR; reconstruído pela ordem editorial')
add('Homing Shot','Disparo Teleguiado',10,200,'Arqueiro Místico','Faça Golpe com arco ou besta contra inimigo visível. A munição contorna esquinas; ignore ocultado e toda cobertura.','Disparo contorna obstáculos e ignora cobertura e ocultação.',pre='Dedicação de Arqueiro Místico',acoes=2,tracos=['mágico'])
add('Expert Eldritch Archer Spellcasting','Conjuração Especialista de Arqueiro Místico',12,200,'Arqueiro Místico','Recebe os benefícios de conjuração especialista da página 173.','Avança a conjuração de arqueiro místico para especialista.',pre='Conjuração Básica de Arqueiro Místico')
add('Incorporeal Shot','Disparo Incorpóreo',16,200,'Arqueiro Místico','Faça Golpe com arco ou besta contra inimigo observado ou escondido, mas não indetectado. O projétil segue reto através de barreiras não mágicas; barreiras mágicas o detêm. Ignora cobertura, ocultado, escondido e bônus de CA de escudos; recebe +4 de estado contra criaturas de armadura. Escudo não mágico não pode reduzir o dano com Bloqueio.','Projétil atravessa matéria comum e ignora quase todas as defesas de cobertura.',pre='Dedicação de Arqueiro Místico',acoes=2,tracos=['mágico'],frequencia='uma vez por dia')
add('Fatal Shot','Disparo Fatal',18,200,'Arqueiro Místico','Faça Golpe com arco ou besta; no acerto, causa 10d10 de precisão adicional. No crítico, o alvo faz Fortitude contra a maior CD de classe ou magia e morre em falha; a salvaguarda tem Morte e Incapacitação.','Disparo diário causa 10d10 adicional e pode matar no crítico.',pre='Dedicação de Arqueiro Místico',acoes=3,tracos=['mágico'],frequencia='uma vez por dia')
add('Master Eldritch Archer Spellcasting','Conjuração Mestre de Arqueiro Místico',18,200,'Arqueiro Místico','Recebe os benefícios de conjuração mestre da página 173.','Avança a conjuração de arqueiro místico para mestre.',pre='Conjuração Especialista de Arqueiro Místico')

# Mestre de Familiar — p. 201
add('Familiar Master Dedication','Dedicação de Mestre de Familiar',2,201,'Mestre de Familiar','Recebe um familiar. Se já possuir um, recebe Familiar Aprimorado.','Concede um familiar ou aprimora o existente.',tracos=['dedicação'])
add('Familiar Mascot','Familiar Mascote',4,201,'Mestre de Familiar','Ao selecionar habilidades de mestre, pode escolher um aliado para receber uma habilidade específica. Cada habilidade beneficia apenas um personagem e só pode ser selecionada uma vez, salvo indicação contrária.','Compartilha habilidades de mestre com aliados.',pre='Dedicação de Mestre de Familiar')
add('Familiar Conduit','Familiar Condutor',4,201,'Mestre de Familiar','Se sua próxima ação for Conjurar uma Magia com alcance, use o familiar como ponto de origem.','Canaliza uma magia a partir da posição do familiar.',pre='Dedicação de Mestre de Familiar; capacidade de conjurar magias',acoes=2,tracos=['concentração','metamágico'],requisitos='linha de efeito até o familiar')
add('Improved Familiar','Familiar Aprimorado',6,201,'Mestre de Familiar','Reduza em 2 o número de habilidades exigido para transformar seu familiar em um familiar específico.','Facilita obter familiares específicos.',pre='Dedicação de Mestre de Familiar')
add('Mutable Familiar','Familiar Mutável',8,201,'Mestre de Familiar','Em atividade de exploração de 10 minutos, troque habilidades entre anfíbio, escavador, escalador, visão no escuro, movimento rápido, destreza manual, resistência e faro. Só pode trocar escolhas diárias, não habilidades obrigatórias nem pré-requisitos de outras.','Reconfigura habilidades físicas do familiar em dez minutos.',pre='Dedicação de Mestre de Familiar')
add('Incredible Familiar','Familiar Incrível',10,201,'Mestre de Familiar','Pode selecionar seis habilidades de familiar ou mestre por dia, em vez de quatro.','Aumenta para seis as habilidades diárias.',pre='Familiar Aprimorado')

# Gladiador — p. 202
add('Gladiator Dedication','Dedicação de Gladiador',2,202,'Gladiador','Recebe Conhecimento Adicional de Gladiadores ou outro Conhecimento se já treinado. No início de combate com espectadores, ganha PV temporários iguais ao nível por 1 minuto e pode usar Performance na iniciativa. Espectadores são criaturas sapientes que observam sem participar; o MJ decide.','Transforma combate com plateia em PV temporários e iniciativa de Performance.',pre='Performance Impressionante',tracos=['dedicação'])
add('Fancy Moves','Movimentos Extravagantes',4,202,'Gladiador','Pode usar Performance para Desmoralizar.','Substitui Intimidação por Performance para Desmoralizar.',pre='Dedicação de Gladiador; especialista em Performance',tracos=['perícia'])
add('Play to the Crowd','Jogar para a Plateia',4,202,'Gladiador','Faça Performance contra a maior entre a CD padrão de seu nível e a CD para Impressionar espectadores. Em sucesso, escolha um benefício; em crítico, dois: PV temporários iguais ao nível por 1 minuto; +1 circunstancial na CA até o fim do próximo turno; ou +1 circunstancial no próximo ataque antes do fim do próximo turno.','Ao derrubar inimigo, conquista um ou dois benefícios da plateia.',pre='Dedicação de Gladiador',acoes='reação',tracos=['concentração'],gatilho='reduz um inimigo a 0 PV em combate com espectadores')
add('Stage Fighting','Combate Cênico',4,202,'Gladiador','Não sofre –2 circunstancial ao fazer ataque não letal com arma ou ataque desarmado sem o traço não letal.','Remove a penalidade de ataques não letais improvisados.',pre='Dedicação de Gladiador')
add('Performative Weapons Training','Treinamento com Armas Performáticas',6,202,'Gladiador','Para proficiência, trata bastão bo, capa de duelo, corrente com cravos, bengala-espada, tridente, mangual de guerra e chicote como simples; o MJ pode adicionar outras. Acertos críticos recebem especialização crítica.','Concede familiaridade e especialização com armas vistosas.',pre='Dedicação de Gladiador')
add('Call Your Shot','Anunciar Seu Golpe',8,202,'Gladiador','Ao ter sucesso em Jogar para a Plateia, pode escolher também deixar uma criatura visível a até 9 m assustada 2; o efeito é Emoção, Medo, Mental e Visual.','Adiciona assustado 2 às recompensas de Jogar para a Plateia.',pre='Jogar para a Plateia')

# Herbalista — p. 203
add('Herbalist Dedication','Dedicação de Herbalista',2,203,'Herbalista','Recebe alquimia avançada para criar quatro consumíveis alquímicos com Cura; reduz para dois se não se preparou em ambiente selvagem. Memoriza as fórmulas desses itens herbais.','Prepara diariamente consumíveis de cura herbais.',pre='treinado em Natureza; Medicina Natural',tracos=['dedicação'])
add('Advanced Herbalism','Herbalismo Avançado',2,203,'Herbalista','Torna-se especialista em Natureza e pode usar Natureza em vez de Ofício para criar consumíveis alquímicos com Cura, usando ferramentas de curandeiro no lugar de alquimista e sem exigir treinamento em Ofício.','Usa Natureza e ferramentas de curandeiro para criar itens de cura.',ambiguidade='cabeçalho perdeu traços e pré-requisitos no OCR')
add('Fresh Ingredients','Ingredientes Frescos',4,203,'Herbalista','Ao usar Medicina Natural para Tratar Ferimentos, recebe +2 circunstancial por ingredientes frescos mesmo fora da natureza, ou +4 em ambiente selvagem.','Melhora Tratar Ferimentos com ingredientes frescos.',pre='Dedicação de Herbalista',tracos=['perícia'])
add('Poultice Preparation','Preparação de Cataplasma',4,203,'Herbalista','Ao criar elixir herbal, pode torná-lo cataplasma: recebe Óleo, permanece alquímico e perde Elixir; aplique com Interagir de uma mão. Além do efeito normal, o recipiente testa imediatamente recuperação de dano persistente de ácido, sangramento ou fogo com a redução de CD por assistência.','Transforma elixires em óleos que também ajudam contra dano persistente.',pre='Dedicação de Herbalista')
add('Advanced Herbalism II','Herbalismo Avançado Aprimorado',6,203,'Herbalista','Pode criar até seis itens herbais diários. No 10º nível, pode selecionar novamente para elevar a oito.','Aumenta itens herbais diários para seis ou oito.',pre='Dedicação de Herbalista; especialista em Natureza',ambiguidade='OCR deslocou o cabeçalho; progressão identificada como segunda seleção de Herbalismo Avançado')
add('Endemic Herbs','Ervas Endêmicas',6,203,'Herbalista','Ao consumir item herbal, recebe por 1 minuto o benefício de onde foi criado: aquático +1 Fortitude; ártico ou deserto reduz em um grau frio ou calor ambiental por 1 hora; floresta +2 contra doenças e venenos; montanha +1 Reflexos; planícies +1 Vontade; pântano remove uma fonte de sangramento persistente; subterrâneo +1 Percepção.','Itens herbais concedem benefício conforme o ambiente de coleta.',pre='Dedicação de Herbalista; treinado em Sobrevivência',tracos=['aditivo'])

# Linguista — p. 204
add('Linguist Dedication','Dedicação de Linguista',2,204,'Linguista','Torna-se treinado em Sociedade, ou especialista se já treinado, e recebe Multilíngue duas vezes.','Melhora Sociedade e concede dois idiomas adicionais.',pre='falar pelo menos três idiomas',tracos=['dedicação'])
add('Multilingual Cipher','Cifra Multilíngue',4,204,'Linguista','Recebe +1 circunstancial para Decifrar Escrita. Quem decifra texto seu sofre –2, salvo se falar todos os idiomas usados na cifra.','Melhora suas cifras e a leitura de textos cifrados.',pre='Dedicação de Linguista; especialista em Sociedade',tracos=['perícia'])
add('Phonetic Training','Treinamento Fonético',4,204,'Linguista','Repete e transcreve foneticamente palavras com precisão sem entender o significado, inclusive sons impronunciáveis, para leitura posterior por alguém com este talento. Memorizar sequências longas continua difícil.','Registra fielmente qualquer fala sem precisar compreendê-la.',pre='Dedicação de Linguista; especialista em Sociedade',tracos=['perícia'])
add('Spot Translate','Tradução Imediata',4,204,'Linguista','Repita em outro idioma uma mensagem linguística ouvida. O efeito passa a contar como ambos os idiomas e pode afetar mais criaturas. Fala normal pode ser traduzida sem reação; esta reação inclui magias e ações como comando ou Desmoralizar.','Traduz instantaneamente efeitos linguísticos.',pre='Dedicação de Linguista',acoes='reação',tracos=['auditivo','linguístico'],gatilho='criatura a até 18 m usa efeito linguístico em idioma compreendido')
add('Analyze Idiolect','Analisar Idioleto',6,204,'Linguista','Depois de 10 minutos interagindo, memoriza maneirismos e recebe +4 circunstancial em testes e CDs de Enganação para Personificar a pessoa. Analisar outra substitui a anterior.','Estuda uma pessoa para imitá-la com +4.',pre='Dedicação de Linguista; especialista em Enganação e Sociedade',ambiguidade='traços corrompidos no OCR')
add('Read Shibboleths','Ler Xibóletes',7,204,'Linguista','Após 10 minutos de interação, descobre fato menor do ambiente social da pessoa. Se ela mentir, faz secretamente Enganação, Sociedade ou Conhecimento contra sua CD de Sociedade e fornece fato falso em sucesso. Após fato verdadeiro, recebe +1 circunstancial em Diplomacia e Enganação com ela.','Deduz origem social pela fala e usa os maneirismos para interagir.',pre='Dedicação de Linguista; mestre em Sociedade',tracos=['linguístico','perícia'])
add('Crude Communication','Comunicação Rudimentar',8,204,'Linguista','Após 10 minutos com criatura que fale idioma, o MJ testa Sociedade secretamente contra raridade do idioma. Em sucesso, entende a ideia e comunica conceitos básicos; em falha, interpreta ou transmite incorretamente. Lendário comunica instantaneamente sem teste e intui o meio de comunicação.','Estabelece comunicação básica sem idioma compartilhado.',pre='Dedicação de Linguista')

# Marechal — p. 205–206
add('Marshal Dedication','Dedicação de Marechal',2,205,'Marechal','Escolha Diplomacia ou Intimidação e torne-se treinado, ou especialista se já treinado. Consciente, emite aura de 4,5 m, Emoção, Mental e Visual, que concede a você e aliados +1 de estado contra medo.','Cria aura que protege aliados contra medo.',pre='treinado em armas marciais e em Diplomacia ou Intimidação',tracos=['dedicação'])
add('Dread Marshal Stance','Postura do Marechal Aterrador',4,205,'Marechal','Teste Intimidação contra CD normalmente fácil do nível. Em sucesso, aura concede +1 de estado no dano e críticos de seus integrantes assustam 1; com arma de vários dados, bônus pode igualar os dados. Falha não entra; falha crítica impede nova tentativa por 1 minuto.','Aura melhora dano e faz críticos assustarem.',pre='Dedicação de Marechal; treinado em Intimidação',acoes=1)
add('Inspiring Marshal Stance','Postura do Marechal Inspirador',4,205,'Marechal','Teste Diplomacia contra CD normalmente fácil do nível. Em sucesso, aura concede +1 de estado em ataques e salvaguardas contra mental. Falha não entra; falha crítica impede nova tentativa por 1 minuto.','Aura melhora ataques e defesa mental.',pre='Dedicação de Marechal; treinado em Diplomacia',acoes=1)
add('Snap Out of It!','Reaja!',4,206,'Marechal','Aliado na aura afetado por efeito mental de Vontade e até 1 minuto repete a salvaguarda com +1 circunstancial e encerra seu efeito em sucesso. Depois fica imune por 10 minutos.','Permite a aliado repetir salvaguarda contra efeito mental.',pre='Dedicação de Marechal',acoes=1,tracos=['auditivo','emoção','mental'])
add('Steel Yourself!','Prepare-se!',4,206,'Marechal','Aliado na aura recebe PV temporários iguais ao seu Carisma e +2 circunstancial em Fortitude até o início de seu próximo turno.','Fortalece um aliado por uma rodada.',pre='Dedicação de Marechal',acoes=1,tracos=['auditivo','emoção','mental'])
add('Cadence Call','Chamado Cadenciado',6,206,'Marechal','Aliados dispostos na aura ficam acelerados até o fim do próximo turno e usam a ação apenas para Andar. Quem a usar fica lento 1 até o fim do turno seguinte.','Acelera aliados por uma rodada com custo posterior.',pre='Dedicação de Marechal',acoes=1,tracos=['auditivo','floreio'],frequencia='uma vez por minuto')
add('Rallying Charge','Investida Revigorante',6,206,'Marechal','Ande até o Deslocamento e faça Golpe corpo a corpo. Se acertar e causar dano, aliados a até 18 m que viram recebem PV temporários iguais ao seu Carisma até o início do próximo turno.','Avança e inspira aliados com PV temporários.',pre='Dedicação de Marechal',acoes=2,tracos=['visual'])
add('Back to Back','Costas com Costas',8,206,'Marechal','Aliado adjacente só fica desprevenido por flanqueamento se você também estiver; você, adjacente a aliado, só fica se ao menos um deles também estiver.','Aliados adjacentes protegem-se mutuamente de flanqueamento.',pre='Dedicação de Marechal')
add('To Battle!','À Batalha!',8,206,'Marechal','Aliado na aura com reação disponível usa-a imediatamente: com uma ação sua, para Andar; com duas, para Golpear.','Concede movimento ou ataque imediato a um aliado.',pre='Dedicação de Marechal',acoes='1 ou 2',tracos=['auditivo','floreio'])
add('Topple Foe','Derrubar Adversário',10,206,'Marechal','Faça Atletismo para Derrubar o alvo do ataque aliado.','Aproveita o acerto aliado para tentar Derrubar.',pre='Dedicação de Marechal; treinado em Atletismo',acoes='reação',gatilho='aliado acerta Golpe corpo a corpo em inimigo adjacente a ambos')
add('Coordinated Charge','Investida Coordenada',12,206,'Marechal','Ande até seu Deslocamento e Golpeie corpo a corpo. Se acertar e causar dano, aliados a até 18 m que viram podem reagir para Andar, terminando mais perto do alvo.','Seu acerto permite que aliados avancem.',pre='Dedicação de Marechal',acoes=2)
add('Tactical Cadence','Cadência Tática',14,206,'Marechal','Aliados acelerados por Chamado Cadenciado podem usar a ação para Andar ou Golpear e não ficam lento depois.','Remove o custo e amplia o uso do Chamado Cadenciado.',pre='Chamado Cadenciado')
add('Target of Opportunity','Alvo de Oportunidade',14,206,'Marechal','Faça Golpe à distância com –2 contra o mesmo alvo. Não conta nem sofre penalidade por ataques múltiplos. Se acertar, combine seu dano com o do aliado para resistências e fraquezas.','Responde ao tiro aliado com disparo combinado.',pre='Dedicação de Marechal',acoes='reação',gatilho='aliado acerta Golpe à distância no primeiro incremento',requisitos='arma à distância ou arremessável em mãos')

# Artista Marcial — p. 207
add('Martial Artist Dedication','Dedicação de Artista Marcial',2,207,'Artista Marcial','O dado de dano do punho aumenta de 1d4 para 1d6 e você não sofre –2 por causar dano letal com ataque desarmado não letal.','Melhora punhos e remove penalidade letal.',tracos=['dedicação'])
add('Follow-Up Strike','Golpe de Continuação',6,207,'Artista Marcial','Faça outro Golpe desarmado corpo a corpo usando a mesma penalidade por ataques múltiplos do Golpe anterior que errou.','Repete rapidamente um ataque desarmado perdido.',pre='Dedicação de Artista Marcial',acoes=1,requisitos='última ação foi Golpe desarmado corpo a corpo que errou')
add('Grievous Blow','Golpe Doloroso',8,207,'Artista Marcial','Faça Golpe desarmado corpo a corpo. No acerto, causa dois dados adicionais e ignora resistência física igual ao nível. Conta como dois ataques. No 18º nível, causa três dados adicionais.','Golpe poderoso ignora resistência e acrescenta dados.',pre='Dedicação de Artista Marcial',acoes=2,tracos=['floreio'])
add('Path of Iron','Caminho de Ferro',14,207,'Artista Marcial','Ande sem provocar reações e faça durante o movimento até três Golpes corpo a corpo, cada um contra inimigo diferente. Todos contam, mas a penalidade só aumenta depois.','Move-se sem reações atacando até três inimigos.',pre='Dedicação de Artista Marcial',acoes=3,frequencia='uma vez por minuto')

# Demolidor — p. 208
add('Mauler Dedication','Dedicação de Demolidor',2,208,'Demolidor','Para proficiência, trata armas marciais corpo a corpo de duas mãos ou Duas Mãos como simples, e avançadas como marciais. Se ao menos especialista, recebe especialização crítica.','Concede familiaridade com armas grandes e seus críticos.',pre='Força 14',tracos=['dedicação'])
add('Clear the Way','Abrir Caminho',6,208,'Demolidor','Tente Empurrar até cinco criaturas adjacentes com testes separados, sem mão livre. Depois Ande metade do Deslocamento sem provocar reações das empurradas. Todos contam para penalidade, que só aumenta ao final.','Empurra vários inimigos e avança pelo espaço aberto.',pre='Dedicação de Demolidor',acoes=2,requisitos='arma corpo a corpo empunhada com duas mãos')
add('Shoving Sweep','Varredura Impulsora',8,208,'Demolidor','Tente Empurrar sem mão livre. Salvo sucesso crítico, o inimigo continua seu movimento depois.','Reage ao movimento inimigo tentando empurrá-lo.',pre='Dedicação de Demolidor; especialista em Atletismo',acoes='reação',gatilho='inimigo ao alcance deixa espaço em ação de movimento',requisitos='arma corpo a corpo empunhada com duas mãos')
add('Hammer Quake','Terremoto de Martelo',14,208,'Demolidor','Escolha espaço ao alcance, inclusive o seu; pode Golpear inimigo nele. Tente Derrubar todos os inimigos nesse e nos espaços adjacentes sem mão livre. Conta como três ataques e a penalidade só aumenta no fim.','Golpeia e derruba uma área ao redor do impacto.',pre='Dedicação de Demolidor',acoes=2,tracos=['floreio'],requisitos='arma corpo a corpo sem acuidade empunhada com duas mãos')
add('Avalanche Strike','Golpe de Avalanche',16,208,'Demolidor','Faça um Golpe corpo a corpo com arma de duas mãos contra cada inimigo ao alcance. Todos contam para a penalidade, mas ela só aumenta depois.','Ataca todos os inimigos ao alcance.',acoes=3,tracos=['floreio'],ambiguidade='nome omitido no OCR e identificado pela descrição e posição editorial')

# Médico — p. 209
add('Medic Dedication','Dedicação de Médico',2,209,'Médico','Torna-se especialista em Medicina. Sucesso em Medicina de Batalha ou Tratar Ferimentos cura +5 na CD 20, +10 na 30 ou +15 na 40. Uma vez por dia, pode ignorar imunidade temporária à Medicina de Batalha; se mestre, uma vez por hora.','Especializa Medicina, aumenta cura e permite novo tratamento.',pre='treinado em Medicina; Medicina de Batalha',tracos=['dedicação'])
add("Doctor's Visitation",'Visita Médica',4,209,'Médico','Ande e use Medicina de Batalha ou Tratar Veneno. Com duas ações, Ande e use Primeiros Socorros ou Tratar Condição, se possuir.','Move-se até o paciente e o trata.',pre='Dedicação de Médico',acoes='1 ou 2',tracos=['floreio'])
add('Treat Condition','Tratar Condição',4,209,'Médico','Escolha desajeitado, enfraquecido ou enjoado em criatura adjacente. Neutralize com Medicina contra a fonte. Artefato ou fonte acima do 20º exige Médico Lendário e CD +10; condição reaplicada continuamente retorna. Crítico reduz 2, sucesso reduz 1, falha crítica aumenta 1.','Reduz condições físicas com Medicina.',pre='Dedicação de Médico',acoes=1,tracos=['cura','manuseio','perícia'],requisitos='ferramentas de curandeiro em mãos ou vestidas e mão livre')
add('Holistic Care','Cuidado Holístico',6,209,'Médico','Adiciona amedrontado, estupefato e atordoado às condições tratáveis. Atordoado com duração, em vez de valor, não pode ser reduzido.','Permite tratar condições mentais adicionais.',pre='treinado em Diplomacia; Tratar Condição',tracos=['perícia'])
add('Resuscitate','Ressuscitar',16,209,'Médico','Faça Medicina CD 40 em criatura morta há até 3 rodadas e corpo quase intacto. Sucesso a revive como Reviver os Mortos, mantendo ferido anterior +1 ou ferido 1. Com sucesso ou falha, fica imune por 1 dia.','Tenta reviver alguém recém-morto.',pre='Dedicação de Médico; lendário em Medicina',acoes=3,tracos=['cura','manuseio'],requisitos='ferramentas de curandeiro em mãos ou vestidas e mão livre')

# Pirata — p. 210
add('Pirate Dedication','Dedicação de Pirata',2,210,'Pirata','Recebe Conhecimento Adicional de Navegação ou cidade costeira. Ignora terreno difícil ou irregular de solo instável. Recebe Ataque de Abordagem: duas ações, floreio; Ande duas vezes ou faça Acrobacia CD 20 para balançar até o dobro do Deslocamento e Golpeie; se embarcou ou desembarcou, causa um dado adicional.','Domina terreno naval e recebe uma investida de abordagem.',pre='treinado em Intimidação',tracos=['dedicação'])
add('Pirate Combat Training','Treinamento de Combate Pirata',4,210,'Pirata','Recebe Escalador de Combate ou Saqueador Subaquático. Trata machadinha, florete, cimitarra e chicote como simples; o MJ pode adicionar outras. No 5º nível, críticos recebem especialização crítica.','Concede um talento e familiaridade com armas piratas.',pre='Dedicação de Pirata')
add('Rope Runner','Corredor de Cordas',4,210,'Pirata','Recebe escalada de 4,5 m apenas em cordas e similares. Sucesso para Escalar ou Equilibrar-se nelas vira crítico e não fica desprevenido ao fazê-lo.','Move-se com segurança e rapidez por cordas.',pre='Dedicação de Pirata; treinado em Acrobacia e Atletismo',tracos=['perícia'])
add('Walk the Plank','Andar na Prancha',8,210,'Pirata','Tente Desmoralizar. Em sucesso, além do normal, pode obrigar o alvo a Andar até seu Deslocamento pelo caminho escolhido, sem reações. Só pode forçar espaço nocivo em crítico. O alvo fica imune por 10 minutos.','Intimida e força o alvo a caminhar.',pre='Dedicação de Pirata',acoes=1)

# Envenenador — p. 211
add('Poisoner Dedication','Dedicação de Envenenador',2,211,'Envenenador','Recebe alquimia avançada para criar quatro venenos alquímicos consumíveis por dia e memoriza suas fórmulas.','Prepara quatro venenos por dia.',pre='treinado em Ofício',tracos=['dedicação'])
add("Poisoner's Twist",'Torção do Envenenador',4,211,'Envenenador','Causa 1d6 do tipo do Golpe anterior e 1d6 de veneno ao alvo. No 18º nível, causa 2d6 de cada.','Explora o ferimento envenenado para causar dano adicional.',pre='Dedicação de Envenenador; treinado em Medicina',acoes=1,requisitos='última ação foi Golpe corpo a corpo que feriu alvo envenenado; conhecer o veneno')
add('Advanced Poisoncraft','Ofício de Venenos Avançado',6,211,'Envenenador','Aumenta para seis os venenos diários; no 10º nível, pode selecionar novamente para elevar a oito.','Aumenta sua produção diária de venenos.',pre='Dedicação de Envenenador')
add('Poison Coat','Revestimento Venenoso',6,211,'Envenenador','Gaste veneno de contato ou ferimento e 10 minutos para aplicá-lo à roupa; apenas um por vez. Recebe Uma Vez Mordido, reação quando criatura adjacente o acerta desarmada: ela é exposta e o veneno fica inerte.','Prepara roupa envenenada que contamina quem o ataca.',pre='Dedicação de Envenenador')
add('Acquired Tolerance','Tolerância Adquirida',8,211,'Envenenador','Repita a salvaguarda contra veneno e use o segundo resultado. Depois, pode usar novamente contra o mesmo tipo naquele dia, mas não contra outro até as preparações.','Repete salvaguarda e cria tolerância ao mesmo veneno.',pre='Dedicação de Envenenador',acoes='reação',tracos=['fortuna'],gatilho='falha em salvaguarda contra veneno')
add('Chemical Contagion','Contágio Químico',18,211,'Envenenador','Recebe a descoberta de campo maior do alquimista toxicologista da página 62, permitindo que venenos de ferimento espirrem sobre criaturas.','Faz venenos de ferimento contagiarem outras criaturas.',pre='Dedicação de Envenenador')

out=pathlib.Path(__file__).with_name('arquetipos-talentos-b-qa.json')
assert len({r['id'] for r in rows})==len(rows)
assert all(r['descricao'] and r['resumo'][0] and r['nomeOriginal'] for r in rows)
out.write_text(json.dumps({'talentos':rows,'total':len(rows),'paginasCobertas':[200,223],'ambiguidades':[r['id'] for r in rows if r['revisao']=='ocr-ambiguo']},ensure_ascii=False,indent=2)+'\n')
print(f'{len(rows)} talentos de arquétipos traduzidos e verificados.')
