#!/usr/bin/env python3
"""Compila o catálogo editorial manual; não traduz OCR automaticamente."""
import json, pathlib, re, tempfile, os
ROOT=pathlib.Path(__file__).resolve().parents[3]
F='player-core-2'
cat={'fonte':{'id':F,'nome':'Livro do Jogador 2 — Player Core 2','edicao':'remaster','idiomaOriginal':'en','paginas':322,'estado':'parcial','referenciaPaginas':'Índice físico global das partes 1 a 4 (100+100+100+22 páginas), não numeração impressa.','cobertura':'Oito classes com estatísticas iniciais e progressão de proficiências; oito ancestralidades e 54 heranças; seleção de talentos revisada. Tradução integral pendente.'},'classes':[],'ancestralidades':[],'biografias':[],'talentos':[],'magias':[],'equipamentos':[],'secoes':[],'lacunas':[]}
def classe(id,nome,pv,keys,skills,fixed,per,saves,armors,weapons,page,description,summary,spell=None):
 c=dict(id=id,nome=nome,pv=pv,atributoChave=keys,periciasTreinadas=skills,periciasFixas=fixed,percepcao=per,salvaguardas=dict(zip(['fortitude','reflexos','vontade'],saves)),armaduras=dict(zip(['sem','leve','media','pesada'],armors)),armas=dict(zip(['simples','marciais','avancadas','desarmado'],weapons)),cdClasse=1,pagina=page,fonte=F,descricao=description,resumo=summary,opcoes=[],progressao=[],paginasRevisadas=list(range(page,page+6)))
 if spell:c['conjuracao']=spell
 cat['classes'].append(c);return c
A=classe('alquimista','Alquimista',8,['int'],3,['manufatura'],1,[2,2,1],[1,1,1,0],[1,0,0,1],58,'Você prepara reagentes e fórmulas para criar bombas, elixires, mutagênicos e venenos. Alquimia não é conjuração.', ['Cria consumíveis nas preparações diárias e converte frascos versáteis em itens durante a aventura.','Inteligência determina a CD e vários recursos; campo de pesquisa modifica fórmulas e frascos.'])
A['armas']['bombasAlquimicas']=1
B=classe('barbaro','Bárbaro',12,['for'],3,['atletismo'],2,[2,1,2],[1,1,1,0],[1,1,0,1],72,'Você canaliza Fúria em ataques corpo a corpo. Instinto determina poderes, dano adicional e resistências.',['Fúria concede PV temporários e dano adicional, mas limita ações de concentração.','Fúria Remaster não impõe a antiga penalidade de CA. Armas ágeis reduzem seu dano adicional de Fúria.'])
C=classe('campeao','Campeão',10,['for','des'],2,['religiao'],1,[2,1,2],[1,1,1,1],[1,1,0,1],88,'Você protege uma causa divina e aliados com uma reação especial. Sua defesa em armaduras pode chegar a lendário.',['Escolhe divindade, santificação e causa; treina a perícia de sua divindade.','Aura de 15 pés define o alcance de efeitos protetores. Magias de devoção usam Carisma.'],{'tradicao':'divina','atributo':'car','grau':1,'tipo':'foco'})
I=classe('investigador','Investigador',8,['int'],4,['sociedade'],2,[1,2,2],[1,1,0,0],[1,1,0,1],102,'Você segue pistas, reúne evidências e antecipa ataques com Inteligência. Recebe aumentos de perícia a cada nível.',['Idealizar Estratagema antecipa um ataque ou beneficia um teste de perícia.','Investigações concedem bônus pertinentes à pergunta central; mestre decide quais testes se relacionam ao caso.'])
M=classe('monge','Monge',10,['for','des'],4,[],1,[2,2,2],[2,0,0,0],[1,0,0,1],116,'Você aperfeiçoa corpo e mente com ataques desarmados, posturas e possíveis magias de qi. Não escolhe subclasse obrigatória.',['Rajada de Golpes faz dois ataques desarmados com uma ação e aplica penalidade por ataques múltiplos normalmente.','Começa especialista nas três salvaguardas e na defesa sem armadura. Posturas e qi exigem talentos.'])
M['opcoesObrigatorias']=False
O=classe('oraculo','Oráculo',8,['car'],3,['religiao'],1,[1,1,2],[1,1,0,0],[1,0,0,1],130,'Você conjura magia divina espontânea de um mistério. Habilidades ligadas à maldição aumentam sua condição amaldiçoado; foco não a aumenta por si só.',['Mistério concede perícias, magias, revelação, talento e maldição próprios.','Refocar reduz a maldição em 1 e recupera foco. Não se pode contornar a maldição com itens ou magias.'],{'tradicao':'divina','atributo':'car','grau':1,'tipo':'espontanea'})
S=classe('feiticeiro','Feiticeiro',6,['car'],2,[],1,[1,1,2],[1,0,0,0],[1,0,0,1],146,'Sua linhagem desperta conjuração espontânea, magia sanguínea e uma magia de foco. A tradição depende da linhagem.',['Carisma governa ataques e CDs de magia. Linhagem treina duas perícias.','Potência Feiticeira aumenta dano ou cura inicial de magias de espaços pela graduação, uma vez por criatura por conjuração.'],{'tradicao':'linhagem','atributo':'car','grau':1,'tipo':'espontanea','truques':5,'espacos':[3],'magiasEscolhidas':2,'truquesEscolhidos':4,'magiasConcedidas':1,'truquesConcedidos':1,'niveisMagia':{str(n):min(9,(n+1)//2) for n in range(1,21)},'espacosPorNivel':{str(n):[4]*(min(9,(n+1)//2)-1)+([3] if n<19 and n%2 else [4])+([1] if n>=19 else []) for n in range(1,21)}})
W=classe('espadachim','Espadachim',10,['des'],4,['acrobacia'],2,[1,2,2],[1,1,0,0],[1,1,0,1],160,'Você ganha panache com ações ousadas e usa finalizações de precisão. Estilo determina perícia e formas adicionais de ganhar panache.',['Golpe Preciso aumenta dano de ataques ágeis/acuidade adequados, mesmo sem panache.','Finalizar exige e consome panache; depois não pode usar ações de ataque no restante do turno.'])
I['incrementosPericia']=list(range(2,21));I['niveisTalentos']={'pericia':list(range(2,21))}
W['incrementosPericia']=sorted(list(range(3,20,2))+[3,7,15]);W['niveisTalentos']={'pericia':sorted(list(range(2,21,2))+[3,7,15])};W['restricoesTalentosExtra']={str(n):['acrobacia','pericia-do-estilo'] for n in [3,7,15]}
def gain(c,n,name,text,page=None,prof=None,**extra):
 g=dict(nivel=n,nome=name,descricao=text,automatico=bool(prof),fonte=F,pagina=page or c['pagina']+1,**extra)
 if prof:g['proficiencias']=prof
 c['progressao'].append(g)
def arms(c,n,rank,martial=True,bombs=False):
 data={'simples':rank,'desarmado':rank}
 if martial:data['marciais']=rank
 if bombs:data['bombasAlquimicas']=rank
 gain(c,n,'Armas '+{2:'Especialista',3:'Mestre'}[rank],'Proficiência nas armas indicadas aumenta para '+{2:'especialista',3:'mestre'}[rank]+'.',prof={'armas':data})
def armor(c,n,rank,groups):gain(c,n,'Defesa '+{2:'Especialista',3:'Mestre',4:'Lendária'}[rank],'Proficiência em '+', '.join({'sem':'defesa sem armadura','leve':'armadura leve','media':'armadura média','pesada':'armadura pesada'}[k] for k in groups)+' aumenta para '+{2:'especialista',3:'mestre',4:'lendário'}[rank]+'.',prof={'armaduras':{k:rank for k in groups}})
def saves(c,n,key,rank,name,extra=''):gain(c,n,name,'Proficiência em '+{'fortitude':'Fortitude','reflexos':'Reflexos','vontade':'Vontade'}[key]+' passa a '+{2:'especialista',3:'mestre',4:'lendário'}[rank]+'. '+extra,prof={'salvaguardas':{key:rank}})
def perception(c,n,rank):gain(c,n,'Percepção '+{2:'Especialista',3:'Mestre',4:'Lendária'}[rank],'Percepção passa a '+{2:'especialista',3:'mestre',4:'lendário'}[rank]+'.',prof={'percepcao':rank})
def spec(c,n,greater=False):gain(c,n,'Especialização em Armas Maior' if greater else 'Especialização em Armas','Dano adicional com armas/ataques desarmados em que é especialista: 4; mestre: 6; lendário: 8.' if greater else 'Dano adicional com armas/ataques desarmados em que é especialista: 2; mestre: 3; lendário: 4.')
# Alquimista: leitura e recursos Remaster, sem recuperação automática de consumíveis.
gain(A,1,'Alquimia e Fórmulas','Recebe Manufatura Alquímica e livro de fórmulas gratuito. Além das fórmulas de talento/campo, aprende duas de itens alquímicos comuns de 1º nível. A cada nível aprende outras duas comuns de itens que possa criar. Identifica automaticamente itens cujas fórmulas conhece.',59)
gain(A,1,'Alquimia Avançada','Nas preparações, cria até 4 + Inteligência consumíveis alquímicos de seu nível ou menor e com fórmula conhecida. Ferramentas bastam: sem teste, matérias-primas ou dias de fabricação. Infundidos duram 24 horas ou até próxima preparação, o que ocorrer primeiro.',59)
gain(A,1,'Frascos Versáteis','Limite e quantidade inicial: 2 + Inteligência. Em exploração recupera 2 a cada 10 minutos, sem interromper outras atividades. São infundidos, não preserváveis nem duplicáveis. Como bombas: nível1 1d6 ácido+1 dispersão; nível4 2d6+2 e bônus item+1; nível12 3d6+3 e +2; nível18 4d6+4 e +3.',59)
gain(A,1,'Alquimia Rápida','Uma ação de manipulação, ferramentas vestidas/seguradas e mão livre. Criar Consumível gasta frasco para item de seu nível ou menor com fórmula, potente até início do próximo turno. Frasco Rápido cria frasco sem gasto de reserva, só como bomba/opção de campo e potente até fim do turno. Efeitos de duração maior que 10 minutos duram apenas 10 minutos.',60)
gain(A,5,'Alquimia Poderosa','Ao criar item alquímico infundido que exige salvaguarda, pode trocar sua CD pela CD de classe.',61)
gain(A,5,'Descoberta de Campo','Recebe descoberta de 5º nível do campo escolhido.',61);arms(A,7,2,False,True);saves(A,7,'vontade',2,'Vontade Especialista');gain(A,9,'Alquimia Especialista','CD de classe passa a especialista; em exploração recupera 3 frascos em vez de 2.',61,{'cdClasse':2});gain(A,9,'Preparo Duplo','Alquimia Rápida pode criar dois itens, não necessariamente iguais. Dois consumíveis gastam um frasco por consumível.',61);perception(A,9,2);gain(A,11,'Frascos Avançados','Recebe melhoria de 11º nível dos frascos de campo.',61);saves(A,11,'fortitude',3,'Resiliência Química','Sucessos tornam-se críticos.');gain(A,13,'Descoberta Maior','Recebe descoberta de 13º nível do campo.',61);armor(A,13,2,['sem','leve','media']);spec(A,13);arms(A,15,3,False,True);saves(A,15,'reflexos',3,'Esquivar de Explosões','Sucessos tornam-se críticos.');gain(A,17,'Frascos Abundantes','Permanentemente acelerado: ação extra só pode criar um único Frasco Rápido, mesmo com Preparo Duplo.',61);gain(A,17,'Alquimia Mestre','CD de classe passa a mestre.',61,{'cdClasse':3});armor(A,19,3,['sem','leve','media'])
# Bárbaro.
gain(B,1,'Fúria','Uma ação; exige não estar fatigado nem em fúria. PV temporários nível+Constituição, dano corpo a corpo+2 (metade se ágil). Não usa concentração salvo ações com fúria e Buscar. Dura 1 minuto, até inconsciência ou fim do encontro; não termina voluntariamente. Ao terminar perde PV temporários e só os recebe novamente com Fúria após 1 minuto.',73)
gain(B,1,'Temperamento Explosivo','Ação livre ao rolar iniciativa, se não estiver sobrecarregado nem de armadura pesada: entra em Fúria.',73);gain(B,3,'Passos Furiosos','+5 pés de estado no Deslocamento, +10 pés em Fúria.',74);arms(B,5,2);gain(B,5,'Brutalidade','Em Fúria recebe especialização crítica de armas corpo a corpo e ataques desarmados.',74);saves(B,7,'fortitude',3,'Colosso','Sucessos tornam-se críticos.');spec(B,7);gain(B,7,'Especialização do Instinto','Recebe aumento de dano de Fúria do instinto.',74);gain(B,9,'Resistência Furiosa','Em Fúria, resistência 3+Constituição aos tipos do instinto.',74);saves(B,9,'reflexos',2,'Reflexos Especialista');gain(B,11,'Fúria Poderosa','CD passa a especialista. Após Temperamento Explosivo, primeiro Golpe do primeiro turno causa dano adicional igual ao dano de Fúria.',74,{'cdClasse':2});saves(B,13,'fortitude',4,'Colosso Maior','Falha crítica vira falha; falha contra dano causa metade.');armor(B,13,2,['sem','leve','media']);arms(B,13,3);spec(B,15,True);gain(B,15,'Especialização Maior do Instinto','Recebe segundo aumento de dano do instinto.',74);saves(B,15,'vontade',3,'Vontade Indomável','Sucessos tornam-se críticos.');perception(B,17,3);gain(B,17,'Fúria Revitalizante','Basta um turno inteiro sem Fúria para receber PV temporários novamente, em vez de 1 minuto.',74);armor(B,19,3,['sem','leve','media']);gain(B,19,'Devastador','CD passa a mestre; Golpes corpo a corpo ignoram até 10 resistência ao dano físico que causam.',74,{'cdClasse':3})
# Campeão.
gain(C,1,'Divindade e Santificação','Escolhe divindade e santificação permitida/obrigatória; treina perícia divina ou outra se já treinado. Arma favorita simples ou ataque desarmado d4 aumenta dado um passo; acesso à favorita incomum e favorita avançada conta como marcial. Anátemas graves podem remover poderes, conforme mestre.',89)
gain(C,1,'Aura de Campeão','Emanação divina de 15 pés, alcance da reação de campeão. Seguidores reconhecem devoção. Suprimir/reativar exige uma ação de concentração; termina inconsciente.',90)
gain(C,1,'Devoção','Escolhe Escudos do Espírito ou magia compatível com fonte divina: Imposição das Mãos se permite curar, Toque do Vazio se permite ferir. Divinas de foco, Carisma; ganha 1 Ponto de Foco. Refocar por 10 minutos de oração/serviço. Graduação automática metade do nível arredondada para cima.',90)
gain(C,1,'Bloqueio com Escudo','Recebe talento geral Bloqueio com Escudo.',90);gain(C,3,'Bênção do Devoto','Escolha Armamento Abençoado (especialização crítica e runa da lista), Escudo Abençoado (runa reforçadora conforme nível) ou Rapidez Abençoada (+5 pés estado, para montaria se montado; aliado ganha +2 estado nas defesas contra reação acionada por mover dentro da aura). Detalhamento completo das runas ainda pendente.',90);arms(C,5,2);armor(C,7,2,['sem','leve','media','pesada']);gain(C,7,'Especialização em Armadura','Recebe efeitos de especialização de armaduras médias/pesadas.',91);spec(C,7);gain(C,9,'Campeão Especialista','CD de classe e ataques/CDs de magia passam a especialista.',91,{'cdClasse':2,'conjuracao':2});saves(C,9,'reflexos',2,'Reflexos Especialista');saves(C,9,'fortitude',3,'Corpo Sagrado','Sucessos tornam-se críticos.');gain(C,9,'Reação Implacável','Recebe melhoria de 9º nível da reação de sua causa.',91);saves(C,11,'vontade',3,'Vontade Divina','Sucessos tornam-se críticos.');gain(C,11,'Reação Exaltada','Recebe melhoria de 11º nível da reação de sua causa.',92);perception(C,11,2);armor(C,13,3,['sem','leve','media','pesada']);arms(C,13,3);spec(C,15,True);gain(C,17,'Campeão Mestre','CD de classe e ataques/CDs de magia passam a mestre.',92,{'cdClasse':3,'conjuracao':3});armor(C,17,4,['sem','leve','media','pesada']);gain(C,19,'Desafio do Herói','Recebe magia de devoção Desafio do Herói; corpo da magia ainda pendente.',92)
# Investigador.
gain(I,1,'Seguir uma Pista','Examina detalhe por 1 minuto; mestre confirma mistério maior. Se houver, não repete por 10 minutos e pode abrir investigação com pergunta central. Mantém duas; abandonar impede retomada até próxima preparação. Testes pertinentes recebem +1 circunstância, conforme mestre.',103)
gain(I,1,'Compartilhar Pista','Reação uma vez a cada 10 minutos quando outra criatura testa para ajudar investigação: bônus de circunstância igual a Seguir uma Pista.',104)
gain(I,1,'Idealizar Estratagema','Uma ação, uma vez por rodada; livre se alvo visível pode responder investigação ativa. Rola d20: Ataque obriga usar resultado no primeiro Golpe contra alvo antes do próximo turno e pode trocar Força/Destreza por Inteligência com arma/ataque corpo a corpo ágil/acuidade, arma à distância (se arma de arremesso corpo a corpo, precisa ágil/acuidade) ou porrete. Perícia impede Golpear alvo até próximo turno e dá +1 circunstância ao próximo teste mental/percepção ligado ao alvo; se bônus investigativo se aplicar, aumenta-o em 1.',104)
gain(I,1,'Golpe Estratégico','Golpe que usa Inteligência por Estratagema causa +1d6 precisão; +2d6 no nível5, +3d6 no9, +4d6 no13, +5d6 no17.',105);gain(I,3,'Recordação Aguçada','Proficiência em testes destreinados de Recordar Conhecimento passa a nível em vez de 0.',106);arms(I,5,2);perception(I,7,3);spec(I,7);saves(I,9,'fortitude',2,'Fortitude Especialista');gain(I,9,'Investigador Especialista','CD passa a especialista; Seguir uma Pista concede +2.',106,{'cdClasse':2});gain(I,11,'Improvisação Dedutiva','Pode tentar ações que exigem treinado mesmo destreinado, especialista se treinado e mestre se especialista. Não altera seu grau nem bônus.',106);saves(I,11,'vontade',3,'Vontade Obstinada','Sucessos tornam-se críticos.');perception(I,13,4);armor(I,13,2,['sem','leve']);arms(I,13,3);spec(I,15,True);saves(I,15,'reflexos',3,'Reflexos Perspicazes','Sucessos tornam-se críticos.');saves(I,17,'vontade',4,'Vontade Obstinada Maior','Sucessos tornam-se críticos; falha crítica vira falha; falha contra dano causa metade.');armor(I,19,3,['sem','leve']);gain(I,19,'Detetive Mestre','CD passa a mestre; ao entrar em local com pista de investigação ativa, mestre informa existência/tipo de uma pista; confirma quando achar qualquer pista.',107,{'cdClasse':3})
# Monge: escolhas persistidas, nunca uma salvaguarda inventada.
gain(M,1,'Rajada de Golpes','Uma ação com floreio: dois Golpes desarmados. Se ambos acertam mesma criatura, combina dano apenas para resistências/fraquezas. Aplica penalidade por ataques múltiplos normalmente. Um floreio por turno.',117);gain(M,1,'Punho Poderoso','Punho causa d6 em vez de d4. Não sofre −2 circunstância para ataque letal com punho ou outro ataque desarmado.',117);gain(M,3,'Movimento Incrível','Sem armadura, +10 pés estado no Deslocamento; aumenta +5 nos níveis7,11,15,19. Não soma a outro bônus de estado.',117);gain(M,3,'Golpes Místicos','Ataques desarmados contam como mágicos para resistência. Não fornece bônus de item nem dados extras.',117);arms(M,5,2,False);gain(M,5,'Especialização Crítica Desarmada','Ataques desarmados do grupo pugilato recebem especialização crítica.',118);perception(M,5,2)
for n,name in [(7,'Caminho para a Perfeição'),(11,'Segundo Caminho para a Perfeição'),(15,'Terceiro Caminho para a Perfeição')]:
 e={'id':f'salvaguarda{n}','campo':'salvaguardas','opcoes':['fortitude','reflexos','vontade'],'grau':4 if n==15 else 3}
 if n==15:e['grauAnterior']=3
 gain(M,n,name,'Escolha uma salvaguarda para mestre: sucesso vira crítico.' if n==7 else ('Escolha outra salvaguarda para mestre: sucesso vira crítico.' if n==11 else 'Escolha uma das duas anteriores para lendário. Falha crítica vira falha; falha contra dano causa metade.'),118 if n<15 else 119,escolhaProficiencia=e)
spec(M,7);gain(M,9,'Golpes de Metal','Ataques desarmados contam como ferro frio/prata.',118);gain(M,9,'Monge Especialista','CD passa a especialista; se possui qi, ataques/CDs de magia também.',118,{'cdClasse':2},proficienciasCondicionais={'conjuracao':2,'requer':'magias-qi'});armor(M,13,3,['sem']);arms(M,13,3,False);spec(M,15,True);gain(M,17,'Golpes de Adamante','Ataques desarmados contam como adamante.',119);gain(M,17,'Lenda Graciosa','Sem armadura lendário e CD mestre; se possui qi, ataques/CDs de magia mestre.',119,{'armaduras':{'sem':4},'cdClasse':3},proficienciasCondicionais={'conjuracao':3,'requer':'magias-qi'});gain(M,19,'Forma Aperfeiçoada','No primeiro Golpe do turno, pode tratar d20 abaixo de 10 como 10. Efeito de fortuna.',120)
# Oráculo.
gain(O,1,'Repertório Divino','Conjura espontaneamente com Carisma; repertório e espaços são separados. Truques/foco se elevam a metade do nível arredondada para cima. A tabela inicial concede três espaços de1ª graduação, mas a prosa diz dois; divergência da impressão registrada, sem correção silenciosa.',131);gain(O,1,'Maldição Oracular','Depois da habilidade ligada à maldição, ganha amaldiçoado1 ou aumenta valor em1. Limite inicial2; no limite não pode usar tais habilidades. Efeitos são cumulativos. Só Refocar reduz valor em1 e recupera1foco; efeitos não podem ser contornados por itens/magias.',133);gain(O,3,'Magias Assinatura','Escolhe uma por graduação disponível e pode elevar sem aprender versões separadas, inclusive usar versões inferiores se aprendeu elevada.',133);gain(O,7,'Conjurador Especialista','Ataques/CDs de magia passam a especialista.',134,{'conjuracao':2});saves(O,7,'vontade',3,'Determinação Misteriosa','Sucessos tornam-se críticos.');saves(O,9,'fortitude',2,'Fortitude Mágica');gain(O,11,'Acesso Divino','Escolhe divindade com domínio de seu mistério; adiciona até três magias concedidas por ela à lista e ao repertório quando puder conjurá-las.',134);gain(O,11,'Maldição Maior','Limite de amaldiçoado passa a3.',134);perception(O,11,2);arms(O,11,2,False);armor(O,13,2,['sem','leve']);saves(O,13,'reflexos',2,'Reflexos Premonitórios');spec(O,13);gain(O,15,'Conjurador Mestre','Ataques/CDs de magia passam a mestre.',135,{'conjuracao':3});gain(O,17,'Maldição Extrema','Limite passa a4.',135);saves(O,17,'vontade',4,'Determinação Misteriosa Maior','Sucessos tornam-se críticos; falha crítica vira falha; falha contra dano causa metade.');gain(O,19,'Conjurador Lendário','Ataques/CDs de magia passam a lendário.',135,{'conjuracao':4});gain(O,19,'Clareza Oracular','Aprende duas magias divinas comuns de10ª graduação e recebe um espaço especial para elas. Não cresce normalmente nem funciona com habilidades que dão espaços ou conjuram sem gastá-los.',135)
# Feiticeiro.
gain(S,1,'Repertório e Linhagem','Aprende quatro truques e duas magias de1ª graduação à escolha, mais um truque e uma magia de linhagem. Três espaços iniciais. A primeira nova magia de cada graduação é a da linhagem. A cada nível pode trocar uma magia não concedida pela linhagem por outra da mesma graduação. Linhagem concede duas perícias, uma magia de foco e1Ponto de Foco.',148);gain(S,1,'Potência Feiticeira','Magia de espaço que causa dano/restaura PV recebe bônus de estado igual à graduação na cura/dano inicial. Cada criatura recebe aumento uma vez por conjuração.',148);gain(S,1,'Magia Sanguínea','Após conjurar magia de foco da linhagem ou magia concedida pela linhagem usando espaço, escolhe um efeito conhecido de magia sanguínea. Normalmente apenas um. Outros efeitos exigem talentos.',150);gain(S,3,'Magias Assinatura','Escolhe uma por graduação; pode elevar livremente sem aprender versões separadas e usar versões menores de assinatura aprendida elevada.',149);saves(S,5,'fortitude',2,'Fortitude Mágica');gain(S,7,'Conjurador Especialista','Ataques/CDs de magia passam a especialista.',149,{'conjuracao':2});saves(S,9,'reflexos',2,'Reflexos Especialista');perception(S,11,2);arms(S,11,2,False);armor(S,13,2,['sem']);spec(S,13);gain(S,15,'Conjurador Mestre','Ataques/CDs de magia passam a mestre.',150,{'conjuracao':3});saves(S,17,'vontade',3,'Vontade Majestosa','Sucessos tornam-se críticos.');gain(S,19,'Conjurador Lendário','Ataques/CDs de magia passam a lendário.',150,{'conjuracao':4});gain(S,19,'Excelência da Linhagem','Aprende duas magias comuns de10ª graduação da tradição e recebe um espaço especial. Não cresce normalmente nem funciona com habilidades que dão espaços ou conjuram sem gastá-los.',150)
# Espadachim Remaster: dano preciso não exige panache.
gain(W,1,'Panache e Bravata','Atravessar e ações do estilo ganham bravata. Sucesso no teste concede panache; falha não crítica concede até fim do próximo turno, mesmo sem outro efeito por imunidade. Mestre pode permitir ações especialmente ousadas com teste significativo. Normalmente só em encontro; termina ao fim dele.',161);gain(W,1,'Golpe Preciso','Arma corpo a corpo/ataque desarmado ágil ou acuidade causa +2 precisão; finalização +2d6. Aumenta +1/+1d6 nos níveis5,9,13,17, até +6/+6d6.',161);gain(W,1,'Combatente Estiloso','Em encontro, +1 circunstância em bravata; com panache, +5 pés estado aos Deslocamentos.',161);gain(W,1,'Finalização Confiante','Uma ação, exige e consome panache. Golpe adequado para Golpe Preciso. Falha não crítica causa metade do dano de Golpe Preciso, do mesmo tipo da arma. Depois não usa ações de ataque no restante do turno.',162);saves(W,3,'fortitude',2,'Fortitude Especialista');gain(W,3,'Ripostar Oportuno','Reação quando inimigo ao alcance falha criticamente em Golpe contra você: Golpe corpo a corpo ou Desarmar sua arma. Tem bravata.',162)
for n in [3,7,15]:gain(W,n,'Truques Estilosos','Aumento de perícia extra e talento de perícia extra; ambos em Acrobacia ou perícia do estilo.',162)
gain(W,3,'Velocidade Vivaz','Bônus com panache passa a+10 pés estado, +5 nos níveis7,11,15,19. Sem panache recebe metade arredondada para baixo ao múltiplo de5 pés. Não soma bônus de estado.',162);arms(W,5,2);gain(W,5,'Especialização Crítica','Armas em que é especialista recebem especialização crítica.',162);saves(W,7,'reflexos',3,'Evasão Confiante','Sucessos tornam-se críticos.');spec(W,7);gain(W,9,'Finalização Exemplar','Dançarino: Passo livre; Fanfarrão: remove imunidade ao seu Desmoralizar; Esgrimista: desprevenido até próximo turno; Ginasta: dano circunstancial 2×dados da arma se alvo agarrado/restringido/prostrado; Malandro: −10 pés circunstância até próximo turno; Sagaz: −2 circunstância em ataques contra você até próximo turno.',163);gain(W,9,'Espadachim Especialista','CD passa a especialista e bônus de Combatente Estiloso a+2.',163,{'cdClasse':2});gain(W,11,'Estilo Contínuo','Bônus de Combatente Estiloso também em exploração.',163);perception(W,11,3);saves(W,13,'reflexos',4,'Evasão Assegurada','Falha crítica vira falha; falha contra dano causa metade.');armor(W,13,2,['sem','leve']);arms(W,13,3);spec(W,15,True);gain(W,15,'Estilo Aguçado','Em Golpe com arma/ataque em que é mestre,19 natural que seria sucesso vira crítico.',163);saves(W,17,'vontade',3,'Ego Reforçado','Sucessos tornam-se críticos.');gain(W,19,'Confiança Eterna','CD passa a mestre. Finalização/Ripostar pode receber efeito de falha de Finalização Confiante, inclusive Finalização Precisa se possuir, apenas com arma/ataque adequado.',163,{'cdClasse':3});armor(W,19,3,['sem','leve'])
# Escolhas gerais nunca são aplicadas silenciosamente.
for c in cat['classes']:
 for n in [5,10,15,20]:gain(c,n,'Quatro Incrementos de Atributo','Escolha quatro atributos diferentes; em +4 ou maior, dois incrementos em níveis distintos são necessários para +1.')
 for n in [1,5,9,13,17]:gain(c,n,'Talento de Ancestralidade','Escolha talento de ancestralidade com requisitos cumpridos.')
 for n in [3,7,11,15,19]:gain(c,n,'Talento Geral','Escolha talento geral com requisitos cumpridos.')
 for n in range(2,21,2):gain(c,n,'Talento de Perícia','Escolha talento de perícia; precisa treino na perícia exigida.')
 for n in range(2 if c is I else 3,21,1 if c is I else 2):gain(c,n,'Aumento de Perícia','Aumenta perícia um grau. Mestre exige nível7; lendário exige nível15.')
 if c is I:
  for n in range(3,20,2):gain(c,n,'Lição Habilidosa','Talento extra de perícia baseada em Inteligência, Sabedoria ou Carisma, ou perícia da metodologia.')
 for n in ([] if c in [O,S] else [1])+list(range(2,21,2)):gain(c,n,'Talento de Classe','Escolha talento da classe com requisitos cumpridos.')
 if c in [O,S]:
  for n in range(3,18,2):gain(c,n,f'Magias de {(n+1)//2}ª Graduação','Recebe nova graduação; selecione repertório conforme regras/tabela da classe.')
 c['progressao'].sort(key=lambda g:(g['nivel'],g['nome']))
# As demais entradas manuais são compiladas do arquivo editorial independente.
EDITORIAL=json.loads((pathlib.Path(__file__).parent/'editorial.json').read_text())
for c in cat['classes']:c['opcoes']=EDITORIAL['opcoes'].get(c['id'],[])
cat['ancestralidades']=EDITORIAL['ancestralidades'];cat['talentos']=EDITORIAL['talentos']
cat['lacunas']=EDITORIAL['lacunas']
from automacao import aplicar
aplicar(cat)
from talentos_evolucao import aplicar as aplicar_talentos_evolucao
aplicar_talentos_evolucao(cat)
from talentos_intermediarios import aplicar as aplicar_talentos_intermediarios
aplicar_talentos_intermediarios(cat)
focos=json.loads((ROOT/'docs/pathfinder/player-core-1/focos-pc2-fixtures.json').read_text())
for m in focos['magias']:
 m['paginaImpressa']=m['pagina'];m['pagina']=m['paginaPdf'];m['secoes']=['magia-'+m['id']]
 cat['magias'].append(m)
cat['lacunas'].extend(focos.get('lacunas',[]))
for overlay in ['focos-linhagens-qa.json','focos-oraculo-qa.json','focos-qi-qa.json']:
 dados=json.loads((pathlib.Path(__file__).parent/overlay).read_text())
 for m in dados['magias']:
  assert m['pagina']==m['paginaPdf'], 'A referência do catálogo deve ser a página física do PDF.'
  m['secoes']=['magia-'+m['id']]
  cat['magias'].append(m)
 cat['lacunas'].extend(dados.get('lacunas',[]))
cat['secoes']=[dict(id='classe-'+x['id'],nome=x['nome'],pagina=x['pagina'],texto=x['descricao']+'\n\n'+'\n\n'.join(f"Nível {g['nivel']} — {g['nome']}\n{g['descricao']}" for g in x['progressao']),resumo=x['resumo']) for x in cat['classes']]
cat['secoes'] += [dict(id='ancestralidade-'+x['id'],nome=x['nome'],pagina=x['pagina'],texto=x['descricao']+'\n\n'+'\n\n'.join(f"{h['nome']}\n{h['descricao']}" for h in x['herancas']),resumo=x['resumo']) for x in cat['ancestralidades']]
for c in cat['classes']:
 for o in c['opcoes']:cat['secoes'].append(dict(id=c['id']+'-'+o['id'],nome=c['nome']+' — '+o['nome'],pagina=o['pagina'],texto=o['descricao'],resumo=o['resumo']))
cat['secoes'] += [dict(id='talento-'+t['id'],nome=t['nome'],pagina=t['pagina'],texto=t['descricao'],resumo=t['resumo']) for t in cat['talentos']]
cat['secoes'] += [dict(id='magia-'+m['id'],nome=m['nome'],pagina=m['pagina'],texto=m['descricao'],resumo=m['resumo']) for m in cat['magias']]
for name in ['classes','ancestralidades','talentos','magias','secoes']:
 ids=[x['id'] for x in cat[name]];assert len(ids)==len(set(ids));assert all(re.fullmatch('[a-z0-9-]+',s) for s in ids)
path=ROOT/'public/pathfinder/player-core-2.json';path.parent.mkdir(parents=True,exist_ok=True)
with tempfile.NamedTemporaryFile(mode='w',dir=path.parent,prefix='.player-core-2-',suffix='.tmp',encoding='utf-8',delete=False) as tmp:
 tmp.write(json.dumps(cat,ensure_ascii=False,indent=2)+'\n');pending=tmp.name
os.replace(pending,path)
print({k:len(cat[k]) for k in ['classes','ancestralidades','talentos','magias','secoes']})
