#!/usr/bin/env python3
"""Conteúdo editorial traduzido manualmente das páginas indicadas; coverage parcial."""
import json,pathlib
F='player-core-2'
e={'opcoes':{},'ancestralidades':[],'talentos':[],'lacunas':[]}
def opt(cl,id,name,page,text,skills=[],**extra):
 o=dict(id=id,nome=name,pagina=page,fonte=F,descricao=text,resumo=[text],periciasFixas=skills,**extra);e['opcoes'].setdefault(cl,[]).append(o);return o
opt('alquimista','bombardeiro','Bombardeiro',61,'Aprende duas fórmulas de bombas comuns de1º nível. Ao lançar bomba com dispersão, pode limitar dispersão ao alvo primário. Frascos podem causar frio, eletricidade ou fogo em vez de ácido.')
opt('alquimista','cirurgiao','Cirurgião',62,'Aprende duas fórmulas de elixires comuns de1º nível com cura. Pode usar grau de Manufatura em requisitos de Medicina e modificador de Manufatura nos testes de Medicina. Frasco pode curar criatura viva pelo seu dano inicial: beber ou lançar em alvo voluntário até20pés com Interagir. Ganha coagulante: imunidade temporária à cura por coagulantes por10minutos.')
opt('alquimista','mutagenista','Mutagenista',62,'Aprende duas fórmulas de mutagênicos comuns de1º nível. Ao usar um, recebe PV temporários Inteligência (mínimo0)+metade do nível, por1minuto ou duração do mutagênico, o que acabar primeiro; só recebe novamente após1minuto. Beber frasco suprime uma desvantagem de um mutagênico até início do próximo turno.')
opt('alquimista','toxicologista','Toxicologista',63,'Aprende duas fórmulas de venenos comuns de1º nível. Aplica veneno de ferimento segurado a arma/munição empunhada com uma ação em vez de duas. Venenos infundidos causam ácido contra imunidade a veneno ou se isso for mais prejudicial, conforme mestre. Frascos causam veneno e podem ser aplicados como veneno de ferimento; tornam-se inertes ao fim do turno.')
opt('barbaro','animal','Instinto Animal',75,'Em Fúria recebe ataques desarmados do animal escolhido e não pode usar armas. Fúria ganha morfo/primal. Dados e traços dependem do animal. Especialização aumenta dado um passo e dano de Fúria a5 no nível7,12 com Especialização Maior; resiste a perfurante/cortante. Escolha de animal e ataques ainda exige registro manual.')
opt('barbaro','dragao','Instinto de Dragão',75,'Escolhe dragão. Em Fúria pode elevar dano adicional de2para4 e mudá-lo para o tipo do sopro; ganha tradição e traço de dano pertinente. Especialização aumenta a8 no nível7,16 com Especialização Maior. Resiste a perfurante e tipo do sopro. Tipos são os dragões Remaster; escolha exige registro.')
opt('barbaro','furia','Instinto de Fúria',76,'Dano de Fúria passa de2para3; recebe talento extra de bárbaro de1º nível. Especialização aumenta a7 no nível7,13 com Especialização Maior. Resiste a dano físico de armas, não a ataques desarmados/outras fontes.')
opt('barbaro','gigante','Instinto de Gigante',76,'Pequeno/Médio pode usar arma para Grande; outro tamanho pode usar arma uma categoria acima. Recebe uma arma comum ou acessível de preço até9po sem ajuste de tamanho, grátis e sem revenda antes de runas. Com arma maior, Fúria causa+6 e fica desajeitado1 sem poder ignorar/remover; especialização10 no nível7 e18 com Maior. Resiste a contundente e frio, eletricidade ou fogo à escolha.')
opt('barbaro','espirito','Instinto de Espírito',77,'Em Fúria pode aumentar dano a3 e torná-lo espiritual; só nessa escolha armas/ataques ganham toque fantasma e Fúria ganha divino/espírito. Especialização7 no nível7,13 com Maior. Resiste a vazio e dano de ataques/habilidades de mortos-vivos, qualquer tipo.')
opt('barbaro','supersticao','Instinto de Superstição',77,'É anátema aprender/Conjurar Magia ou usar item ativável para Conjurar Magia; violar remove habilidades/talentos do instinto até1dia de recesso recentrando-se. Em Fúria +2 estado em salvaguardas contra magia e dano de Fúria3, ou4 contra criatura vista conjurando na última hora. Ao entrar, cura PV iguais aos temporários recebidos uma vez a cada10minutos. Aceitar magia/efeito enquanto em Fúria impõe assustado1 que não reduz enquanto afetado. Receber magia não é o antigo anátema. Resistência cobre duas tradições associadas escolhidas conforme livro; detalhamento pendente.')
opt('campeao','profanacao','Profanação',92,'Causa profana e incomum. Escudo Egoísta: reação quando inimigo na aura o fere; resistência ao dano acionador2+metade do nível. Golpes contra agressor causam+1 espiritual até fim do próximo turno (+2 no9,+3 no16). No nível9, se Carisma≥3, resistência é Carisma+metade do nível. No nível11, inimigos na aura recebem−1 estado em ataques contra você até início do próximo turno.',santificacao='profana')
opt('campeao','grandeza','Grandeza',92,'Exige sagrado. Clarão de Grandeza: reação quando inimigo causa dano a aliado, ambos na aura; resistência ao aliado2+nível contra dano acionador e Luz Reveladora no inimigo por1rodada. No nível9 causa espiritual persistente igual a Carisma, irrecuperável enquanto sob sua luz. No nível11, outros inimigos na aura também recebem Luz Reveladora.',santificacao='sagrada')
opt('campeao','iniquidade','Iniquidade',93,'Causa profana e incomum. Vingança Destrutiva: ao inimigo na aura feri-lo, reação aumenta seu dano recebido1d6 e causa1d6 espiritual nele; dados aumentam2d6 no5,3d6 no9,4d6 no12,5d6 no16,6d6 no19. Golpes contra ele+2 espiritual até fim do próximo turno (+4 no9,+6 no16). No nível9 dano inicial também dá espiritual persistente igual a Carisma. No11, demais inimigos na aura sofrem metade do dano da reação.',santificacao='profana')
opt('campeao','justica','Justiça',93,'Golpe Retributivo: reação quando inimigo causa dano a aliado, ambos na aura. Aliado recebe resistência2+nível ao dano acionador; se inimigo ao alcance, Golpe corpo a corpo nele. No nível9, acerto causa espiritual persistente igual a Carisma. No11, aliados na aura com alvo ao alcance podem gastar reação para Golpe com−5. Segue lei/autoridade legítima; explorar outros/trapacear é anátema.')
opt('campeao','libertacao','Libertação',93,'Passo Libertador: reação quando inimigo fere, agarra ou restringe aliado, ambos na aura. Se acionado por dano, resistência2+nível. Aliado pode repetir salvaguarda permitida contra restrição, imobilização/paralisia ou Escapar livre; depois Passo livre se puder mover. No9, quem impunha restrição sofre espiritual persistente igual a Carisma. No11, você e demais aliados na aura também podem dar Passo. Opõe-se à tirania; forçar escolhas dos outros é anátema.')
opt('campeao','obediencia','Obediência',94,'Comando de Ferro: reação divina/emocional/mental quando inimigo na aura o fere. Ele escolhe prostrar-se livremente ou sofrer1d6 mental (2d6 no5,3d6 no9,4d6 no12,5d6 no16,6d6 no19). Golpes contra ele+1 espiritual até fim do próximo turno (+2 no9,+3 no16). No9 recusa também dá espiritual persistente igual a Carisma. No11 outros inimigos escolhem prostrar-se ou dano mínimo dos dados, sem melhorias. Defende hierarquias legítimas; aceitar poder de inferior é anátema.')
opt('campeao','redencao','Redenção',94,'Exige sagrado. Vislumbre de Redenção: reação quando inimigo fere aliado, ambos na aura; escolhe Arrepender-se (aliado sem dano acionador) ou Recusar (resistência2+nível, agressor enfraquecido2 até fim do próximo turno dele). Sem mente/incapaz de arrepender usa Recusar. No9 recusa causa espiritual persistente igual a Carisma. No11 pode estender resistência a todos aliados/você na aura, reduzindo-a em2. Matar sapiente sem oferecer redenção é anátema.',santificacao='sagrada')
opt('investigador','ciencias-alquimicas','Ciências Alquímicas',104,'Treina Manufatura; recebe Manufatura Alquímica, livro de fórmulas e duas fórmulas comuns de1º nível de elixir/ferramenta, além das do talento. Aprende uma nova fórmula por nível. Prepara frascos iguais a Inteligência. Tintura Rápida: uma ação, um frasco, mão livre e ferramentas; cria elixir/ferramenta de seu nível ou menor potente até fim do turno.', ['manufatura'])
opt('investigador','empirismo','Empirismo',105,'Treina perícia de Inteligência à escolha e recebe Isso É Estranho. Inspeção Expedita: ação livre uma vez por10minutos para Recordar Conhecimento, Buscar ou Sentir Motivação.',periciasEscolha=['arcanismo','ocultismo','sociedade','manufatura'])
opt('investigador','medicina-forense','Medicina Forense',105,'Treina Medicina e recebe Acuidade Forense e Medicina de Batalha. Em sucesso com Medicina de Batalha cura PV extras iguais ao nível e imunidade temporária dura1hora, não1dia.',['medicina'])
opt('investigador','interrogacao','Interrogação',105,'Treina Diplomacia e recebe Sem Motivo para Alarme. Pode Seguir uma Pista enquanto Causa Impressão com pergunta pertinente. Pergunta Incisiva: uma ação, Diplomacia contra Vontade; sucesso exige resposta não necessariamente verdadeira, +2 na CD de Percepção contra mentiras e alvo desprevenido contra Estratagema até fim do turno. Crítico dá+4; falha permite recusa; crítica também piora atitude um passo. Imunidade1hora.',['diplomacia'])
for id,name,page,skill,feat,text in [
 ('ancestrais','Ancestrais',136,'sociedade','sussurros-fraqueza','Revelação Toque Ancestral. Magias: Orientação (truque), Mau Agouro1, Mensageiro Fantasmagórico2, Potencial Onírico5. Amaldiçoado impõe desajeitado de valor igual.'),
 ('batalha','Batalha',136,'atletismo','aviso','Revelação Transe da Arma. Magias: Escudo (truque), Golpe Certeiro1, Manobra Telecinética2, Tempestade de Armas4. Amaldiçoado1 dá fraqueza2 a dano de magias e suprime resistência/imunidade;2 dá−1 estado nas salvaguardas contra magias;3 fraqueza igual ao nível;4 penalidade−2.'),
 ('ossos','Ossos',136,'medicina','inclinar-balanca','Revelação Sifão da Alma. Magias: Distorção do Vazio (truque), Tentáculos Sombrios1, Vitalidade Falsa2, Arma Fantasmagórica3. Amaldiçoado1 fraqueza2 a vitalidade/vazio, podendo ferir e suprimindo resistência/imunidade;2 −1 estado em Fortitude;3 fraqueza5+nível;4 penalidade−2.'),
 ('cosmos','Cosmos',137,'natureza','aviso','Revelação Chuva de Estrelas. Magias: Luz (truque), Cores Atordoantes1, Escuridão2, Frenesi Lunar5. Amaldiçoado impõe enfraquecido de valor igual e penalidade de estado do mesmo valor nas salvaguardas/CDs contra movimento forçado.'),
 ('chamas','Chamas',137,'acrobacia','prever-dano','Revelação Aura Incendiária. Magias: Ignição (truque), Soprar Fogo1, Raio Flamejante2, Bola de Fogo3. Amaldiçoado causa fogo persistente igual ao valor e luz de tocha; submerso mantém calor sem chamas. Cessa ao começar Refocar ou inconsciente; retorna se interromper Refocar ou acordar.'),
 ('vida','Vida',138,'medicina','inclinar-balanca','Revelação Vínculo Vital. Magias: Chicote de Vitalidade (truque), Acalmar1, Vitalidade Falsa2, Crescimentos Macabros5. Cura mágica recebida sofre penalidade de estado igual ao nível (mínimo1)×valor de amaldiçoado.'),
 ('conhecimento','Conhecimento',138,'ocultismo','sussurros-fraqueza','Também treina um Saber à escolha. Revelação Drenar Mente. Magias: Ler Aura (truque), Vínculo Mental1, Hipercognição3, Mente Vazia6. Percepção/Vontade sofrem penalidade de estado igual a amaldiçoado; no4 não fala, não usa efeitos linguísticos nem comunica com aliados e fica estupefato1.'),
 ('tempestade','Tempestade',138,'natureza','prever-dano','Revelação Toque da Tempestade. Magias: Arco Elétrico (truque), Golpe Trovejante1, Torrente Hidráulica4, Relâmpago em Cadeia6. Amaldiçoado1 fraqueza2 eletricidade, suprime resistência/imunidade elétrica e conta como metal;2 −2 circunstância em ataques à distância;3 fraqueza5+nível;4 −10 pés estado nos Deslocamentos.')]:
 names={'sussurros-fraqueza':'Sussurros de Fraqueza','aviso':'Aviso Oracular','inclinar-balanca':'Inclinar a Balança','prever-dano':'Prever Dano'}
 opt('oraculo',id,name,page,'Treina '+{'sociedade':'Sociedade','atletismo':'Atletismo','medicina':'Medicina','natureza':'Natureza','acrobacia':'Acrobacia','ocultismo':'Ocultismo'}[skill]+' e recebe '+names[feat]+'. '+text,[skill],talentosConcedidos=['oraculo-'+feat],**({'periciaSaberEscolha':True} if id=='conhecimento' else {}))
for id,name,trad,skills,page in [('aberrante','Aberrante','ocultista',['ocultismo','intimidacao'],151),('angelical','Angelical','divina',['religiao','diplomacia'],151),('demoniaca','Demoníaca','divina',['religiao','intimidacao'],151),('diabolica','Diabólica','divina',['religiao','enganacao'],151),('elemental','Elemental','primal',['natureza','intimidacao'],152),('feerica','Feérica','primal',['natureza','enganacao'],152),('bruxa','Bruxa','ocultista',['ocultismo','enganacao'],153),('imperial','Imperial','arcana',['arcanismo','sociedade'],153),('morta-viva','Morta-viva','divina',['religiao','intimidacao'],153)]:
 opt('feiticeiro',id,name,page,'Tradição '+trad+'. Treina '+', '.join(skills)+'. Linhagem concede magias, foco inicial e magia sanguínea próprios; corpos/listas completos ainda pendentes.',skills,tradicao=trad,conjuracao={'tradicao':trad,'atributo':'car','grau':1})
for id,name,trad,skill in [('adamante','Adamante','primal','natureza'),('conspirador','Conspirador','ocultista','ocultismo'),('diabolico','Diabólico','divina','religiao'),('empireo','Empíreo','divina','religiao'),('fortuna','Fortuna','arcana','arcanismo'),('cornudo','Cornudo','primal','natureza'),('miragem','Miragem','arcana','arcanismo'),('pressagio','Presságio','ocultista','ocultismo')]:
 opt('feiticeiro','draconica-'+id,'Dracônica — '+name,152,'Tradição '+trad+'. Treina Intimidação e '+skill+'. Recebe Dons do Dragão como foco inicial. Magia sanguínea concede +1 estado na CA por1rodada após magia concedida/foco. Lista completa de magias ainda pendente.', ['intimidacao',skill],tradicao=trad,conjuracao={'tradicao':trad,'atributo':'car','grau':1})
for id,name,skill,text in [('dancarino','Dançarino de Batalha','performance','Recebe Performance Fascinante; Atuar ganha bravata.'),('fanfarrao','Fanfarrão','intimidacao','Desmoralizar ganha bravata.'),('esgrimista','Esgrimista','enganacao','Criar Distração e Fintar ganham bravata.'),('ginasta','Ginasta','atletismo','Agarrar, Reposicionar, Empurrar e Derrubar ganham bravata.'),('malandro','Malandro','ladroagem','Recebe Truque Sujo; Truque Sujo ganha bravata.'),('sagaz','Sagaz','diplomacia','Recebe Bon Mot; Bon Mot ganha bravata.')]:opt('espadachim',id,name,162,'Treina '+skill+'. '+text,[skill])
# Ancestralidades e heranças.
def anc(id,name,hp,size,boost,flaw,page,text,her):
 a=dict(id=id,nome=name,pv=hp,deslocamento=25,tamanho=size,incrementos=boost,livres=1,descricao=text,resumo=[text],fonte=F,pagina=page,raridade='incomum',herancas=[])
 if flaw:a['defeito']=flaw
 for h in her:
  hid,hn,ht,*more=h;a['herancas'].append(dict(id=id+'-'+hid,nome=hn,descricao=ht,resumo=[ht],fonte=F,pagina=page,**(more[0] if more else {})))
 e['ancestralidades'].append(a)
anc('povo-gato','Povo-gato',8,'medio',['des','car'],'sab',10,'Visão na penumbra; ao cair sofre metade do dano normal e não fica prostrado.',[
 ('garras','Garras','Garra desarmada1d6 cortante, pugilato, ágil/acuidade.'),('cacador','Caçador','Faro impreciso30pés; +2 circunstância para Rastrear cheiro conhecido. Vento pode dobrar ou reduzir alcance à metade.'),('selva','Selva','Ignora terreno difícil de vegetação; vegetação difícil maior vira apenas difícil.'),('liminar','Liminar','Detectar Magia inato ocultista à vontade, elevado a metade do nível arredondada para cima; +1 circunstância em Ocultismo para Recordar Conhecimento sobre criaturas de planos além do Universo.'),('nove-vidas','Nove Vidas','Recebe Duro de Matar; não soma morrendo à CD de recuperação, normalmente10.'),('ouvidos-agucados','Ouvidos Aguçados','+2 circunstância para Buscar criatura não detectada audível até30pés; se a percebe por som, uma vez/rodada pode Apontar para todos aliados como ação livre.'),('inverno','Inverno','Resistência a frio metade do nível, mínimo1; frio ambiental uma categoria menos extremo.')])
anc('hobgoblin','Hobgoblin',8,'medio',['con','int'],'sab',14,'Visão no escuro; herança reflete adaptações de sua linhagem.',[
 ('antielfo','Antielfo','Reação antes de salvaguarda contra efeito mágico: +1 circunstância, +2 se arcano.'),('chefe-goblin','Chefe Goblin','Coerção em Grupo; sucesso ao Coagir goblin vira crítico, falha crítica vira falha.'),('pernas-curtas','Pernas Curtas','Cavalgar; não fica desprevenido ao Escalar.'),('fumaceiro','Fumaceiro','Resistência a fogo metade do nível mínimo1; sucesso automático no teste simples CD5 contra criatura ocultada só por fumaça.'),('marcha','Marcha de Guerra','Falha não crítica para Subsistir no ermo ainda fornece refeições ruins; pode Apressar-se por dobro do tempo.'),('toca','Criado na Toca','No subterrâneo reduz teste simples contra ocultado a CD3 e escondido a CD9; sucesso em Espremer-se vira crítico.')])
anc('kholo','Kholo',8,'medio',['for','int'],'sab',18,'Visão na penumbra e mordida desarmada1d6 perfurante, pugilato.',[
 ('formiga','Formiga','Tamanho Pequeno; treina Enganação ou outra se já treinado. +1 circunstância em Mentir alegando inocência, CD de Enganação contra Sentir Motivação nessas mentiras e iniciativa por Enganação.',{'tamanho':'pequeno','periciasFixas':['enganacao']}),('caverna','Caverna','Visão no escuro.'),('cachorro','Cachorro','Com duas mãos livres, corre de quatro com Deslocamento30pés.'),('grande','Grande','PV de ancestralidade10; +1 circunstância em Atletismo para Reposicionar, Empurrar ou Derrubar.',{'pv':10}),('halito-doce','Hálito Doce','Treina Diplomacia ou outra se já treinado; +1 circunstância em Causar Impressão se alvo cheira seu hálito.',{'periciasFixas':['diplomacia']}),('inverno','Inverno','Resistência a frio metade do nível mínimo1; frio ambiental uma categoria menos extremo.'),('feiticeiro','Feiticeiro','Quimera inato ocultista à vontade, elevado a metade do nível arredondada para cima; +1 circunstância para Criar Distração/Personificar só com voz.')])
anc('kobold','Kobold',6,'pequeno',['des','car'],'con',22,'Visão no escuro; benfeitor influenciou adaptações.',[
 ('caverna','Espreitador da Caverna','Ao Escalar pedra natural move metade do Deslocamento em sucesso e todo em crítico; com Escalada Rápida move todo em sucesso. Não afeta Deslocamento de escalada. Sucesso em Espremer-se vira crítico.'),('escamas-draconicas','Escamas Dracônicas','PV de ancestralidade10; +1 circunstância contra sopro de dragão, sono e paralisia.',{'pv':10}),('coracao-elemental','Coração Elemental','Escolhe benfeitor e resistência metade do nível mínimo1: ar/frio, terra/eletricidade, fogo/fogo, metal/sônico, água/ácido, madeira/veneno.'),('chifre-magico','Chifre Mágico','Escolhe truque arcano comum inato à vontade, elevado a metade do nível arredondada para cima; treinado em ataques/CD de magia, Carisma.'),('mandibula-forte','Mandíbula Forte','Mandíbula desarmada1d6 perfurante, pugilato/acuidade.'),('tuneis-alagados','Túneis Alagados','Deslocamento de natação15pés.',{'deslocamentoNatacao':15}),('cauda-venenosa','Cauda Venenosa','Toxina da Cauda: ação manipular uma vez/dia, exige arma perfurante/cortante empunhada. Próximo Golpe com ela até fim do próximo turno que acerta e causa dano aplica veneno persistente igual ao nível.')])
anc('povo-lagarto','Povo-lagarto',8,'medio',['for','sab'],'int',26,'Garra desarmada1d4 cortante, pugilato/ágil/acuidade; recebe Controle da Respiração.',[
 ('escalador','Escamas de Penhasco','Escalador de Combate; sem calçados pode Escalar com pés e mãos livres; sucesso em Escalar vira crítico.'),('saltador-nuvens','Saltador das Nuvens','Se pode agir e tem espaço suficiente segundo mestre, abre membranas para evitar dano de queda.'),('franja','Franja','Desmoralizar torna-se visual, sem penalidade por idioma. Aproximação Ameaçadora: uma ação para Andar adjacente e Desmoralizar; sucesso impõe assustado2 em vez de1.'),('areia','Andarilho das Areias','Resistência fogo metade do nível mínimo1; calor uma categoria menos extremo; aguenta dez vezes mais sem comida/água. Sem abrigo/proteção, frio uma categoria mais extremo.'),('camuflado','Camuflado','Mudar cor pequena exige uma ação, grande1hora. Com coloração similar ao ambiente, ação ajusta padrão e dá +2 circunstância Furtividade até mudar ambiente/padrão.'),('pantano','Habitante do Pântano','Deslocamento de natação15pés.',{'deslocamentoNatacao':15}),('mata','Espreitador da Mata','Pode Obter Cobertura na floresta/selva sem obstáculo normal; recebe Espreitador de Terreno para vegetação mesmo sem Furtividade treinada.')])
anc('povo-rato','Povo-rato',6,'pequeno',['des','int'],'for',30,'Visão na penumbra e mandíbula desarmada1d4 perfurante, pugilato/ágil/acuidade.',[
 ('profundezas','Profundezas','Visão no escuro.'),('deserto','Deserto','Mãos livres: corre de quatro com30pés. Calor menos extremo; dez vezes mais sem comida/água. Sem proteção, frio mais extremo.'),('focinho-longo','Focinho Longo','Faro impreciso30pés, vento pode dobrar/reduzir; +2 circunstância em Buscar no alcance do faro.'),('esgoto','Esgoto','Imune à praga pútrida; +1 circunstância contra doenças/venenos. Sucesso vira crítico; se outra habilidade já melhora, falha crítica vira falha.'),('sombra','Sombra','Treina Intimidação ou outra se já treinado; Coage animais e Desmoraliza sem penalidade por idioma. Atitude de animais começa uma categoria pior.',{'periciasFixas':['intimidacao']}),('neve','Neve','Resistência frio metade do nível mínimo1; frio ambiental menos extremo.'),('tunel','Túnel','Espremer-se Rápido mesmo sem treino em Acrobacia; espaços estreitos que não exigem Espremer-se não são terreno difícil.')])
anc('tengu','Tengu',6,'medio',['des'],None,34,'Visão na penumbra; bico desarmado1d6 perfurante, pugilato/acuidade.',[
 ('dentes','Dentes de Cão','Bico ganha mortal d8, acrescentando dado no crítico. Não recebe fatal nem muda seu dado básico.'),('azarado','Azarado','Sucesso contra maldição/infortúnio vira crítico. Ao ganhar condenado, teste simples CD17 pode reduzir valor recebido1.'),('guardiao-montanha','Guardião da Montanha','Chicote de Vitalidade inato primal à vontade elevado a metade do nível arredondada para cima; em cada magia de herança/talento tengu pode escolher tradição divina/primal.'),('ceu','Nascido no Céu','Não sofre dano de queda, qualquer distância.'),('tempestade','Arremessado pela Tempestade','Resistência eletricidade metade do nível mínimo1; sucesso automático para mirar criatura ocultada só por chuva/névoa.'),('garras','Garras','Garras1d4 cortante, pugilato/ágil/acuidade/versátil perfurante.'),('mergulhador','Mergulhador','Deslocamento de natação15pés.',{'deslocamentoNatacao':15})])
anc('tripkee','Tripkee',6,'pequeno',['des','sab'],'for',38,'Visão na penumbra e +2 circunstância em Atletismo para Escalar.',[
 ('pele-venenosa','Pele Venenosa','Pele Tóxica: reação uma vez/hora quando tocado, incluindo Agarrar, acerto desarmado ou magia de toque;1d4 veneno, Fortitude básica pela maior CD de classe/magia. +1d4 no nível3 e cada dois seguintes.'),('rio','Ribeirinho','Deslocamento natação15pés.',{'deslocamentoNatacao':15}),('lingua','Língua Rápida','Língua entrega magias de toque e Interage de forma simples. Não faz tarefas com dedos/destreza significativa, testes ou segurar itens. Esta impressão não fornece alcance numérico; não foi inventado.'),('dedos-aderentes','Dedos Aderentes','+2 circunstância CDs Fortitude/Reflexos contra Desarmar/Empurrar/Reposicionar/Derrubar; sucesso para Escalar árvores, vinhas e vegetação vira crítico.'),('pele-grossa','Pele Grossa','PV de ancestralidade8; +1 circunstância contra doenças/venenos.',{'pv':8}),('membranas','Membranas ao Vento','Com uma mão livre, não sofre dano de queda, qualquer distância.')])
# Talentos iniciais/selecionados: nenhum requisito é removido para facilitar a interface.
def feat(owner,id,name,page,text,kind='ancestralidade',level=1,req='',**extra):
 t=dict(id=owner+'-'+id,nome=name,nivel=level,tipo=kind,requisitos=req,descricao=text,resumo=[text],fonte=F,pagina=page,**extra);t['classe' if kind=='classe' else 'ancestralidade']=owner;e['talentos'].append(t)
def cf(owner,id,name,page,text,level=1,req='',**extra):feat(owner,id,name,page,text,'classe',level,req,**extra)
feat('povo-gato','cochilo','Cochilo Felino',11,'Uma vez por hora dorme 10 minutos e recebe PV temporários iguais ao nível por 1 hora.')
feat('povo-gato','dentes-sabre','Dentes de Sabre',11,'Recebe mandíbula desarmada 1d6 perfurante, grupo pugilato.')
feat('povo-gato','viajante','Viajante Acolhedor',11,'Treina Diplomacia ou outra perícia se já treinado por outra fonte; recebe Socializador.')
feat('povo-gato','danca','Dança Felina',11,'Uma ação: Acrobacia contra CD de Reflexos de criatura adjacente. Sucesso dá −2 circunstância em Reflexos até início do próximo turno; crítico também deixa alvo desprevenido.')
feat('povo-gato','garras-escalada','Garras de Escalada',11,'Deslocamento de escalada 10 pés.',level=5)
feat('hobgoblin','reforco','Reforço Cantoriano',15,'Sucesso em salvaguarda contra doença/veneno vira crítico. Se outra habilidade já melhora assim, falha crítica vira falha.')
feat('hobgoblin','chicote','Chicote Impiedoso',15,'Ao acertar Golpe com arma corpo a corpo em inimigo assustado, ele não pode reduzir assustado abaixo de 1 até início do próximo turno.')
feat('hobgoblin','rosto-pedra','Rosto de Pedra',15,'+1 circunstância em salvaguardas contra medo; +2 circunstância na CD de Vontade contra ações de Intimidação.')
feat('hobgoblin','saude-vigorosa','Saúde Vigorosa',15,'Quando receberia drenado, pode fazer teste simples CD17; sucesso evita a condição.')
feat('hobgoblin','repreensao','Repreensão Agonizante',15,'Desmoralizar com sucesso faz alvo sofrer 1d4 mental no início dos turnos, 2d4 se mestre em Intimidação ou 3d4 se lendário. Termina sem assustado, além de 30 pés ou após 1 minuto.',level=5)
feat('kholo','esmigalhar','Esmigalhar',19,'Mandíbula passa de 1d6 para 1d8 perfurante e ganha agarrar.')
feat('kholo','cacador-matilha','Caçador de Matilha',19,'+2 circunstância nos testes para Ajudar; aliados também recebem +2 para Ajudá-lo.')
feat('kholo','familiar','Familiar Hiena',19,'Recebe uma hiena Minúscula como familiar.')
feat('kholo','nariz','Nariz Sensível',19,'Recebe faro impreciso 30 pés. Só escolhe no nível 1 e não pode retreinar para entrar ou sair.',req='Somente nível 1; não permite retreino.')
feat('kholo','resistencia','Resistência a Aflições',19,'+1 circunstância contra doença/veneno; sucesso vira crítico. Se outra habilidade já melhora assim, falha crítica vira falha.',level=5)
feat('kobold','encolher','Encolher-se',23,'Reação quando criatura de que tem consciência acerta crítico em Golpe que causaria dano: reduz dano por penalidade circunstancial nível+2, após dobrar pelo crítico. Atacante imune por 24 horas.')
feat('kobold','fugir','Escapulir',23,'Uma ação, adjacente a inimigo: Anda com +5 pés estado e +2 circunstância na CA contra reações do movimento; termina sem ficar adjacente a inimigo.')
feat('kobold','presenca-dragao','Presença do Dragão',23,'Sucesso contra medo vira crítico, mas falha vira falha crítica. +1 circunstância para Desmoralizar inimigo de seu nível ou menor.',req='Herança Escamas Dracônicas.')
feat('kobold','abrigo-aliado','Abrigo do Aliado',23,'Reação de fortuna uma vez por dia, antes de rolar salvaguarda e adjacente a aliado: usa modificador correspondente de um aliado adjacente.',level=5)
feat('povo-lagarto','falar-repteis','Falar com Répteis',27,'Pode perguntar, receber respostas e usar Diplomacia com animais répteis; mestre decide quais contam.')
feat('povo-lagarto','armamentos','Armamentos Iruxi',27,'Escolhe: garras 1d6 cortante e versátil perfurante; presas 1d8 perfurante/pugilato; cauda 1d6 contundente/pugilato/varredura. No nível 5 os ataques concedidos ou melhorados ganham especialização crítica. Pode repetir escolhendo diferente.')
feat('povo-lagarto','magia-osso','Magia dos Ossos',27,'Escolhe truque ocultista ou primal e tradição de suas magias inatas deste talento. Conjura à vontade, elevado a metade do nível arredondada para cima. A tradição também se aplica aos talentos que exigem Magia dos Ossos.')
feat('povo-lagarto','cauda-flexivel','Cauda Flexível',27,'Cauda faz Interagir simples, como abrir porta destrancada. Não realiza tarefas com dedos/destreza significativa, testes ou segurar itens.',level=5)
feat('povo-rato','bochechas','Bolsas nas Bochechas',31,'Guarda até quatro itens de Volume leve ou menor, nenhuma dimensão maior que 1 pé. Fala fica difícil de entender com itens. Guardar/retirar cada um exige Interagir. Uma ação esvazia tudo no chão de seu quadrado.')
feat('povo-rato','acumulador','Acumulador',31,'Recipientes/veículos mundanos comportam 50% mais Volume. Não reduz Volume dos itens nem amplia armazenamento mágico/extradimensional.')
feat('povo-rato','familiar','Familiar Rato',31,'Recebe familiar rato. Forma básica permanece rato; recebe habilidades normalmente.')
feat('povo-rato','falar-roedores','Falar com Roedores',31,'Pode perguntar, receber respostas e usar Diplomacia com roedores, não outros mamíferos. Mestre decide quais contam.')
feat('povo-rato','incisivos','Incisivos Cruéis',31,'Mandíbula passa de 1d4 para 1d6 perfurante e ganha ataque pelas costas. Pode escolher em qualquer nível e retreinar normalmente.')
feat('tengu','incendio-marinheiro','Fogo do Marinheiro',34,'Ignição inato primal à vontade, elevado a metade do nível arredondada para cima. Forma orbes de fogo e pode conjurar debaixo d’água.')
feat('tengu','salto-dedo','Salto de Um Dedo',35,'Uma ação para Salto vertical sem acionar reações de movimento/entrada/saída de quadrado.')
feat('tengu','buscar','Busca do Catador',35,'+2 circunstância para localizar objetos, incluindo portas secretas/perigos, até 30 pés usando Buscar.')
feat('tengu','grasnar','Grasnar!',35,'Reação quando falha criticamente em Enganação, Diplomacia ou Intimidação contra criatura sem tengu: vira falha. Testemunhas imunes por 24 horas.')
feat('tengu','chicote-tempestade','Chicote da Tempestade',35,'Arco Elétrico inato primal à vontade, elevado a metade do nível arredondada para cima.')
feat('tripkee','falar-coaxos','Falar por Coaxos',38,'Pode perguntar, receber respostas e usar Diplomacia com animais anfíbios, normalmente de traço anfíbio.')
feat('tripkee','defesa-cacador','Defesa do Caçador',38,'Reação uma vez por hora quando animal, besta, elemental, feérico, fungo ou planta visível o ataca: ataque usa CD de Natureza em vez de CA. Condições/efeitos que penalizariam CA continuam existindo para outros propósitos, como dano furtivo.',req='Treinado em Natureza.',requisitosEstruturados={'pericias':{'natureza':1}})
feat('tripkee','andar-selva','Andarilho da Selva',39,'Ignora terreno difícil em floresta/selva. Ao Equilibrar em superfície estreita/irregular de material vegetal, não fica desprevenido e sucesso vira crítico.')
feat('tripkee','noturno','Tripkee Noturno',39,'Visão no escuro; só escolhe no nível 1 e não pode retreinar para entrar ou sair.',req='Somente nível 1; não permite retreino.')
feat('tripkee','saltos','Saltos Fantásticos',39,'Salto ganha 10 pés de distância máxima horizontal e 5 pés vertical.',level=5)
# Classe: os mesmos IDs da seleção editorial original.
cf('alquimista','familiar','Familiar Alquímico',64,'Familiar com habilidade constructo permanente, sem exigir resistente e sem contar no limite normal de habilidades. Usa Inteligência em Percepção, Acrobacia e Furtividade.')
cf('alquimista','avaliacao','Avaliação Alquímica',64,'Identificar Alquimia de item segurado exige uma ação em vez de 10 minutos.',req='Treinado em Manufatura.',requisitosEstruturados={'pericias':{'manufatura':1}})
cf('alquimista','arremesso-longo','Arremesso Longo',64,'Incremento de alcance de bombas alquímicas passa de 20 para 30 pés.')
cf('alquimista','bombardeiro-rapido','Bombardeiro Rápido',64,'Uma ação: Interagir para sacar bomba/frasco ou Alquimia Rápida para criar bomba; então Golpe com ela. Mesmo criando duas, só ataca com uma.')
cf('alquimista','frascos-calmantes','Frascos Calmantes',64,'Criatura viva afetada por efeito mental que cura PV de seu frasco versátil pode repetir salvaguarda de Vontade para encerrar um efeito mental à escolha, +1 de item.',req='Campo Cirurgião.')
cf('alquimista','mutagenico-revitalizante','Mutagênico Revitalizante',65,'Uma ação sob mutagênico: cura 1d6 PV por cada dois níveis do item, mínimo 1d6, e termina o mutagênico.',level=2)
cf('barbaro','visao-agucada','Visão Aguçada',78,'Em Fúria recebe visão no escuro.')
cf('barbaro','adrenalina','Explosão de Adrenalina',78,'Em Fúria, limites de Volume sobrecarregado/máximo +2 e +1 estado em Atletismo para levantar, Escapar e Forçar Abertura.')
cf('barbaro','clareza','Momento de Clareza',78,'Uma ação de concentração/fúria: até fim do turno pode usar concentração sem traço fúria.')
cf('barbaro','intimidacao','Intimidação Furiosa',78,'Em Fúria, Desmoralizar/Matar de Susto ganham fúria. Recebe Olhar Intimidador e Matar de Susto assim que cumpre requisitos.')
cf('barbaro','arremessador','Arremessador Furioso',78,'Dano de Fúria aplica a armas arremessadas. Crítico Brutal/Devastador também, se possuir.')
cf('barbaro','investida','Investida Súbita',78,'Duas ações com floreio: Anda duas vezes e se termina ao alcance corpo a corpo de inimigo pode Golpear. Pode usar Escavar/Escalar/Voar/Nadar se possui Deslocamento correspondente.')
cf('campeao','avanco','Avanço Defensivo',94,'Duas ações com floreio: Ergue Escudo e Anda; se termina ao alcance corpo a corpo de inimigo pode Golpear. Outros movimentos exigem Deslocamento correspondente.')
cf('campeao','oracao','Oração Desesperada',94,'Ação livre uma vez por dia ao começar turno sem foco: ganha 1 Ponto de Foco só para devoção; perde se não gastar até fim do turno.')
cf('campeao','dominio','Domínio da Divindade',94,'Escolhe domínio de sua divindade e recebe magia inicial como devoção.')
cf('campeao','corcel','Corcel Fiel',95,'Companheiro animal jovem como montaria, normalmente com habilidade montaria. Mestre pode permitir outro. Se sagrado/profano, montaria e Golpes ganham traço.')
cf('investigador','pistas-falsas','Eliminar Pistas Falsas',107,'Falha crítica em Recordar Conhecimento ligado à pergunta de investigação ativa vira falha.')
cf('investigador','estudos','Estudos Flexíveis',107,'Nas preparações treina temporariamente uma perícia até próxima preparação. Treino temporário não vale como requisito para escolha permanente.')
cf('monge','postura-grou','Postura do Grou',120,'Uma ação de postura sem armadura. +1 circunstância CA; só asa do grou: 1d6 contundente, pugilato/ágil/acuidade/não letal. CDs de Salto em Altura/Distância −5; Salto +5 pés horizontal/+2 vertical.')
cf('monge','postura-dragao','Postura do Dragão',120,'Uma ação de postura sem armadura. Cauda do dragão 1d10 contundente, pugilato/retorno/não letal; ignora primeiro quadrado de terreno difícil ao Andar.')
cf('monge','postura-montanha','Postura da Montanha',120,'Uma ação de postura sem armadura e tocando chão. Só pedra caindo: 1d8 contundente, pugilato/vigoroso/não letal. +4 item CA, +2 circunstância contra movimento forçado/Repositionar/Empurrar/Derrubar; limite Destreza CA0 e Deslocamentos−5 pés. Bônus soma com potência nas roupas de explorador, Armadura Mística e braceletes de força.')
cf('monge','postura-tigre','Postura do Tigre',120,'Uma ação de postura sem armadura. Garras 1d8 cortante, pugilato/ágil/acuidade/não letal. Crítico com dano dá 1d4 sangramento persistente. Com Deslocamento≥20 pés pode dar Passos de10 pés.')
cf('monge','postura-lobo','Postura do Lobo',120,'Uma ação de postura sem armadura. Mandíbula 1d8 perfurante, pugilato/ágil/ataque pelas costas/acuidade/não letal. Contra alvo flanqueado ganha derrubar.')
cf('monge','magias-qi','Magias de Qi',120,'Recebe Agitação Interior, Impulso de Qi ou outra magia de qi de1ª graduação acessível. Escolhe divina/ocultista, usa Sabedoria, treinado em ataques/CD de magia e ganha1foco. Refocar 10 minutos estabiliza mente/respiração; foco elevado a metade do nível arredondada para cima.')
cf('oraculo','sussurros-fraqueza','Sussurros de Fraqueza',139,'Uma ação divina ligada à maldição: criatura até60 pés, aprende fraquezas e menor salvaguarda; +2 estado no próximo ataque/teste de perícia como ataque contra ela até fim do turno. Imune por1dia.')
cf('oraculo','aviso','Aviso Oracular',139,'Ação livre ligada à maldição ao prestes a rolar iniciativa: aliados até20 pés +2 estado na iniciativa e PV temporários metade do nível por1minuto. Bônus+3 se amaldiçoado2 no uso, +4 se3.')
cf('oraculo','prever-dano','Prever Dano',139,'Ação livre ligada à maldição uma vez/rodada; ação anterior Conjurar Magia não truque com dano. Início do próximo turno do alvo, sofre dano do mesmo tipo igual ao dobro da graduação. Imune por24 horas.')
cf('oraculo','inclinar-balanca','Inclinar a Balança',139,'Uma ação ligada à maldição: cura2+duas vezes nível a criatura até30 pés, viva/morta-viva. Nas preparações escolhe vida (cura vital normal) ou morte (cura do vazio e outras curas de mortos-vivos).')
cf('espadachim','esquiva','Esquiva Vistosa',164,'Reação ao ser alvo de ataque de criatura visível, não sobrecarregado: +2 circunstância CA contra ataque acionador; se Golpe errar, panache até fim do próximo turno.')
cf('espadachim','broquel','Broquel Elegante',164,'Erguer Escudo com broquel concede +2 circunstância em vez de+1. Com broquel erguido, crítico de falha em Golpe contra você concede panache até fim do próximo turno.')
cf('espadachim','desarme','Desarme Estiloso',164,'Desarmar ganha bravata.')
cf('espadachim','lamina-voadora','Lâmina Voadora',164,'Golpe Preciso aplica a Golpes com arma arremessada ágil/acuidade no primeiro incremento. Permite usá-los em Finalização Confiante e outras finalizações que se beneficiem de Golpe Preciso.')
cf('feiticeiro','ungir-aliado','Ungir Aliado',154,'Uma ação manipular: runa em aliado adjacente por1minuto. Quando você/aliado receberia magia sanguínea, pode abdicar para conceder ao ungido mesmo fora dos alvos. Só um ungido por vez.',level=2)
cf('feiticeiro','expansao-truques','Expansão de Truques',154,'Adiciona dois truques de sua lista ao repertório.',level=2)
cf('feiticeiro','sangrar','Sangrar',154,'Uma ação, anterior Conjurar Magia não truque: ataque de magia à distância contra CA de alvo até60 pés; sangramento persistente igual à graduação da magia anterior.',level=2)
e['lacunas']=[
 'Tradução integral das 322 páginas ainda não concluída. Este catálogo não substitui o livro completo.',
 'Arquétipos, maioria dos talentos, magias gerais/de foco, tesouros, descrições culturais e índice ainda precisam de tradução e revisão.',
 'Oráculo: prosa inicial diz dois espaços, tabela diz três de1ª graduação; cotejo de errata necessário antes de automatizar quantidade por essa prosa.',
 'Escolhas de divindade, animal, dragão, elemento, caminhos e magias devem ser registradas; o catálogo não presume decisões.',
 'Heranças versáteis dhampir, sangue de dragão e andarilho do crepúsculo ainda não integradas.',
 'Conversão automática dos efeitos de talentos, heranças, instintos e magias é limitada; bônus situacionais não são aplicados silenciosamente.'
]
# Melhorar espaçamento do conteúdo editorial sem transformar expressões de dado.
import re
skills={'manufatura':'Manufatura','intimidacao':'Intimidação','ocultismo':'Ocultismo','religiao':'Religião','diplomacia':'Diplomacia','enganacao':'Enganação','natureza':'Natureza','sociedade':'Sociedade','arcanismo':'Arcanismo','performance':'Performance','atletismo':'Atletismo','ladroagem':'Ladroagem'}
for opts in e['opcoes'].values():
 for o in opts:
  for key,name in skills.items():o['descricao']=re.sub(r'\b'+key+r'\b',name,o['descricao'])
  o['resumo']=[o['descricao']]
def clean(x):
 if isinstance(x,str):
  x=re.sub(r'(?<![\w])(\d+)(minutos|minuto|horas|hora|dias|dia|pés|po|PV)',r'\1 \2',x)
  x=re.sub(r'(nível|níveis|para|por|igual a|passa a|amaldiçoado|desajeitado|assustado|enfraquecido|estupefato|de|tem|no)(\d)',r'\1 \2',x)
  return x.replace('Repositionar','Reposicionar')
 if isinstance(x,list):return [clean(v) for v in x]
 if isinstance(x,dict):return {k:clean(v) for k,v in x.items()}
 return x
e=clean(e)
assert len(e['ancestralidades'])==8
assert sum(len(a['herancas']) for a in e['ancestralidades'])==54
assert len(e['talentos'])==73
assert sum(len(o) for o in e['opcoes'].values())==52
pathlib.Path(__file__).with_name('editorial.json').write_text(json.dumps(e,ensure_ascii=False,indent=2)+'\n')
print('Editorial restaurado:8ancestralidades/54heranças/73talentos/52opções.')
