#!/usr/bin/env python3
"""Entradas de devoção e qi: tradução manual do PDF fornecido, páginas físicas 258–259."""
import json,pathlib
rows=[]
def add(id,nome,en,rank,page,acoes,classe,tracos,text,summary,**meta):
 rows.append(dict(id=id,nome=nome,nomeOriginal=en,ranque=rank,nivel=rank,tipo='foco',truque=False,foco=True,tradicoes=['divina'] if classe=='campeao' else ['divina','ocultista'],acoes=acoes,tracos=['incomum','foco',classe]+tracos,descricao=text,resumo=[summary],fonte='player-core-2',pagina=page,paginaPdf=page,paginaImpressa=page-1,revisao='revisado',somenteConsulta=True,revisaoFonte='Tradução manual do texto e elevações do PDF fornecido, páginas físicas 258–259; sem executor de combate presumido.',automatizacaoCombate={'estado':'executor-pendente','semCalculoManual':True},**meta))
add('sacrificio-do-campeao','Sacrifício do Campeão',"champion's sacrifice",6,258,'reacao','campeao',['manuseio'],
 'Gatilho: um aliado é atingido por um Golpe ou falha em uma salvaguarda contra um efeito que não afeta você. Alcance: 9 m. Alvo: o aliado que acionou a reação. Você cria um vínculo com o aliado para sofrer em seu lugar. Todos os efeitos do acerto ou da salvaguarda falha se aplicam a você em vez de ao alvo. Por exemplo, se o alvo falhar criticamente contra uma Bola de Fogo, você recebe dano dobrado. Esses efeitos ignoram quaisquer resistências, imunidades ou outras habilidades suas que poderiam mitigá-los; porém as do alvo se aplicam antes de você receber o efeito.',
 'Reação: assume todos os efeitos de um Golpe ou salvaguarda falha de um aliado a até 9 m. A defesa do aliado vale antes da transferência; a sua não reduz o efeito.',mecanica={'alcance':9,'transferenciaEfeito':True,'defesasAplicadas':'alvo-original-apenas'})
add('desafio-do-heroi','Desafio do Herói',"hero's defiance",10,258,'livre','campeao',['concentracao','cura','vitalidade'],
 'Gatilho: um ataque reduziria seus PV a 0. Você brada em desafio e recebe uma explosão de cura. Imediatamente antes de aplicar o dano do ataque, recupera 6d8+20 PV. Se isso impedir que o ataque reduza seus PV a 0, não fica inconsciente nem morrendo. Independentemente do resultado, só pode usar Desafio do Herói outra vez depois de Refocar ou realizar suas preparações diárias. Não pode usar esta magia contra efeitos com o traço morte nem efeitos que não deixariam restos, como Desintegrar.',
 'Ação livre antes do dano que o derrubaria: cura 6d8+20 PV. Recarrega ao Refocar ou preparar-se; não evita efeitos de morte nem desintegração.',mecanica={'cura':'6d8+20','recarga':['refocar','preparacoes-diarias'],'gatilho':'ataque-reduziria-pv-a-zero','naoFuncionaContra':['morte','sem-restos']})
add('avanco-espectral','Avanço Espectral','spectral advance',5,258,[1,2],'campeao',['concentracao','polimorfia','espirito'],
 'Assumindo uma forma espiritual, você atravessa o campo de batalha para enfrentar um inimigo. Anda até um espaço adjacente a um inimigo. Com duas ações de conjuração, pode Andar duas vezes em vez de uma. Se tiver Deslocamento de voo, pode Voar em vez de Andar. Se estiver montado, pode fazer a montaria mover-se em seu lugar. Esse movimento não aciona reações e ignora terreno difícil e terreno difícil maior. Durante o movimento, você ou sua montaria recebe resistência a todo dano igual ao seu nível.',
 'Uma ou duas ações permitem um ou dois movimentos até um inimigo, sem reações nem terreno difícil; durante o percurso, resistência a todo dano igual ao nível.',mecanica={'movimentosPorAcoes':{'1':1,'2':2},'naoAcionaReacoes':True,'ignoraTerrenoDificilMaior':True,'resistenciaDuranteMovimento':'nivel'})
add('explosao-de-qi','Explosão de Qi','qi blast',3,258,[1,2,3],'monge',['concentracao','forca','manuseio'],
 'Área: cone de 4,5 m ou maior. Defesa: Fortitude. Você libera qi em uma explosão que causa 2d6 de força. Com duas ações, o cone aumenta para 9 m e o dano para 3d6. Com três ações, o cone aumenta para 18 m e o dano para 4d6. Cada criatura na área faz uma salvaguarda de Fortitude. Sucesso crítico: não é afetada. Sucesso: metade do dano. Falha: dano completo e empurrada 1,5 m. Falha crítica: dano dobrado e empurrada 3 m. Elevada (+1): o dano aumenta em 1d6 se usada uma ação, ou 2d6 se usadas duas ou três ações.',
 'Uma a três ações determinam cone e dano de força; Fortitude reduz o dano e falhas empurram. Elevação depende das ações gastas.',salvaguarda='fortitude',mecanica={'porAcoes':{'1':{'cone':4.5,'dano':'2d6','elevacao':'1d6'},'2':{'cone':9,'dano':'3d6','elevacao':'2d6'},'3':{'cone':18,'dano':'4d6','elevacao':'2d6'}},'empurraoFalha':1.5,'empurraoFalhaCritica':3})
add('encurtar-a-distancia','Encurtar a Distância','shrink the span',3,258,1,'monge',['manuseio','teleporte'],
 'Alcance: veja o texto. O mundo parece encolher diante de seus passos. Você se teleporta até uma distância igual ao seu Deslocamento, dentro de sua linha de visão.',
 'Uma ação: teleporta-se até seu Deslocamento, para um local na linha de visão.',mecanica={'alcance':'deslocamento','exigeLinhaDeVisao':True})
add('ira-da-medusa','Ira da Medusa',"medusa's wrath",8,258,3,'monge',['concentracao','manuseio'],
 'Você desfere um ataque infundido de poder petrificante. Faça um Golpe desarmado com os efeitos adicionais abaixo. Sucesso crítico: o alvo fica lento 2 e faz uma salvaguarda de Fortitude ao fim de cada turno. Essa salvaguarda contínua tem o traço incapacitação. Uma falha aumenta lento em 1; falha crítica aumenta em 2. Um sucesso reduz lento em 1. Quando a criatura ficar incapaz de agir por causa de lento imposto por Ira da Medusa, fica petrificada permanentemente. A magia termina se a criatura ficar petrificada ou se a condição lento for removida. Sucesso: como sucesso crítico, mas o alvo começa lento 1.',
 'Golpe desarmado impõe lento 1 ou 2; Fortitude ao fim dos turnos reduz ou aumenta a condição. Se lento impedir todas as ações, o alvo fica petrificado.',mecanica={'golpeDesarmado':True,'lentoSucesso':1,'lentoCritico':2,'salvaguardaPosterior':'fortitude','incapacitacaoApenasSalvaguardaPosterior':True})
add('toque-da-morte','Toque da Morte','touch of death',8,258,2,'monge',['concentracao','incapacitacao','manuseio'],
 'Defesa: Fortitude. Duração: 1 mês. Faça um Golpe desarmado corpo a corpo. Se acertar e o alvo permanecer vivo, a qualquer momento durante a duração pode gastar uma ação, com os traços auditivo e concentração, para pronunciar uma palavra de morte que pode matá-lo instantaneamente. O alvo faz uma salvaguarda de Fortitude. Sucesso crítico: sobrevive, a magia termina e fica temporariamente imune por 24 horas. Sucesso: fica atordoado 1 e sofre 40 de dano; a magia termina e fica imune por 24 horas. Falha: fica atordoado 3 e sofre 80 de dano; a magia continua, mas ele fica imune por 24 horas a ser morto por Toque da Morte. Falha crítica: morre. Conjurar Toque da Morte novamente encerra os efeitos de qualquer conjuração anterior sua. Elevada (+1): o dano aumenta em 10 na falha e em 5 no sucesso.',
 'Golpe implanta uma ameaça por 1 mês; uma ação posterior exige Fortitude, causando atordoamento e dano ou morte. Só uma conjuração sua pode permanecer ativa.',salvaguarda='fortitude',mecanica={'golpeDesarmadoInicial':True,'acaoPosterior':1,'danoSucesso':40,'danoFalha':80,'elevacaoSucesso':5,'elevacaoFalha':10,'falhaCriticaMorte':True,'limiteEfeitos':1})
add('abracar-o-nada','Abraçar o Nada','embrace nothingness',9,259,2,'monge',['concentracao','manuseio'],
 'Duração: 1 minuto. Você esvazia o corpo de substância e se torna uno com o nada. Recebe resistência a dano físico igual ao seu nível. Move-se à metade de sua velocidade normal, mas pode mover-se em qualquer direção, inclusive para cima e para baixo. Enquanto se move, fica ocultado. Fora de seu turno, e durante seu turno até realizar uma ação com o traço movimento, fica invisível. Pode atravessar objetos sólidos inanimados desde que não tenham mais de 60 cm de espessura.',
 'Por 1 minuto, resistência física igual ao nível, movimento à metade em qualquer direção, invisibilidade enquanto imóvel e passagem por objetos de até 60 cm.',mecanica={'resistenciaFisica':'nivel','fatorDeslocamento':0.5,'espessuraMaximaObjeto':0.6,'duracaoRodadas':10})
add('forma-de-qi','Forma de Qi','qi form',9,259,1,'monge',['concentracao','polimorfia'],
 'Duração: 1 minuto. Você assume uma forma especial de qi: cabelo, penas, pele ou escamas mudam de cor e brilham. Recebe Deslocamento de voo igual ao terrestre. Escolha força, espiritual, vitalidade ou vazio: todos os seus Golpes causam mais 1d6 do tipo escolhido. Uma coroa brilhante da mesma cor de seu qi envolve o corpo, como efeito de luz. Essa coroa é uma aura em emanação de 1,5 m e causa 2d6 do tipo escolhido a criaturas que começarem seu turno nela. Se sobrepuser um efeito de escuridão, o brilho tenta neutralizá-lo; independentemente do resultado, não pode tentar neutralizar aquele mesmo efeito novamente por 1 dia. Pode Sustentar para ampliar a emanação a 9 m ou fazê-la voltar a 1,5 m. Suas armas e ataques desarmados perdem o traço não letal. Sofre −2 de estado em salvaguardas contra emoção, mas recebe +2 de estado contra todos os demais efeitos mentais.',
 'Por 1 minuto, voo, mais 1d6 nos Golpes e aura de 2d6; Sustentar alterna o raio entre 1,5 e 9 m. Muda defesas mentais e elimina ataques não letais.',mecanica={'voo':'deslocamento-terrestre','tiposEscolha':['forca','espiritual','vitalidade','vazio'],'danoGolpeExtra':'1d6','danoAura':'2d6','raiosAura':[1.5,9],'bonusSalvaguardaMentalNaoEmocao':2,'penalidadeSalvaguardaEmocao':-2})
add('postura-das-sombras-aderentes','Postura das Sombras Aderentes','clinging shadows stance',4,259,1,'monge',['manuseio','sombra','postura'],
 'Duração: até sair da postura. Você assume a postura das sombras aderentes. Pode fazer Golpes de abraço sombrio que causam 1d4 de vazio, pertencem ao grupo pugilato e têm os traços ágil, agarrar, alcance e desarmado. Nessa postura, recebe +2 de circunstância em Atletismo para Agarrar e na CD para criaturas Escaparem de você.',
 'Postura concede ataque desarmado ágil de vazio com alcance e agarrar; +2 circunstância para Agarrar e impedir que escapem.',mecanica={'ataque':{'nome':'Abraço Sombrio','dano':'1d4','tipo':'vazio','grupo':'pugilato','tracos':['agil','agarrar','alcance','desarmado']},'bonusAgarrarEscape':{'tipo':'circunstancia','valor':2}})
add('postura-dos-ventos-selvagens','Postura dos Ventos Selvagens','wild winds stance',4,259,1,'monge',['ar','manuseio','postura'],
 'Duração: até sair da postura. Você assume uma postura de ventos fluentes e envia ondas de energia à distância. Pode fazer Golpes desarmados de impacto de vento como ataques à distância contra alvos a até 9 m. Causam 1d6 contundente, pertencem ao grupo pugilato e têm os traços ágil, não letal, propulsivo e desarmado. Ignoram ocultação e todas as coberturas. Nessa postura, recebe +2 de circunstância na CA contra ataques à distância.',
 'Postura permite Golpes desarmados à distância de 1d6 que ignoram cobertura e ocultação; +2 circunstância na CA contra ataques à distância.',mecanica={'ataque':{'nome':'Impacto de Vento','dano':'1d6','tipo':'contundente','grupo':'pugilato','alcance':9,'tracos':['agil','nao-letal','propulsivo','desarmado'],'ignora':['ocultacao','cobertura']},'bonusCaContraDistancia':{'tipo':'circunstancia','valor':2}})
add('teia-das-sombras','Teia das Sombras',"shadow's web",7,259,2,'monge',['concentracao','manuseio'],
 'Requisito: estar na Postura das Sombras Aderentes. Área: emanação de 9 m. Defesa: Fortitude. Escuridão agarradora irrompe de você e causa 14d4 de vazio. Cada criatura na área faz Fortitude. Sucesso crítico: não é afetada. Sucesso: metade do dano e enfraquecido 1 por 1 rodada. Falha: dano completo e enfraquecido 2 por 1 rodada. Falha crítica: dano dobrado, atordoado 1, enfraquecido 2 por 1 rodada e imobilizado por 1 rodada ou até Escapar, o que ocorrer primeiro. Elevada (+1): o dano de vazio aumenta em 2d4.',
 'Na postura de sombras, emanação causa 14d4 de vazio; Fortitude controla dano e enfraquecimento. Falha crítica também atordoa e imobiliza.',salvaguarda='fortitude',mecanica={'requerPostura':'postura-das-sombras-aderentes','dano':'14d4','tipo':'vazio','elevacao':'2d4','raio':9})
add('harmonizar-se','Harmonizar-se','harmonize self',2,259,1,'monge',['concentracao','cura','vitalidade'],
 'Você se cura de uma das maneiras abaixo, escolhida ao conjurar: recupera 8 PV; ou tenta curar um veneno ou doença que o aflige, fazendo uma tentativa de neutralizar a aflição. Elevada (+1): se escolheu recuperar PV, a cura aumenta em 8.',
 'Uma ação: cura 8 PV, mais 8 por graduação extra, ou tenta neutralizar um veneno ou doença que o aflige.',mecanica={'cura':8,'elevacaoCura':8,'alternativa':'neutralizar-veneno-ou-doenca'})

add('salto-do-vento','Salto do Vento','wind jump',5,259,1,'monge',['ar','concentracao'], 'Duração: 1 minuto. Recebe Deslocamento de voo igual ao seu Deslocamento. Deve encerrar seu turno em chão sólido, ou cai. Elevada (6ª): ao fim do turno, pode tentar Acrobacia CD 30 para encontrar apoio no ar; se obtiver sucesso, não cai.', 'Voo por 1 minuto, exigindo pousar ao fim de cada turno. Na 6ª graduação, Acrobacia CD 30 permite manter-se no ar.',mecanica={'voo':'deslocamento','exigePousoFimTurno':True,'elevacao6':{'pericia':'acrobacia','cd':30}})
assert len(rows)==14
pathlib.Path(__file__).with_name('focos-devocao-qi-qa.json').write_text(json.dumps({'magias':rows,'lacunas':[{'categoria':'automacao-focos-devocao-qi','descricao':'Quatorze focos adicionais de devoção e qi possuem texto traduzido; transferência de dano, movimentos compostos, reação à derrota e petrificação precisam de executores específicos.'}]},ensure_ascii=False,indent=2)+'\n')
print('14 magias de devoção/qi traduzidas.')
