#!/usr/bin/env python3
"""Tradução manual das revelações avançadas do Oráculo, PC2 Remaster."""
import json,pathlib
rows=[]
def add(id,nome,en,rank,page,actions,tracos,text,summary,**meta):
 rows.append(dict(id=id,nome=nome,nomeOriginal=en,ranque=rank,nivel=rank,tipo='foco',truque=False,foco=True,tradicoes=['divina'],acoes=actions,tracos=['incomum','foco','oraculo']+tracos,descricao=text,resumo=[summary],fonte='player-core-2',pagina=page,paginaPdf=page,paginaImpressa=page-1,revisao='revisado',somenteConsulta=True,revisaoFonte='Tradução manual da entrada do PDF fornecido; página física indicada. Sem executor de combate presumido.',automatizacaoCombate={'estado':'executor-pendente','semCalculoManual':True},**meta))
add('defesa-ancestral','Defesa Ancestral','ancestral defense',3,260,'reacao',['fortuna','manuseio','mental'],
 'Gatilho: você está prestes a fazer uma salvaguarda de Vontade. Seu ancestral o protege contra quem tentaria dobrar sua vontade. Role a salvaguarda que acionou a reação duas vezes e use o melhor resultado.',
 'Reação de fortuna: role uma salvaguarda de Vontade duas vezes e use o melhor resultado.',mecanica={'fortuna':'vontade','rolagens':2,'usar':'melhor'})
add('forma-ancestral','Forma Ancestral','ancestral form',6,260,2,['concentracao','manuseio'],
 'Duração: sustentada até 1 minuto. Você assume a forma de seus espíritos ancestrais, tornando-se invisível e quase corpóreo. Recebe resistência 10 a todo dano, exceto força, espiritual e dano de Golpes com a runa de propriedade toque fantasma. Essa resistência dobra contra dano não mágico ou Golpes que incluam dano de precisão. Recebe Deslocamento de voo igual ao terrestre; subir ao Voar não conta como terreno difícil. Não pode atravessar objetos sólidos, mas pode flutuar por fendas minúsculas. Não pode Conjurar Magias, embora possa Sustentá-las, ativar itens ou usar ações com ataque ou manuseio. Elevada (+2): a resistência aumenta em 5.',
 'Forma invisível sustentada: voo e resistência ampla, dobrada contra dano não mágico ou Golpes com precisão. Impede conjuração, ativação, ataques e manuseio.',mecanica={'resistencia':10,'elevacaoResistencia':{'intervalo':2,'valor':5},'exceto':['forca','espiritual','toque-fantasma'],'resistenciaDuplaContra':['nao-magico','golpe-com-precisao'],'invisivel':True,'voo':'deslocamento-terrestre','sustentada':True})
add('persistencia-no-campo-de-batalha','Persistência no Campo de Batalha','battlefield persistence',3,260,'reacao',['concentracao'],
 'Gatilho: você está prestes a fazer uma salvaguarda, mas ainda não rolou. Você é difícil de deter em batalha. Recebe +2 de estado na salvaguarda que acionou a reação. Se ela for contra um efeito de incapacitação, esse efeito trata você como se tivesse 2 níveis a mais.',
 'Reação antes de rolar: +2 estado em uma salvaguarda e trata seu nível como 2 maior contra incapacitação.',mecanica={'bonusSalvaguarda':{'tipo':'estado','valor':2},'nivelExtraContraIncapacitacao':2})
add('deleite-na-retribuicao','Deleite na Retribuição','revel in retribution',6,260,1,['concentracao','manuseio','mental'],
 'Duração: 1 minuto. O tempo parece desacelerar, permitindo atingir oponentes no meio do movimento. Recebe a habilidade Golpe Reativo e imediatamente ganha uma segunda reação, que só pode usar para Golpe Reativo. No início de cada turno subsequente, quando recuperar suas ações, ganha uma reação adicional que também só pode usar para Golpe Reativo. Acertar um Golpe Reativo concede 5 PV temporários, que duram pelo restante da magia. Elevada (+1): os PV temporários recebidos por um Golpe Reativo bem-sucedido aumentam em 1.',
 'Por 1 minuto, concede Golpe Reativo e uma reação extra por turno exclusivamente para ele; acertar concede 5 PV temporários, com elevação.',mecanica={'reacaoExtra':'golpe-reativo','pvTemporariosAoAcertar':5,'elevacaoPvTemporarios':1,'duracaoRodadas':10})
add('armadura-de-ossos','Armadura de Ossos','armor of bones',3,260,1,['manuseio'],
 'Duração: 1 minuto. Você ossifica sua forma física, imitando a resistência dos ossos. Recebe resistência 3 a frio, eletricidade, fogo, perfurante e cortante. Elevada (+1): a resistência aumenta em 1.',
 'Por 1 minuto, resistência 3 a frio, eletricidade, fogo, perfurante e cortante; mais 1 por graduação extra.',mecanica={'resistencia':3,'tipos':['frio','eletricidade','fogo','perfurante','cortante'],'elevacao':1,'duracaoRodadas':10})
add('reivindicar-morto-vivo','Reivindicar Morto-vivo','claim undead',6,260,2,['concentracao','incapacitacao','manuseio'],
 'Alcance: 9 m. Alvo: 1 criatura morta-viva. Defesa: Vontade. Duração: 10 minutos. Você tenta tomar o controle do morto-vivo ou obrigá-lo a reconhecê-lo como mestre. Se outra criatura já o controla, ela faz Vontade para conservar o controle; caso contrário, o alvo faz a salvaguarda. Sucesso crítico: o alvo não é afetado. Sucesso: atordoado 1 e confuso por 1 rodada, resistindo a suas ordens. Falha: fica controlado por você e segue suas ordens. Ele, ou o controlador anterior, pode tentar Vontade ao fim de cada turno do alvo; um sucesso encerra a magia e deixa o morto-vivo atordoado 1 e confuso por 1 rodada. Se der uma ordem obviamente autodestrutiva, o alvo não age até receber nova ordem. Falha crítica: como falha, mas uma nova salvaguarda só ocorre ao dar uma nova ordem contrária à natureza do alvo.',
 'Controla um morto-vivo por até 10 minutos; Vontade do alvo ou controlador decide. Ordens autodestrutivas interrompem suas ações.',salvaguarda='vontade',mecanica={'duracaoRodadas':100,'salvaguardaControladorSeExistente':True,'ordemAutodestrutiva':'aguarda-nova-ordem'})
add('vazio-interestelar','Vazio Interestelar','interstellar void',3,261,2,['frio','concentracao','manuseio'],
 'Alcance: 9 m. Alvo: 1 criatura. Defesa: Fortitude. Duração: sustentada até 1 minuto. Você invoca as profundezas geladas do espaço para trazer frio terrível ao inimigo. O vazio congelante envolve o alvo e causa 3d6 de frio imediatamente e na primeira vez a cada rodada que Sustentar a magia em turnos futuros, com Fortitude básica. O alvo fica fatigado enquanto o efeito persistir. Elevada (+1): o dano de frio aumenta em 1d6.',
 'Sustentada por até 1 minuto: causa 3d6 de frio agora e no primeiro Sustentar de cada rodada, com Fortitude básica; mantém o alvo fatigado.',salvaguarda='fortitude',mecanica={'dano':'3d6','tipo':'frio','elevacao':'1d6','sustentada':True,'fatigadoDuranteEfeito':True})
add('ponte-de-luar','Ponte de Luar','moonlight bridge',6,261,2,['concentracao','luz','manuseio'],
 'Alcance: 9 m. Duração: 10 minutos. Você invoca uma ponte de luar radiante e cintilante, com 3 m de largura. Ela deve começar no chão em um ponto no alcance e se estende como um plano horizontal, em linha reta ou inclinado até 45 graus para cima ou para baixo, por até 36 m. Tem CA 10, Dureza 30 e 60 PV, e é imune a todo dano exceto força, espiritual e dano de Golpes com toque fantasma. Você e seus aliados podem atravessá-la normalmente; outras criaturas passam através dela ao tentar atravessá-la. A ponte bloqueia ataques físicos, etéreos e incorpóreos que cruzariam sua superfície, de cima ou de baixo. Pode Dispensar a magia. Elevada (+1): comprimento aumenta em 6 m, PV em 20 e você pode aumentar a largura em até mais 1,5 m.',
 'Ponte seletiva de até 36 m por 10 minutos; aliados passam sobre ela, outros atravessam. Bloqueia ataques e tem Dureza 30, com elevação de tamanho e PV.',mecanica={'largura':3,'comprimento':36,'ca':10,'dureza':30,'pv':60,'elevacao':{'comprimento':6,'pv':20,'larguraMaxima':1.5}})
add('chamas-giratorias','Chamas Giratórias','whirling flames',3,261,2,['concentracao','fogo','manuseio'],
 'Alcance: 9 m. Área: até duas explosões de 1,5 m que não se sobreponham. Defesa: Reflexos básico. Você invoca uma tempestade de chamas giratórias que envolve todas as criaturas na área, causando 5d6 de fogo com Reflexos básico. Elevada (+2): o dano aumenta em 3d6 e pode acrescentar outra explosão de 1,5 m, sem sobreposição.',
 'Duas pequenas explosões sem sobreposição causam 5d6 de fogo com Reflexos básico. A cada duas graduações extras, mais dano e outra explosão.',salvaguarda='reflexos',mecanica={'dano':'5d6','tipo':'fogo','explosoes':2,'raio':1.5,'elevacao':{'intervalo':2,'dano':'3d6','explosoes':1}})
add('fuzilaria-flamejante','Fuzilaria Flamejante','flaming fusillade',6,261,2,['concentracao','fogo','manuseio'],
 'Duração: 1 minuto. Você invoca uma barragem interminável de chamas, com explosões como pequenos sóis ao redor. Conjura Ignição como parte de conjurar Fuzilaria Flamejante. Durante sua duração, o tempo de conjuração de Ignição é reduzido de duas ações para uma. Elevada (9ª): durante a duração, também recebe bônus de estado no dano causado por Ignição igual à graduação de Fuzilaria Flamejante.',
 'Conjura Ignição imediatamente e, por 1 minuto, reduz sua conjuração a uma ação; na 9ª graduação acrescenta bônus de estado ao dano.',mecanica={'magiaDelegada':'ignicao','acoesIgnição':1,'duracaoRodadas':10,'bonusDanoRanque9':'ranque'})
add('adiar-aflicao','Adiar Aflição','delay affliction',3,262,2,['concentracao','cura','manuseio','vitalidade'],
 'Alcance: 9 m. Alvo: 1 criatura. Uma descarga de energia curativa retarda uma aflição do alvo e restaura 3d8 PV. Você tenta neutralizar uma aflição que sabe que o alvo possui: um sucesso suspende seus efeitos por 1 hora em vez de removê-la. Depois, o alvo fica temporariamente imune a Adiar Aflição por 1 dia. Não precisa conhecer o nome específico da aflição, mas precisa estar ciente dela; por exemplo, não pode adiar um veneno ingerido durante sua latência sem saber do veneno. Elevada (+1): a cura aumenta em 1d8 e pode tentar suspender uma aflição adicional.',
 'Cura 3d8 e tenta suspender uma aflição conhecida por 1 hora; o alvo fica imune por 1 dia. Elevação acrescenta cura e outra aflição.',mecanica={'cura':'3d8','elevacaoCura':'1d8','aflicoes':1,'elevacaoAflicoes':1,'suspensaoHoras':1,'imunidadeHoras':24})
add('forma-doadora-de-vida','Forma Doadora de Vida','life-giving form',6,262,2,['concentracao','cura','luz','manuseio','vitalidade'],
 'Duração: 1 minuto. Você transcende sua forma física e vira um farol de energia curativa. O corpo emite luz intensa como uma tocha. Recebe resistência 5 a precisão e fraqueza 5 a vazio; seus Golpes desarmados causam mais 1d4 de vitalidade. Pode tocar uma criatura viva com Interagir para restaurar 6d8 PV. Quando uma criatura tocar você com Interagir, pode permitir que receba a mesma cura. Em qualquer caso, fica temporariamente imune à cura de Forma Doadora de Vida por 1 minuto. A cura é de vitalidade e não pode curar você mesmo. Uma criatura ferida por vitalidade, como um morto-vivo, que toque você ou o fira com ataque desarmado ou arma corpo a corpo sem alcance sofre 3d4 de vitalidade, sem ganhar imunidade temporária. Pode Dispensar a magia. Elevada (+1): a cura de Interagir aumenta em 1d8, o dano de vitalidade aumenta em 1 e a resistência e fraqueza aumentam em 1.',
 'Por 1 minuto, toques voluntários curam 6d8 com imunidade de 1 minuto; mortos-vivos que o tocam sofrem vitalidade. Recebe resistência a precisão e fraqueza a vazio.',mecanica={'cura':'6d8','elevacaoCura':'1d8','danoContatoVulneravelVitalidade':'3d4','danoGolpeExtra':'1d4','resistenciaPrecisao':5,'fraquezaVazio':5,'imunidadeCuraRodadas':10,'naoCuraConjurador':True})
add('acessar-saber','Acessar Saber','access lore',3,262,1,['fortuna','manuseio'],
 'Duração: 1 minuto. Você vasculha o conhecimento divino do multiverso por informações sobre um assunto. Escolha uma perícia Saber. Temporariamente recebe nessa perícia o mesmo grau de proficiência que tem na conjuração de Oráculo.',
 'Por 1 minuto, recebe em um Saber escolhido o grau de proficiência da conjuração de Oráculo.',mecanica={'periciaEscolha':'saber','grau':'conjuracao-oraculo','duracaoRodadas':10})
add('segredo-terrivel','Segredo Terrível','dread secret',6,262,2,['concentracao','emocao','medo','manuseio','mental'],
 'Alcance: 18 m. Alvos: até 6 criaturas. Defesa: Vontade. Duração: até o início de seu próximo turno. Você pronuncia um segredo poderoso contrário à natureza fundamental das criaturas. Escolha uma resistência ou fraqueza específica com valor numérico que acredita que ao menos um alvo possua, por Recordar Conhecimento ou experiência prévia; por exemplo resistência a fogo ou fraqueza a prata. Se a informação estiver incorreta para um alvo, a magia não o afeta. Os alvos afetados fazem Vontade. Sucesso crítico: não é afetado. Sucesso: sofre 1 de dano que corresponde ao tipo ou traço da fraqueza escolhida, acionando-a; ou perde a resistência escolhida até o fim de seu próximo turno. Falha: como sucesso e assustado 1. Falha crítica: como falha, mas assustado 3.',
 'Contra até 6 alvos com resistência ou fraqueza conhecida, aciona a fraqueza ou remove a resistência temporariamente; Vontade também determina medo.',salvaguarda='vontade',mecanica={'alvosMaximos':6,'exigeResistenciaFraquezaNumericaReal':True,'danoParaAcionarFraqueza':1,'assustadoFalha':1,'assustadoFalhaCritica':3})
add('explosao-trovejante','Explosão Trovejante','thunderburst',3,262,2,['ar','concentracao','manuseio','sonico'],
 'Alcance: 30 m. Área: explosão de 6 m. Defesa: Fortitude. Você cria uma forte explosão de ar e um estrondo de trovão, causando 2d6 contundente e 2d6 sônico. Cada criatura na área faz Fortitude. Sucesso crítico: não é afetada. Sucesso: metade do dano. Falha: dano completo e surda por 1 minuto. Falha crítica: dano dobrado e surda por 1 hora. Elevada (+2): cada tipo de dano aumenta em 2d6 e o raio da área aumenta em 1,5 m.',
 'Explosão causa 2d6 contundente e 2d6 sônico; Fortitude reduz dano, e falhas causam surdez. A cada duas graduações cresce o dano e a área.',salvaguarda='fortitude',mecanica={'danos':[{'tipo':'contundente','formula':'2d6'},{'tipo':'sonico','formula':'2d6'}],'raio':6,'elevacao':{'intervalo':2,'danoPorTipo':'2d6','raio':1.5},'surdezFalhaRodadas':10,'surdezFalhaCriticaRodadas':600})
add('forma-da-tempestade','Forma da Tempestade','tempest form',6,263,2,['concentracao','manuseio','polimorfia'],
 'Duração: sustentada até 1 minuto. Seu corpo se torna fluido: escolha ar, água ou névoa. A magia recebe ar se escolher ar ou névoa e água se escolher água ou névoa. Você e sua armadura ficam amorfos. Perde bônus de item na CA e usa a proficiência de defesa sem armadura para calculá-la. Recebe resistência 10 a dano físico e imunidade a precisão. Pode passar por fendas minúsculas e não precisa respirar. Não pode conjurar, ativar itens nem usar ações com ataque ou manuseio, exceto as concedidas pela magia. Ar: voo de 6 m e invisibilidade enquanto no ar; pode produzir os efeitos de Lufada de Vento de seu espaço com uma atividade de duas ações e manuseio. Névoa: voo de 6 m; qualquer criatura de um lado de seu espaço fica ocultada para quem a alveja do lado oposto. Água: natação de 6 m e invisibilidade enquanto na água. Pode eletrificar-se com uma ação de manuseio: deixa de ficar invisível na água, pois a eletricidade revela sua localização, mas quem fizer um ataque corpo a corpo contra você sofre 1d6 elétrico. Elevada (+2): a resistência aumenta em 5 e o dano elétrico da forma de água carregada aumenta em 1.',
 'Forma sustentada de ar, água ou névoa: resistência física, imunidade a precisão e deslocamento especial. Limita ações; cada forma oferece invisibilidade ou cobertura e poderes próprios.',mecanica={'formas':['ar','agua','nevoa'],'resistenciaFisica':10,'imunePrecisao':True,'perdeBonusItemCa':True,'usaDefesaSemArmadura':True,'movimento':6,'retaliacaoAguaEletrificada':'1d6','elevacaoResistencia':5,'elevacaoDanoEletricoFixo':1})

assert len(rows)==16
pathlib.Path(__file__).with_name('focos-oraculo-avancados-qa.json').write_text(json.dumps({'magias':rows,'lacunas':[{'categoria':'automacao-revelacoes-avancadas','descricao':'Revelações avançadas traduzidas permanecem de consulta até terem executores específicos de fortuna, reação, formas e resistências condicionais.'}]},ensure_ascii=False,indent=2)+'\n')
print(len(rows),'revelações avançadas traduzidas.')
