#!/usr/bin/env python3
"""Tradução editorial manual: todos os vinte focos avançados das dez linhagens PC2.
Fonte primária: PDF fornecido, páginas físicas 263–266, OCR preservado no artefato.
Não atribui execução de combate a regras ainda sem executor.
"""
import json,pathlib
rows=[]
def add(id,nome,en,rank,page,actions,trad,tracos,text,resumo,**meta):
 rows.append(dict(id=id,nome=nome,nomeOriginal=en,ranque=rank,nivel=rank,tipo='foco',truque=False,foco=True,tradicoes=trad,acoes=actions,tracos=['incomum','foco','feiticeiro']+tracos,descricao=text,resumo=[resumo],fonte='player-core-2',pagina=page,paginaPdf=page,paginaImpressa=page-1,revisao='revisado',somenteConsulta=True,revisaoFonte='Tradução manual integral da entrada e de suas elevações no PDF fornecido; páginas físicas 263–266. Combate ainda sem executor para esta entrada.',automatizacaoCombate={'estado':'executor-pendente','semCalculoManual':True},**meta))
add('sussurros-aberrantes','Sussurros Aberrantes','aberrant whispers',3,263,[1,2,3],['ocultista'],['auditivo','concentracao','mental'],
 'Área: emanação de 1,5 m ou maior. Alvos: cada inimigo na área. Defesa: Vontade. Duração: 1 rodada. Você pronuncia frases em uma língua desconhecida, agredindo a mente de quem está por perto. Cada alvo faz uma salvaguarda de Vontade. Independentemente do resultado, torna-se temporariamente imune a esta magia por 1 minuto. Cada ação adicional usada para Conjurar Magia amplia o raio da emanação em 1,5 m. Sucesso: o alvo não é afetado. Falha: estupefato 2. Falha crítica: confuso. Elevada (+3): o raio inicial aumenta em 1,5 m.',
 'Uma a três ações; Vontade evita estupefato 2 ou confusão por 1 rodada. Ações extras ampliam a área; cada alvo fica imune por 1 minuto.',area={'tipo':'emanacao','raio':1.5},salvaguarda='vontade',duracaoRodadas=1)
add('anatomia-incomum','Anatomia Incomum','unusual anatomy',5,263,2,['ocultista'],['manuseio','polimorfia'],
 'Duração: 1 minuto. Você transforma carne e órgãos em uma amálgama bizarra de pele reluzente, escamas ásperas, tufos de pelos e protuberâncias tumorais. Recebe resistência 10 a dano de precisão e resistência 10 ao dano adicional de acertos críticos. Se a resistência superar o dano adicional, ela reduz esse adicional a zero, mas não reduz o dano normal do ataque. Recebe visão no escuro. Ácido exsuda de sua pele: toda criatura que o acerta com ataque desarmado ou arma corpo a corpo sem alcance sofre 2d6 de ácido. Elevada (+2): as resistências aumentam em 5 e o dano de ácido aumenta em 1d6.',
 'Por 1 minuto, visão no escuro e resistência a precisão e dano extra de críticos; acertá-lo de perto causa ácido ao agressor.',mecanica={'resistenciaPrecisao':10,'resistenciaDanoExtraCritico':10,'retaliacaoAcido':'2d6','duracaoRodadas':10})
add('asas-angelicais','Asas Angelicais','angelic wings',3,263,2,['divina'],['concentracao','luz','manuseio'],
 'Duração: 3 rodadas. Asas de pura luz se estendem de suas costas, concedendo Deslocamento de voo igual ao seu Deslocamento. As asas emitem luz intensa em um raio de 9 m. Se ainda estiver voando quando a duração terminar, flutua até o chão como em Pouso Suave. Elevada (5ª): a duração aumenta para 1 minuto.',
 'Voo igual ao seu Deslocamento e luz intensa por 3 rodadas; na 5ª graduação dura 1 minuto. Ao terminar, pousa suavemente.',mecanica={'voo':'deslocamento','luzIntensaRaio':9,'duracaoRodadas':3,'elevacaoDuracao':{'ranque':5,'rodadas':10}})
add('marca-celestial','Marca Celestial','celestial brand',5,263,2,['divina'],['maldicao','manuseio'],
 'Alcance: 9 m. Alvo: 1 criatura profana. Duração: 1 rodada. Um símbolo flamejante aparece no alvo, amaldiçoando-o a enfrentar a justiça divina. Você e seus aliados recebem +1 de estado em jogadas de ataque e testes de perícia contra ele. Sempre que uma criatura sagrada lhe causar dano, causa mais 1d4 de dano espiritual. Depois, o alvo fica temporariamente imune por 1 minuto. Elevada (+2): o dano espiritual aumenta em 1.',
 'Marca um alvo profano por 1 rodada: +1 em ataques e perícias contra ele; dano de criaturas sagradas recebe mais 1d4 espiritual.',mecanica={'bonusAtaquePericia':{'tipo':'estado','valor':1},'danoEspiritualExtra':'1d4','elevacaoDanoFixo':{'intervalo':2,'valor':1},'duracaoRodadas':1})
add('pantano-da-preguica','Pântano da Preguiça','swamp of sloth',3,264,[1,2,3],['divina'],['concentracao','manuseio','olfativo'],
 'Alcance: 36 m. Área: explosão de 1,5 m ou maior. Defesa: Fortitude básica. Duração: 1 minuto. O chão vira um pântano fétido e terreno difícil. A lama se anima em minúsculas bestas de lodo de aparência demoníaca. Não funcionam como criaturas normais, mas enxameiam sobre quem está no pântano e exalam um fedor nocivo. O pântano causa 1d6 de veneno às criaturas que terminarem seu turno na área, com salvaguarda básica de Fortitude. Cada ação adicional usada na conjuração aumenta o raio da explosão em 1,5 m. Elevada (+2): o dano aumenta em 1d6 e o raio inicial aumenta em 1,5 m.',
 'Terreno difícil por 1 minuto; quem termina o turno nele sofre 1d6 de veneno com Fortitude básica. Ações extras ampliam a área.',area={'tipo':'explosao','raio':1.5},salvaguarda='fortitude',mecanica={'dano':'1d6','tipo':'veneno','elevacao':{'intervalo':2,'dados':1},'gatilho':'fim-do-turno-na-area'})
add('ira-ctonica','Ira Ctônica','chthonian wrath',5,264,2,['divina'],['concentracao','manuseio'],
 'Área: cone de 18 m. Defesa: Reflexos básico. Você evoca a energia de uma região das Fendas Exteriores. Role 1d4 para determinar um tipo de energia e um tipo físico: 1, Céus, relâmpagos e detritos voadores, contundente e eletricidade; 2, Profundezas, ácido e conchas demoníacas, ácido e cortante; 3, Congelada, ar gelado e gelo, contundente e frio; 4, Vulcânica, rochas vulcânicas pontiagudas e magma, fogo e perfurante. Cada criatura no cone sofre 4d6 de cada um dos dois tipos, totalizando 8d6, com Reflexos básico. Elevada (+1): o dano de cada tipo aumenta em 1d6.',
 'Cone de 18 m causa 8d6 em dois tipos escolhidos por 1d4; Reflexos básico. Cada graduação extra acrescenta 1d6 de cada tipo.',area={'tipo':'cone','comprimento':18},salvaguarda='reflexos',mecanica={'tabelaTipos':[['contundente','eletricidade'],['acido','cortante'],['contundente','frio'],['fogo','perfurante']],'dadosPorTipo':'4d6','elevacaoPorTipo':'1d6'})
add('abracar-o-abismo','Abraçar o Abismo','embrace the pit',3,264,2,['divina'],['concentracao','morfo'],
 'Duração: 1 minuto. Chifres de diabo brotam de seu crânio e a pele adquire características do diabo responsável por sua linhagem diabólica. Você recebe resistência 5 a fogo e veneno e resistência 1 a dano físico, exceto prata. Elevada (+2): a resistência a fogo e veneno aumenta em 5 e a resistência a dano físico, exceto prata, aumenta em 2.',
 'Por 1 minuto, resistência 5 a fogo e veneno e resistência 1 a dano físico, atravessada por prata.',mecanica={'resistencias':[{'tipo':'fogo','valor':5},{'tipo':'veneno','valor':5},{'tipo':'fisico','valor':1,'exceto':['prata']}],'duracaoRodadas':10})
add('coluna-de-fogo-infernal','Coluna de Fogo Infernal','hellfire plume',5,264,2,['divina'],['concentracao','fogo','manuseio','espirito'],
 'Alcance: 18 m. Área: cilindro de 3 m de raio e 18 m de altura. Defesa: Reflexos básico. Você invoca uma coluna de fogo infernal que irrompe de baixo, causando 4d6 de fogo e 4d6 espiritual. Elevada (+1): tanto o dano de fogo quanto o espiritual aumentam em 1d6.',
 'Cilindro de 3 m de raio causa 4d6 de fogo e 4d6 espiritual, com Reflexos básico; cada graduação extra aumenta ambos em 1d6.',area={'tipo':'cilindro','raio':3,'altura':18},salvaguarda='reflexos',mecanica={'danos':[{'tipo':'fogo','formula':'4d6'},{'tipo':'espiritual','formula':'4d6'}],'elevacaoPorTipo':'1d6'})
add('sopro-de-dragao','Sopro de Dragão','dragon breath',3,264,2,['arcana','divina','ocultista','primal'],['concentracao','manuseio'],
 'Área: cone de 9 m. Defesa: Reflexos básico. Você expele energia pela boca, causando 5d6 de dano com salvaguarda básica de Reflexos. O tipo depende da tradição do dragão que influenciou sua linhagem: arcana, força; divina, espiritual; ocultista, mental; primal, fogo. Elevada (+1): o dano aumenta em 2d6.',
 'Cone de 9 m causa 5d6 com Reflexos básico; o tipo vem da tradição da linhagem. Cada graduação extra acrescenta 2d6.',area={'tipo':'cone','comprimento':9},salvaguarda='reflexos',mecanica={'dano':'5d6','elevacao':'2d6','tiposPorTradicao':{'arcana':'forca','divina':'espiritual','ocultista':'mental','primal':'fogo'}})
add('asas-de-dragao','Asas de Dragão','dragon wings',5,265,2,['arcana','divina','ocultista','primal'],['concentracao','manuseio','morfo'],
 'Duração: 1 minuto. Asas coriáceas brotam de suas costas, concedendo Deslocamento de voo de 18 m ou igual ao seu Deslocamento, o que for maior. Se ainda estiver voando quando a magia terminar, flutua até o chão com os efeitos de Pouso Suave. Elevada (8ª): a duração aumenta para 10 minutos.',
 'Voo de pelo menos 18 m por 1 minuto; na 8ª graduação dura 10 minutos. Ao terminar, pousa suavemente.',mecanica={'vooMinimo':18,'voo':'maximo-entre-18-e-deslocamento','duracaoRodadas':10,'elevacaoDuracao':{'ranque':8,'rodadas':100}})
add('movimento-elemental','Movimento Elemental','elemental motion',3,265,2,['primal'],['concentracao','manuseio'],
 'Duração: 1 minuto. Você usa seu elemento para se impulsionar; a magia recebe o traço desse elemento. Ar: voo igual ao seu Deslocamento. Terra: escavação de 3 m. Fogo: voo igual ao seu Deslocamento. Metal: escavação de 3 m. Água: natação igual ao seu Deslocamento e pode respirar debaixo d’água. Madeira: escalada igual ao seu Deslocamento. Elevada (6ª): também recebe +3 m de estado em seus Deslocamentos. Elevada (9ª): esse bônus de estado aumenta para +6 m.',
 'Por 1 minuto, seu elemento concede voo, escavação, natação ou escalada. Na 6ª e 9ª graduações, recebe bônus de velocidade.',mecanica={'movimentosPorElemento':{'ar':'voo','terra':'escavacao','fogo':'voo','metal':'escavacao','agua':'natacao','madeira':'escalada'},'escavacao':3,'bonusEstadoPorRanque':{'6':3,'9':6}})
add('explosao-elemental','Explosão Elemental','elemental blast',5,265,2,['primal'],['concentracao','manuseio'],
 'Alcance: 9 m, somente para explosão. Área: explosão de 3 m de raio, cone de 9 m ou linha de 18 m. Defesa: Reflexos básico. Você reúne energia elemental e a libera em uma das três formas à escolha, causando 8d6 de dano. O tipo do dano corresponde à influência elemental de sua linhagem, por exemplo cortante para ar e fogo para fogo. A magia recebe o traço do elemento. Elevada (+1): o dano aumenta em 2d6.',
 'Escolha explosão, cone ou linha; causa 8d6 do elemento da linhagem com Reflexos básico e mais 2d6 por graduação extra.',salvaguarda='reflexos',mecanica={'dano':'8d6','elevacao':'2d6','formas':[{'tipo':'explosao','raio':3,'alcance':9},{'tipo':'cone','comprimento':9},{'tipo':'linha','comprimento':18}]})
add('desaparecimento-feerico','Desaparecimento Feérico','fey disappearance',3,265,1,['primal'],['manuseio'],
 'Duração: até o fim do seu próximo turno. Você fica invisível e ignora terreno difícil natural, como vegetação rasteira. Qualquer ação hostil que realizar encerra essa invisibilidade, mas continua ignorando terreno difícil natural. Elevada (5ª): realizar uma ação hostil não encerra a invisibilidade.',
 'Invisibilidade e ignora terreno difícil natural até o fim do próximo turno. Ações hostis encerram a invisibilidade, salvo na 5ª graduação.',mecanica={'invisivel':True,'ignoraTerrenoDificilNatural':True,'invisibilidadeMantidaComHostilidadeRanque':5})
add('encanto-feerico','Encanto Feérico','fey glamour',5,265,2,['primal'],['concentracao','ilusao','manuseio'],
 'Alcance: 9 m. Área: explosão de 9 m ou alvos: até 10 criaturas voluntárias. Duração: 10 minutos. Você invoca encantos feéricos para revestir a área ou os alvos com ilusões. Escolha o efeito de Cena Ilusória na área ou Disfarce Ilusório nas criaturas. Use o efeito da magia escolhida elevada a uma graduação uma unidade inferior à de Encanto Feérico, mas empregue o alcance e a duração de Encanto Feérico.',
 'Por 10 minutos, cria uma Cena Ilusória em uma área ou Disfarce Ilusório em até 10 voluntários, com graduação uma abaixo desta magia.',mecanica={'magiasDelegadas':['cena-ilusoria','disfarce-ilusorio'],'ranqueDelegado':'ranque-1','duracaoRodadas':100})
add('semblante-horrendo','Semblante Horrendo','horrific visage',3,265,2,['ocultista'],['concentracao','emocao','medo','ilusao','manuseio','mental','visual'],
 'Área: emanação de 9 m de raio. Defesa: Vontade. Você transforma brevemente suas feições no rosto horrendo de uma bruxa monstruosa, assustando os inimigos. Cada inimigo na área faz uma salvaguarda de Vontade. Sucesso: não é afetado. Falha: assustado 1. Falha crítica: assustado 2. Elevada (5ª): sucesso impõe assustado 1; falha, assustado 2; falha crítica, assustado 3 e fugindo por 1 rodada. Sucesso crítico continua sem efeito.',
 'Vontade evita assustado 1 ou 2; na 5ª graduação, até um sucesso causa medo e a falha crítica também faz fugir.',area={'tipo':'emanacao','raio':9},salvaguarda='vontade',mecanica={'resultados':{'sucesso':{},'falha':{'assustado':1},'falhaCritica':{'assustado':2}},'elevacao5':{'sucesso':{'assustado':1},'falha':{'assustado':2},'falhaCritica':{'assustado':3,'fugindoRodadas':1}}})
add('voce-e-meu','Você É Meu','you\'re mine',5,266,2,['ocultista'],['concentracao','emocao','incapacitacao','manuseio','mental'],
 'Alcance: 9 m. Alvo: 1 criatura. Defesa: Vontade. Duração: 1 rodada. Você manipula as emoções do alvo, podendo controlá-lo por um breve instante. Sucesso crítico: não é afetado. Sucesso: atordoado 1. Falha: no próximo turno do alvo, ele fica atordoado 1 e você o controla parcialmente, obrigando-o a realizar uma única ação à sua escolha; se ainda tiver ações disponíveis, age normalmente. Falha crítica: controlado por 1 rodada. Elevada (7ª): em falha, fica controlado por 1 rodada; em falha crítica, fica controlado por até 1 minuto, com nova salvaguarda de Vontade ao fim de cada turno. Um sucesso encerra a magia.',
 'Vontade determina atordoamento, uma ação imposta ou controle por 1 rodada. Na 7ª graduação, a falha crítica permite controle por até 1 minuto.',salvaguarda='vontade',mecanica={'resultados':{'sucesso':{'atordoado':1},'falha':{'atordoado':1,'acaoImposta':1},'falhaCritica':{'controladoRodadas':1}}})
add('estender-magia-sanguinea','Estender Magia Sanguínea','extend blood magic',3,266,1,['arcana'],['concentracao','modificador-de-magia'],
 'Você usa a energia arcana de seu sangue para estender a magia que ela concede. Se sua próxima ação for Conjurar Magia que conceda um efeito de magia sanguínea com duração de pelo menos 1 rodada, você ou um alvo recebe esse efeito por uma rodada adicional. Só pode manter um efeito de magia sanguínea estendido de cada vez.',
 'Se a próxima ação conjurar uma magia que ativa magia sanguínea, estende um efeito com duração de pelo menos 1 rodada em mais 1 rodada.',mecanica={'duracaoExtraRodadas':1,'limiteEfeitosEstendidos':1,'exigeProximaAcaoConjurar':True})
add('contramedida-arcana','Contramedida Arcana','arcane countermeasure',5,266,'reacao',['arcana'],['manuseio'],
 'Gatilho: uma criatura visível no alcance Conjura Magia. Alcance: 36 m. Alvo: a magia conjurada pela criatura que acionou a reação. Você enfraquece essa magia, tornando mais fácil defender-se dela. Reduza sua graduação em 1; os alvos recebem +2 de estado em salvaguardas, testes de perícia, CA ou CDs contra ela. Não pode reduzir a graduação abaixo da mínima da magia: uma Nevasca Uivante de 5ª graduação permanece na 5ª, mas uma Bola de Fogo de 5ª vira de 4ª. Os alvos recebem os demais benefícios mesmo quando a graduação não pode ser reduzida.',
 'Reação a uma conjuração visível a até 36 m: reduz a graduação em 1, respeitando o mínimo, e concede +2 nas defesas dos alvos.',mecanica={'reducaoRanque':1,'respeitaRanqueMinimo':True,'bonusDefesas':{'tipo':'estado','valor':2}})
add('drenar-vida','Drenar Vida','drain life',3,266,1,['divina'],['manuseio','vazio'],
 'Alcance: 9 m. Alvo: 1 criatura viva. Defesa: Fortitude básica. Você fecha a mão e puxa a energia vital de outra criatura para si. Causa 3d4 de vazio, com salvaguarda básica de Fortitude. Recebe PV temporários iguais ao dano que o alvo sofre, depois da salvaguarda e de qualquer efeito de magia sanguínea aplicável. Se o alvo tinha menos PV que o dano causado, recebe somente seus PV restantes como PV temporários. Eles duram 1 minuto. Elevada (+1): o dano aumenta em 1d4.',
 'Causa 3d4 de vazio com Fortitude básica; ganha PV temporários iguais ao dano efetivo, limitados pelos PV que o alvo tinha.',salvaguarda='fortitude',mecanica={'dano':'3d4','tipo':'vazio','elevacao':'1d4','pvTemporarios':'minimo-entre-dano-final-e-pv-anteriores-alvo','duracaoRodadas':10})
add('sepultura-agarradora','Sepultura Agarradora','grasping grave',5,266,2,['divina'],['concentracao','manuseio'],
 'Alcance: 18 m. Área: raio de 6 m no chão. Defesa: Reflexos. Centenas de braços esqueléticos irrompem do chão, arranhando as criaturas e tentando prendê-las. Os braços causam 6d6 de cortante. Cada criatura na área faz uma salvaguarda de Reflexos. Sucesso crítico: não é afetada. Sucesso: metade do dano. Falha: dano completo e −3 m de circunstância em seus Deslocamentos por 1 rodada. Falha crítica: dano dobrado e imobilizada por 1 rodada ou até Escapar. Elevada (+1): o dano aumenta em 2d6.',
 'Área no chão causa 6d6 cortante; Reflexos reduz o dano. Falha diminui velocidade e falha crítica imobiliza por 1 rodada ou até Escapar.',area={'tipo':'explosao-no-chao','raio':6},salvaguarda='reflexos',mecanica={'dano':'6d6','tipo':'cortante','elevacao':'2d6','falha':{'penalidadeMovimento':{'tipo':'circunstancia','valor':-3}},'falhaCritica':{'imobilizadoRodadas':1,'terminaAoEscapar':True}})
assert len(rows)==20
assert len({r['id'] for r in rows})==20
out=pathlib.Path(__file__).with_name('focos-avancados-qa.json')
out.write_text(json.dumps({'magias':rows,'lacunas':[{'categoria':'automacao-focos-avancados','descricao':'Os vinte focos avançados das linhagens têm texto português revisado e metadados; permanecem somente para consulta até receberem executores de combate e testes independentes.'}]},ensure_ascii=False,indent=2)+'\n')
print('20 focos avançados traduzidos integralmente; nenhuma automação presumida.')
