#!/usr/bin/env python3
"""Treze rituais PC2: tradução manual completa das regras nas páginas físicas267–272.
Textos de ambientação foram reescritos em português; fórmulas e exceções conservadas.
"""
import json,pathlib
rows=[]
def add(id,name,en,rank,page,text,summary,**meta):
 rows.append(dict(id=id,nome=name,nomeOriginal=en,ranque=rank,pagina=page,paginaPdf=page,paginaImpressa=page-1,fonte='player-core-2',tipo='ritual',revisao='revisado',somenteConsulta=True,descricao=text,resumo=[summary],automatizacao={'estado':'executor-ritual-pendente'},**meta))
add('projecao-astral','Projeção Astral','astral projection',5,267,
 'Incomum. Conjuração: 1 hora. Custo: uma gema por alvo de valor igual a nível do alvo, mínimo 1, × 5 po. Conjuradores secundários: 2. Teste primário: Arcanismo ou Ocultismo, mestre. Testes secundários: Arcanismo ou Ocultismo, o que não foi usado como primário, e Sobrevivência. Alcance: toque. Alvos: você e até 5 criaturas voluntárias. Duração: veja o texto.\n\nProjeta as essências espirituais no Plano Astral, deixando corpos físicos imóveis, inconscientes e em estase no plano de origem. As formas astrais podem explorar indefinidamente. Durante a conjuração, os conjuradores devem manter contato físico entre si em círculo; todos os alvos são escolhidos entre eles. A forma astral duplica o alvo e tudo que carrega. Tudo que acontece a um item duplicado também acontece ao original: usar, gastar, destruir, perder ou doar a cópia faz o original desaparecer de sua posse. Qualquer alvo pode usar uma ação para Dispensar sua forma astral e retornar imediatamente ao corpo. Ao Dispensar a própria forma, o conjurador primário pode também Dispensar todas as demais na mesma ação. Os outros alvos não conseguem navegar no Astral sem o primário; se separados, devem esperar seu retorno ou Dispensar as próprias formas. As formas astrais desaparecem quando o ritual termina.\n\nA forma astral e o corpo ficam ligados por um cordão de prata incorpóreo, visível apenas no Astral, que funciona como condutor e linha de segurança. É quase indestrutível; se cortado, ambas as formas morrem imediatamente. Se uma força externa interromper o ritual, como Dissipar Magia contra qualquer das formas, o alvo retorna imediatamente ao corpo sem dano. Se a forma astral morrer, o cordão o devolve ao corpo e ele deve fazer Fortitude contra a mesma CD do teste primário. Falha: morre. Sucesso: fica desajeitado 2, drenado 2, condenado 2 e enfraquecido 2 por 1 semana; essas condições não podem ser removidas nem reduzidas antes do fim da semana. O corpo fica em animação suspensa; destruí-lo mata a criatura e faz sua forma astral desaparecer. O ritual só projeta parte da consciência. Viajar fisicamente ao Astral, por exemplo para alcançar Planos Exteriores, exige magia como Teleporte Interplanar.\n\nSucesso crítico: todos os alvos podem navegar independentemente; seus cordões são mais fortes e concedem +4 de circunstância na Fortitude para evitar morrer se a forma astral morrer. Sucesso: projeta os alvos como descrito. Falha: não consegue projetá-los. Falha crítica: separar espíritos e corpos causa uma catástrofe; todos os conjuradores ficam condenado 1, são reduzidos a 0 PV e começam a morrer.',
 'Projeta até seis participantes no Astral com corpos em estase e equipamento vinculado; Dispensar retorna ao corpo. Cordão cortado ou forma morta pode causar morte real.',custoPorNivelAlvo=5,conjuradoresSecundarios=2)
add('clone','Clone','clone',9,267,
 'Raro. Conjuração: 7 dias. Custo: materiais laboratoriais e reagentes raros de nível do alvo, mínimo 1, × 100 po. Conjuradores secundários: 3. Teste primário: Manufatura, lendário. Testes secundários: Arcanismo, Medicina e Ocultismo. Alcance: 3 m. Alvo: 1 criatura viva voluntária de até 20º nível.\n\nVocê coleta cabelo, unhas, pele e sangue do alvo, que precisa permanecer presente durante todo o ritual e pode ser conjurador. Usa as amostras para cultivar uma cópia fisicamente idêntica, destinada a abrigar sua alma depois da morte. É necessário um laboratório de alquimista expandido ou equipamento superior. Depois de concluir o ritual, a cópia cresce no laboratório por 2d4 meses. Não exige participação direta nesse período, mas é preciso impedir interferências e interrupções ou o ritual falha. Ao ficar pronta, a alma entra na cópia assim que o original morrer, ou imediatamente se já morreu durante os meses de crescimento, desde que esteja livre e queira retornar. Se Pharasma decidiu que chegou sua hora, ou a alma está presa ou não quer voltar, a cópia fica vazia até remover o impedimento. Enquanto vazia, deve ser preservada em equipamento alquímico adequado para não apodrecer.\n\nSucesso crítico: o clone é criado; quando a alma ocupar o corpo, fica desajeitado 1, drenado 1, condenado 1 e enfraquecido 1 por 1 semana, sem poder remover ou reduzir essas condições antes do fim desse prazo. Sucesso: igual, mas cada condição tem valor 2. Falha: não forma o clone. Falha crítica: o clone parece funcionar, mas algo deu terrivelmente errado; ao completar o crescimento, não abriga a alma e em vez disso contém uma inteligência malévola ou criatura invasora, como um demônio poderoso.',
 'Cultiva um corpo de reserva em 2d4 meses para uma alma livre e voluntária retornar após a morte. Exige laboratório e preservação; resultados impõem condições por uma semana.',custoPorNivelAlvo=100,conjuradoresSecundarios=3)
add('fachada-fantastica','Fachada Fantástica','fantastic facade',9,268,
 'Raro, ilusão. Conjuração: 1 semana. Custo: tinta mística, véus elaborados e minerais em pó no total de 20.000 po. Conjuradores secundários: 3. Teste primário: Arcanismo ou Ocultismo, lendário. Testes secundários: Enganação; Sociedade ou Sobrevivência; Furtividade. Área: círculo centrado em você de até 1,6 km de raio. Alvos: 1 povoado e seus residentes. Duração: ilimitada.\n\nSobrepõe ilusões permanentes ao povoado, escolhendo aparência, som, toque e cheiro das estruturas, terreno e criaturas presentes na conjuração. Pode alterar estruturas e criaturas existentes e adicionar estruturas ou criaturas ilusórias. Pode, por exemplo, tornar tudo verde, criar uma floresta ilusória que esconda o povoado ou fazer ruínas vazias parecerem habitadas e intactas. Ao criar a fachada, determina quais ilusões são estáticas, limitadas ao movimento natural básico como bandeiras, e quais seguem programação básica, como um desfile diário. Não pode alterar as programações depois, salvo o benefício de sucesso crítico. Pode disfarçar criaturas como Disfarce Ilusório de 3ª graduação. Se uma criatura afetada sair da área, suas ilusões desaparecem depois de 1 dia. Na conjuração decide se recém-chegados são disfarçados e se isso ocorre imediatamente ou após um período definido de até 1 semana.\n\nQuem interagir de modo que possa sugerir ou revelar a ilusão, como pintar um edifício afetado ou escalar uma estrutura ilusória, pode tentar desacreditá-la. As ilusões são inofensivas: lava ilusória não causa dano e espinhos ilusórios não perfuram ninguém. Sucesso crítico: cria a fachada e pode alterar as programações gastando 1 dia para reprogramá-las. Sucesso: cria a fachada descrita. Falha: não há efeito. Falha crítica: cria ilusões inesperadas e fora de controle, como cores que mudam, odores desagradáveis ou criaturas aparentando esqueletos; desaparecem depois de 1 mês. Elevado (10ª): custo 100.000 po e raio de até 8 km.',
 'Ilusão permanente cobre um povoado inteiro e seus moradores, com aparência e programas definidos. Interações permitem desacreditar; as ilusões não causam dano.',custo=20000,conjuradoresSecundarios=3)
add('bebida-fortificante','Bebida Fortificante','fortifying brew',5,268,
 'Incomum. Conjuração: 4 horas. Custo: ingredientes de alta qualidade e equipamento de preparo de 25 po. Conjuradores secundários: 1. Teste primário: Manufatura, Natureza ou Sociedade, especialista. Testes secundários: Saber de Álcool ou relacionado, Manufatura ou Sociedade. Alcance: 6 m.\n\nPrepara uma bebida restauradora, como chá revigorante, cerveja refrescante ou tônico alquímico estimulante. O ritual acelera processos naturais como fermentação. Ao fim das primeiras 3 horas, há bebida suficiente para até 10 pessoas, qualquer das quais pode ser o conjurador secundário. Ela deve ser consumida durante a hora seguinte; se alcoólica, não há perigo de embriaguez. Terminada essa hora, o primário e secundário fazem os testes. Sucesso crítico: em cada bebedor, para cada aflição ou condição relevante, aplica Purificar Aflição, Clarear Mente e Corpo Sadio de 4ª graduação. Usa o modificador do teste de perícia primário como modificador de neutralização. Cada pessoa também recebe 20 PV temporários por 12 horas e +2 de estado em salvaguardas contra doenças e venenos por 12 horas. Sucesso: como crítico, mas apenas 10 PV temporários e sem bônus nas salvaguardas. Falha: a bebida deixa gosto azedo e não beneficia. Falha crítica: vira algo próximo de veneno; os bebedores ficam enjoado 4 e não podem reduzir a condição por 12 horas. Elevado (+1): PV temporários aumentam em 2, ou em 4 no sucesso crítico.',
 'Bebida para até 10 pessoas tenta neutralizar aflições e concede PV temporários por 12 horas. Sucesso crítico também protege contra doença e veneno; falha crítica causa enjoo.',custo=25,conjuradoresSecundarios=1)
add('chamado-de-reuniao','Chamado de Reunião','gathering call',7,268,
 'Raro, teleporte. Conjuração: 7 dias. Custo: óleos raros e minerais em pó de 5.000 po. Conjuradores secundários: 2. Teste primário: Arcanismo ou Ocultismo, especialista, secreto. Testes secundários: Arcanismo ou Ocultismo, o que não foi primário, e Sociedade. Alcance: 6 m. Alvos: até 7 criaturas voluntárias de até 14º nível. Duração: 1 ano.\n\nVincula você e aliados ao local seguro onde o ritual é realizado, chamado santuário, permitindo voltar depois ao pronunciar uma palavra. Sucesso: estabelece o vínculo. Qualquer participante pode Dispensar o ritual; quando faz isso, todos os participantes podem retornar imediatamente de qualquer distância, desde que estejam no mesmo plano do santuário. Chegam às posições que ocupavam na conjuração. Ao ouvir a palavra, os outros participantes sabem dela e escolhem individualmente retornar ou não. O ritual termina imediatamente. Falha: não forma o vínculo, e os conjuradores sabem que falhou. Falha crítica: cria acidentalmente vínculo com um local em outro plano, sem os conjuradores saberem; ao invocar a palavra, todos são transportados a esse local extraplanar. Elevado (+1): custo aumenta em 5.000 po, pode alvejar mais uma criatura e o nível máximo do alvo aumenta em 2.',
 'Vínculo de um ano com um santuário: qualquer participante pode chamar os demais de volta no mesmo plano, uma vez. Falha crítica troca o destino por outro plano.',custo=5000,conjuradoresSecundarios=2)
add('vinculo-do-coracao','Vínculo do Coração','heartbond',2,269,
 'Incomum. Conjuração: 1 hora. Custo: bebidas sacramentais e anéis ou símbolos correspondentes de 20 po por conjurador secundário. Conjuradores secundários: 2 ou mais. Teste primário: Natureza ou Religião, especialista. Testes secundários: Diplomacia e Sociedade. Alcance: 6 m.\n\nCria um vínculo mágico entre duas ou mais criaturas voluntárias, os conjuradores secundários, que devem sentir afeto verdadeiro entre si. Cada uma recebe um anel, amuleto ou símbolo similar. Perde os efeitos quando não usa o símbolo; destruir um dos símbolos rompe o vínculo. Criaturas vinculadas com sucesso podem participar de versão elevada sem novos testes, cumprindo o tempo e pagando a diferença dos custos. Pode estar sob vários Vínculos do Coração simultaneamente. Sucesso crítico: uma vez por dia, cada vinculada pode usar atividade de duas ações com concentração para conhecer o estado atual de outra: direção, distância e condições. Também pode conjurar Mensagem como magia divina inata à vontade, mas só para outra participante. Sucesso: como crítico, sem Mensagem inata. Falha: sem efeito. Falha crítica: energia discordante; por 1 semana, cada secundário fica desajeitado 2 e estupefato 2 sempre que estiver a até 9 m de outro secundário. Elevado (6ª): custo 300 po por secundário. No sucesso, participantes secundários ganham permanentemente efeitos de Telepatia de 6ª graduação, mas apenas entre si.',
 'Afeto e símbolos sustentam um vínculo que informa direção, distância e condições uma vez ao dia; crítico também concede Mensagem. Na 6ª graduação, telepatia entre participantes.',custoPorConjuradorSecundario=20,conjuradoresSecundariosMinimos=2)
add('seduzir-a-mente','Seduzir a Mente','inveigle',2,269,
 'Incomum, mental. Conjuração: 1 dia. Custo: óleos raros de 10 po × nível do alvo. Teste primário: Arcanismo, Ocultismo ou Religião, especialista. Alcance: 3 m. Alvo: 1 criatura de nível não superior a duas vezes a graduação do ritual. Duração: 1 ano ou até Dispensar.\n\nConquista a mente do alvo, que o vê como amigo próximo e confiável e considera suas sugestões razoáveis. Fica prestativo e se esforça para ajudar, dentro dos limites normais de uma criatura prestativa. Se pedir algo inteiramente contrário à natureza dela ou desnecessariamente nocivo a ela ou seus interesses, recusa e pode fazer Vontade para encerrar o efeito. O tempo e alcance tornam difícil realizar o ritual salvo se o alvo for voluntário, talvez enganado sobre o efeito, ou restringido. Se não quiser aceitar o ritual, pode fazer Vontade para anulá-lo. Sucesso crítico: ritual funciona e o alvo sofre −4 de estado em Vontade para encerrar o efeito. Sucesso: funciona. Falha: falha. Falha crítica: o alvo passa a odiá-lo e fica hostil pela duração. Elevado (6ª): pode estar a até 1,6 km durante toda a conjuração, se possuir parte do corpo do alvo para misturar aos óleos. Custo básico 100 po. Duração passa a 1 semana para sangue, cabelo, escamas e similares; ou 1 mês para uma mão ou parte corporal de tamanho comparável.',
 'Torna o alvo prestativo por até um ano, com salvaguardas para resistir ou encerrar quando pedidos violam sua natureza. Na 6ª graduação funciona à distância com amostra corporal.',custoPorNivelAlvo=10)
add('zeladores-fantasmagoricos','Zeladores Fantasmagóricos','phantasmal custodians',3,269,
 'Incomum. Conjuração: 1 dia. Custo: óleos raros, sais e ervas de 15 po. Conjuradores secundários: 2. Teste primário: Arcanismo ou Ocultismo, especialista. Testes secundários: Arcanismo ou Ocultismo, o que não foi primário, e Diplomacia. Área: 30 m × 30 m, até 6 m de altura. Duração: 1 ano.\n\nAdaptação duradoura de Servo Fantasmagórico cria entidades para tarefas básicas em local fixo. Sucesso crítico: cria seis servos fantasmagóricos. Não precisa se concentrar neles e não são asseclas invocados. Pode gastar uma ação de concentração para mandar um deles executar tarefa básica, que continua até receber nova ordem. Sucesso: cria três servos. Falha: não cria nenhum. Falha crítica: cria seis servos hostis que podem dar Golpes de punho com bônus de ataque igual ao modificador de perícia do teste primário, causando 1d6 de força. Atacam você e aliados e tentam destruir seus objetos na área. Elevado (6ª): se destruídos, os servos se reformam na manhã seguinte; custo 30 po.',
 'Cria três ou seis ajudantes por um ano em uma área fixa; uma ação comanda tarefas. Falha crítica gera servos hostis, e a 6ª graduação permite regenerá-los.',custo=15,conjuradoresSecundarios=2)
add('reencarnar','Reencarnar','reincarnate',3,270,
 'Incomum. Conjuração: 4 horas. Custo: ervas raras de nível do alvo, mínimo 1, × 25 po. Conjuradores secundários: 2. Teste primário: Natureza, especialista. Testes secundários: Ocultismo e Religião. Alcance: 3 m. Alvo: 1 criatura morta de até 8º nível.\n\nInvoca a alma e tenta encarná-la em corpo novo. Basta pequena parte dos restos, desde que integrasse o corpo original no momento da morte. O alvo deve ter morrido na última semana. Se Pharasma decidiu que chegou sua hora, a alma está presa ou não quer retornar, o ritual falha automaticamente; descobre isso depois de sucesso em Religião e pode encerrá-lo sem pagar o custo. Se funcionar, a ancestralidade do novo corpo é aleatória: 1–14 em 1d20, comum; 15–20, incomum ou rara. O mestre escolhe possibilidades locais e sorteia. Substitui PV, tamanho, Deslocamentos, melhorias e falhas de atributos, traços e habilidades especiais de ancestralidade pelos da nova. Perde herança e talentos ancestrais antigos e escolhe substitutos da nova ancestralidade. Biografia, características de classe e idiomas não mudam.\n\nSucesso crítico: reencarna em corpo adulto, com PV completos e as mesmas magias preparadas que tinha ao morrer. Sucesso: como crítico, mas 1 PV, sem magias preparadas e desajeitado 2, drenado 2 e enfraquecido 2 por 1 semana, sem remover ou reduzir essas condições antes do prazo. Falha: não reencarna. Falha crítica: alma fica presa em animal não inteligente escolhido pelo mestre, de nível não superior ao alvo. Enquanto presa, Inteligência é 1, modificador −5, e não pode usar suas habilidades. Elevado (4ª): nível máximo 10, custo nível mínimo 1 × 40 po. (5ª): máximo 12, × 75 po. (6ª): máximo 14, × 125 po, morte no último mês. (7ª): máximo 16, × 200 po, morte no último mês. (8ª): máximo 18, × 300 po, morte no último ano. (9ª): máximo 20, × 600 po, morte na última década.',
 'Devolve uma alma livre e voluntária em corpo de ancestralidade sorteada, substituindo herança e talentos ancestrais. Elevação amplia nível, tempo desde a morte e custo.',custoPorNivelAlvo=25,conjuradoresSecundarios=2)
add('descanso-eterno','Descanso Eterno','rest eternal',4,271,
 'Incomum, espírito. Conjuração: 1 dia. Custo: óleos raros para ungir o corpo de nível do alvo, mínimo 1, × 25 po. Conjuradores secundários: 2. Teste primário: Religião, especialista. Testes secundários: Ocultismo e Religião. Alcance: 6 m. Alvo: 1 criatura morta.\n\nApela a deuses, espíritos e seres estranhos para impedir que um espírito retorne. Um espírito que não quiser a restrição pode fazer Vontade; em sucesso crítico, faz você acreditar que o ritual funcionou. Não afeta morto-vivo nem alma que não esteja na vida após a morte. Sucesso crítico: isola o espírito; tentativas de comunicar-se, ressuscitar, torná-lo morto-vivo ou perturbar o pós-vida falham salvo se a graduação de neutralização do efeito for ao menos 2 superior ao ritual, ou se vier de artefato ou divindade. Retornar a criatura à vida encerra as restrições. Sucesso: igual, mas basta graduação de neutralização superior à do ritual. Falha: sem efeito. Falha crítica: espíritos ficam furiosos; todos os conjuradores ficam condenado 1 por 1 semana.',
 'Protege uma alma morta contra comunicação, ressurreição ou animação, salvo efeitos de graduação superior, artefatos ou divindades; um espírito pode resistir.',custoPorNivelAlvo=25,conjuradoresSecundarios=2)
add('duplicata-sombria','Duplicata Sombria','shadow double',4,271,
 'Raro, ilusão. Conjuração: 1 dia. Custo: um objeto pequeno de significado pessoal para o alvo e óleos, minerais e pigmentos raros de 300 po. Conjuradores secundários: 3. Teste primário: Arcanismo ou Ocultismo, mestre, secreto. Testes secundários: Arcanismo, Natureza, Ocultismo, Religião ou Sociedade, a perícia de Recordar Conhecimento sobre a criatura; Manufatura; Enganação. Alvo: 1 criatura viva.\n\nCria cópia ilusória com matéria sombria do Mundo Sombrio, moldada em forma semissólida. A duplicata é criatura de 4º nível sem habilidades especiais; quando precisar rolar ou usar CD, use o valor moderado de monstro, exceto as alterações abaixo. Não tem lembranças específicas, mas pode usar informações fornecidas pelos conjuradores para Personificar o alvo. Parece idêntica e seu modificador de Enganação para personificá-lo é o do secundário que fez Enganação, com +4 de estado. Não tem poderes especiais reais, como sopro de dragão; ilusões simulam esses poderes sem efeito. Contra sopro ilusório, por exemplo, os alvos parecem obter sucesso crítico e não sofrem dano. Pode tentar desacreditar com Percepção contra a CD de Enganação do secundário. Sucesso crítico: cria duplicata assecla sob controle absoluto, com vínculo mental direto; pode usar uma ação para comandá-la à distância. Sucesso: igual, mas sem vínculo mental, exigindo comando verbal ou outro meio. Falha: sem efeito. Falha crítica: cria duplicata que não é sua assecla e é hostil aos conjuradores; tenta destruí-los ou foge para planejar sua ruína.',
 'Cria cópia semissólida de 4º nível que personifica o alvo, sem seus poderes reais. Pode ser assecla controlada ou, na falha crítica, inimiga.',custo=300,conjuradoresSecundarios=3)
add('circulo-de-teleporte','Círculo de Teleporte','teleportation circle',7,271,
 'Incomum, teleporte. Conjuração: 1 dia. Custo: incenso raro, metais preciosos e giz purificado de 500 po. Conjuradores secundários: 2. Teste primário: Arcanismo ou Ocultismo, mestre. Testes secundários: Manufatura e Sobrevivência. Alcance: 6 m. Duração: 1 dia.\n\nCria círculo de 3 m de diâmetro no chão, portal a destino fixado na conjuração, que não pode mudar. O destino deve estar no mesmo plano, a até 1.600 km. Deve identificá-lo precisamente por posição relativa e aparência ou características; também precisa ser círculo de 3 m que não sobreponha estruturas sólidas, embora possa ser perigoso. O secundário de Sobrevivência pode estar no destino em vez da origem. Se ele tiver sucesso lá e o primário tiver sucesso, o resultado do ritual vira sucesso crítico. Qualquer criatura que entrar inteiramente no círculo ativo é teleportada instantaneamente. Alvo involuntário pode fazer Vontade para resistir, repetindo ao fim dos turnos se permanecer no círculo. Funciona normalmente em um sentido; dobrar o custo permite ambos. Sucesso crítico: chega exatamente ao ponto desejado. Sucesso: desvia cerca de 1% da distância, máximo 16 km. Falha: não funciona. Falha crítica: leva a destino aleatório aproximadamente à mesma distância e aumenta muito a chance de outro acidente incomum. Elevado (9ª): custo 2.000 po, duração 1 mês, destino em qualquer lugar do mesmo planeta. (10ª): 10.000 po, duração ilimitada, mesmo planeta.',
 'Portal fixo de um dia entre locais no mesmo plano; custo dobrado permite ida e volta. Sucesso comum desvia o destino; elevação permite permanência e alcance planetário.',custo=500,conjuradoresSecundarios=2)
add('proteger-dominio','Proteger Domínio','ward domain',6,272,
 'Incomum. Conjuração: 1 dia. Custo: incensos, óleos e prata em pó raros de 150 po. Conjuradores secundários: 3. Teste primário: Arcanismo, Natureza ou Ocultismo, mestre. Testes secundários: Saber de qualquer assunto, Sobrevivência e Ladroagem. Área: 30 m × 30 m, até 15 m de altura. Duração: 1 semana.\n\nDurante a conjuração, queima incenso, entoa rezas e traça prata nas entradas para guardar um santuário. Os efeitos abaixo são elevados à graduação do ritual e duram por toda a duração. Portões, portas, janelas e aberturas similares ficam trancados como Trancar. Pode esconder até seis entradas com Objeto Ilusório para parecerem paredes lisas. Magias de vidência não percebem estímulos da área. O domínio tenta neutralizar teleportes de entrada ou saída, incluindo invocações, com modificador igual à CD de salvaguarda do ritual menos 10. Dissipar Magia com sucesso contra um efeito específico remove somente esse efeito, como a tranca de uma janela. Detonar Magia com sucesso encerra o ritual inteiro. Sucesso crítico: cria os efeitos e protege área duas vezes maior. Sucesso: cria os efeitos. Falha: sem efeito. Falha crítica: a área fica armadilhada e hostil a você e aliados de maneira imprevista. Elevado (+1): acrescenta área de 30 m × 30 m por até 15 m de altura, contígua à original.',
 'Guarda área por uma semana com trancas, entradas ilusórias, bloqueio de vidência e tentativas de neutralizar teleportes. Elevação amplia área; crítico dobra cobertura.',custo=150,conjuradoresSecundarios=3)
assert len(rows)==13
pathlib.Path(__file__).with_name('rituais-qa.json').write_text(json.dumps({'rituais':rows,'cobertura':'13 de 13 rituais do índice PC2, páginas físicas267–272. Tradução manual de regras, resultados e elevações; executores pendentes.'},ensure_ascii=False,indent=2)+'\n')
print('13/13 rituais traduzidos; execução ainda não presumida.')
