#!/usr/bin/env python3
"""Talentos gerais e de perícia do PC2, páginas físicas 227–236.

Tradução editorial manual do texto do PDF fornecido. As entradas são de consulta:
o motor não deve presumir execução automática de ações situacionais.
"""
import json, pathlib, re, unicodedata

ROWS=[]
def slug(s):
    return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
def add(original,nome,nivel,pagina,pre,texto,*,tracos=('geral','pericia'),acoes=None,frequencia=None):
    row={'id':'pc2-'+slug(nome),'nome':nome,'nomeOriginal':original,'nivel':nivel,'pagina':pagina,'paginaPdf':pagina,'paginaImpressa':pagina-1,'fonte':'player-core-2','tipo':'geral','tracos':list(tracos),'prerequisitos':pre,'descricao':texto,'resumo':[texto.split('. ')[0]+'.'],'revisao':'revisado','somenteConsulta':True,'automatizacao':{'estado':'executor-pendente','semCalculoManual':True}}
    if acoes is not None: row['acoes']=acoes
    if frequencia: row['frequencia']=frequencia
    ROWS.append(row)

add('A Home in Every Port','Um Lar em Cada Porto',11,227,'Carisma +3','Em uma cidade ou vila, durante o recesso, você pode gastar 8 horas para encontrar um morador disposto a hospedar gratuitamente você e até seis aliados por até 24 horas. A hospedagem tem padrão de vida confortável e fornece refeições adequadas sem custo. Depois de 24 horas, é preciso pagar os preços normais ou usar novamente este talento para encontrar outro anfitrião.',tracos=('geral','recesso'))
add('Acrobatic Performer','Artista Acrobático',1,227,'Treinado em Acrobacia','Ao usar Apresentar-se, você pode fazer um teste de Acrobacia no lugar de Performance. Se for treinado nas duas perícias, recebe +1 de circunstância nos testes de Acrobacia realizados para Apresentar-se.')
add('Aerobatics Mastery','Maestria Aerobática',7,227,'Mestre em Acrobacia','Recebe +2 de circunstância em Acrobacia para Manobrar em Voo. Pode combinar duas manobras em uma ação; a CD é a da manobra mais difícil +5. Se lendário, pode combinar três, com CD da mais difícil +10. A combinação normalmente não permite percorrer além do seu Deslocamento de voo.')
add('Armor Assist','Auxílio com Armadura',1,228,'Treinado em Atletismo ou Saber de Guerra','Faça Atletismo ou Saber de Guerra contra CD definida pelo mestre — normalmente 15 para armadura comum, 20 para incomum e 25 para rara — para reduzir pela metade o tempo de vestir sua armadura. Pode auxiliar um aliado da mesma maneira, trabalhando junto dele e obtendo sucesso contra a mesma CD.')
add('Armored Stealth','Furtividade com Armadura',2,228,'Especialista em Furtividade','Com armadura sem o traço ruidoso na qual seja treinado, reduz a penalidade de Furtividade em 1, mínimo 0; em 2 se mestre e em 3 se lendário. Se a armadura for ruidosa, em vez disso ignora o efeito do traço ruidoso, permitindo remover a penalidade com Força suficiente normalmente.')
add('Assured Identification','Identificação Garantida',2,228,'Especialista em Arcanismo, Natureza, Ocultismo ou Religião','Ao Identificar Magia com Arcanismo, Natureza, Ocultismo ou Religião, uma falha crítica vira falha. Se um sucesso que não seja crítico faria você identificar incorretamente um item amaldiçoado, você apenas não consegue identificá-lo.')
add('Backup Disguise','Disfarce Reserva',2,228,'Especialista em Dissimulação','Mantém um disfarce específico sob a roupa externa. Pode vesti-lo para Personificar como atividade de 3 ações; 2 ações se mestre e 1 ação se lendário. Preparar outro exige o tempo normal de Personificar e só pode manter um. Isso não acelera remover armadura ou roupas complexas, e uma busca minuciosa pode revelar partes ocultas do disfarce.')
add('Battle Planner','Planejador de Batalha',2,228,'Especialista em Saber de Guerra','Depois de reconhecer a posição inimiga ou receber relatório detalhado que indique número, posição e identidade dos possíveis adversários, gaste 1 minuto para planejar e role Saber de Guerra. Se as informações continuarem corretas quando rolar iniciativa contra esses inimigos, pode usar o resultado previamente obtido como iniciativa; isso é fortuna.')
add('Biographical Eye','Olhar Biográfico',7,228,'Mestre em Sociedade','Passe 1 minuto na presença de alguém que não conhecia desde antes de obter o talento e faça Sociedade CD 30; conversar concede +1 de circunstância. Se a criatura sustenta identidade falsa, descobre a biografia falsa salvo se superar a CD de Vontade. Sucesso crítico revela profissão, especialidade, grande realização ou controvérsia, país, assentamento e distrito onde vive e onde cresceu. Sucesso revela profissão, especialidade e local onde vive. Falha revela profissão e região de origem. Falha crítica fornece informação errada.',tracos=('geral','pericia','secreto'))
add('Bon Mot','Tirado Sagaz',1,229,'Treinado em Diplomacia','Escolha inimigo a até 9 m e teste Diplomacia contra a CD de Vontade. Sucesso crítico: −3 de estado em Percepção e Vontade por 1 minuto; sucesso: −2. O alvo pode encerrar com uma resposta usando uma ação de concentração ou ação de perícia adequada. Em falha crítica, você sofre a penalidade que imporia com sucesso até 1 minuto ou até obter sucesso em outro Tirado Sagaz.',tracos=('auditivo','concentracao','emocao','geral','linguistico','mental','pericia'),acoes=1)
add('Caravan Leader','Líder de Caravana',11,229,'Acelerar o Passo','Ao viajar em grupo, o grupo pode Marchar Apressado por 20 minutos além do tempo permitido ao integrante que conseguiria fazê-lo por mais tempo.')
add('Concealing Legerdemain','Prestidigitação Ocultadora',1,229,'Treinado em Ladroagem','Ao Ocultar Objeto de volume leve ou desprezível, pode usar Ladroagem em vez de Furtividade tanto no seu teste quanto na CD contra a busca ativa de alguém. Role uma única vez, mas continue usando ações para Ocultar Objeto durante todo o processo.')
add('Consult the Spirits','Consultar os Espíritos',7,229,'Mestre em Natureza, Ocultismo ou Religião','Escolha uma das perícias ao adquirir o talento. Uma vez por dia, passe 10 minutos e faça Recordar Conhecimento com ela contra CD normalmente muito difícil do maior nível provável na área. Sucesso crítico: espíritos prestativos respondem três perguntas simples sobre o ambiente a até 30 m, dentro do domínio escolhido; sucesso: espíritos indiferentes respondem uma. Falha não contata. Falha crítica contata espíritos hostis que dão até três respostas prejudiciais. Se lendário, pode usar uma vez por hora, mas não novamente em área sobreposta. Pode adquirir novamente para outra perícia.',frequencia='uma vez por dia')
add("Crafter's Appraisal",'Avaliação do Artesão',1,230,'Treinado em Manufatura','Pode usar Manufatura em vez da perícia ligada a uma tradição mágica para Identificar Magia em itens mágicos, mas não em outras formas de magia.')
add('Deceptive Worship','Adoração Enganosa',1,230,'Treinado em Ocultismo','Pode usar Ocultismo no lugar de Dissimulação para Personificar um adorador típico de outra religião ou Mentir especificamente que pertence à fé personificada. Ainda usa Dissimulação para personificar pessoa específica ou outras mentiras.')
add('Dirty Trick','Truque Sujo',1,230,'Treinado em Ladroagem; mão livre; inimigo ao alcance corpo a corpo','Faça Ladroagem contra a CD de Reflexos do alvo. Sucesso crítico deixa desajeitado 1 até ele usar Interagir para encerrar o impedimento. Sucesso deixa desajeitado 1 por 1 rodada. Falha crítica faz você cair prostrado.',tracos=('ataque','geral','manuseio','pericia'),acoes=1)
add('Discreet Inquiry','Investigação Discreta',2,230,'Especialista em Dissimulação ou Diplomacia','Ao Obter Informação, pode esconder o verdadeiro tema entre assuntos irrelevantes sem aumentar a CD nem o tempo. Quem tentar descobrir que alguém investigava o tema precisa superar sua CD de Dissimulação ou a CD normal para Obter Informação sobre suas perguntas, a que for maior.')
add('Distracting Performance','Performance Distrativa',2,230,'Especialista em Performance','Cria uma Distração usando Performance no lugar de Dissimulação, e os benefícios do sucesso se aplicam a um aliado escolhido em vez de você. Duram até o fim do turno do aliado e podem terminar antes conforme as ações dele. Não precisa vê-lo nem saber a posição, apenas saber que está presente.',acoes=1)
add('Disturbing Knowledge','Conhecimento Perturbador',7,230,'Mestre em Ocultismo','Com duas ações, faça Ocultismo contra a CD de Vontade de um inimigo a até 9 m; se lendário, compare contra qualquer quantidade de inimigos nesse alcance. Eles ficam imunes por 24 horas. Sucesso crítico: confuso por 1 rodada e assustado 1. Sucesso: assustado 1. Falha: sem efeito. Falha crítica: você fica assustado 1.',tracos=('emocao','medo','geral','mental','pericia'),acoes=2)
add('Doublespeak','Duplo Sentido',7,230,'Mestre em Dissimulação','Disfarça uma mensagem verdadeira por trás de outras palavras. Aliados que viajaram com você por ao menos uma semana entendem automaticamente. Outros precisam superar sua CD de Dissimulação com Percepção para notar a mensagem e obter sucesso crítico para compreendê-la.')
add('Environmental Guide','Guia Ambiental',7,231,'Mestre em Sobrevivência','Depois de 1 hora no ambiente, você e até cinco aliados tratam a temperatura natural como um grau menos severa. Isso se acumula com equipamento e magia. Se lendário, protege você e até cinco aliados e reduz a severidade em dois graus.')
add('Evangelize','Evangelizar',7,231,'Mestre em Diplomacia; seguidor de religião ou filosofia específica','Com uma ação, teste Diplomacia contra a CD de Vontade de alvo que possa ouvir e compreender seu idioma. Ele fica imune a este uso ligado à sua fé por 1 dia. Quem já concorda não é afetado. Sucesso crítico: estupefato 2 por 1 rodada. Sucesso: estupefato 1 por 1 rodada. Falha: sem efeito.',acoes=1)
add('Exhort the Faithful','Exortar os Fiéis',2,231,'Especialista em Religião; seguidor de religião específica','Ao Pedir ou Coagir membros da própria fé, pode testar Religião em vez de Diplomacia ou Intimidação e recebe +2 de circunstância. Numa falha crítica ao Pedir, a atitude do alvo não piora.')
add('Express Rider','Cavaleiro Expresso',1,231,'Treinado em Natureza','Ao calcular a velocidade de viagem diária montado, teste Natureza para Comandar um Animal contra CD definida pelo mestre, normalmente pelo nível da montaria ou dificuldade ambiental. Sucesso aumenta em metade a velocidade de viagem da montaria. Afeta até seis aliados montados ou quadrúpedes com Deslocamento de ao menos 9 m; não altera movimento em encontros.')
add('Eye for Numbers','Olho para Números',1,231,'Treinado em Sociedade','Ao olhar um grupo de objetos visualmente semelhantes, aprende de imediato a quantidade aproximada, arredondada ao primeiro algarismo; não distingue tipos nem conta coisas normalmente incontáveis. Se contar posses de inimigo, recebe +1 de circunstância no próximo Fintar ou Criar uma Distração contra ele em 1 minuto e pode usar Sociedade em vez de Dissimulação. Ao Decifrar Escrita numérica ou matemática, recebe +2 de circunstância.')
add('Eyes of the City','Olhos da Cidade',2,231,'Treinado em Diplomacia ou Sociedade','Pode usar Diplomacia ou Sociedade, aquela em que for treinado, para Rastrear criaturas em assentamentos conversando com moradores. O mestre pode determinar que não há pessoas suficientes para continuar a trilha.')
add('Forensic Acumen','Perspicácia Forense',1,231,'Treinado em Medicina','Faz exame forense de cadáver em metade do tempo, mínimo 5 minutos. Em sucesso, pode Recordar Conhecimento imediatamente sobre uma descoberta ou o tipo da criatura com +2 de circunstância, aumentando para +3 se mestre em Medicina e +4 se lendário.')
add('Glean Contents','Deduzir Conteúdo',1,232,'Treinado em Sociedade','Pode Decifrar Escrita parcialmente vista, invertida ou de cabeça para baixo e recebe +1 de circunstância. Também pode decifrar cartas seladas sem romper o selo, acrescentando manuseio. Isso não oculta seu esforço; em falha crítica o destinatário percebe a tentativa.')
add('Improvise Tool','Improvisar Ferramenta',1,232,'Treinado em Manufatura','Pode Reparar itens sem kit de reparo. Com matérias-primas, pode Fabricar como se conhecesse as fórmulas: estrepes básicos, vela, bússola, pé de cabra, equipamento de pesca, pederneira, martelo, escada, píton, corda, vara de 3 m, gazuas de reposição, ferramenta longa ou curta e tocha.')
add('Improvised Repair','Reparo Improvisado',3,232,'Nenhum','Com três ações, remenda item quebrado seu ou de criatura voluntária adjacente. Até receber dano outra vez, funciona como item ordinário de seu tipo. Item mágico não pode ser ativado, mas mantém funções normais. Não recupera PV e continua fácil de destruir. Ao ser Reparado normalmente e deixar de estar quebrado, deixa de ser ordinário.',tracos=('geral',),acoes=3)
add('Incredible Scout','Batedor Incrível',1,232,'Mestre em Percepção','Ao usar a atividade de exploração Batedor, concede aos aliados +2 de circunstância na iniciativa em vez de +1.',tracos=('geral',))
add('Influence Nature','Influenciar a Natureza',7,233,'Mestre em Natureza','Com chamados de animais e trilhas, influencia o comportamento de certo tipo de animal na região. Mestre define CD e tempo, normalmente um ou dois dias de recesso. Não controla diretamente, mas pode buscar caça facilitada ou aves silenciosas quando há perigo. Se lendário, produz os mesmos ajustes em 10 minutos.')
add('Inoculation','Inoculação',1,233,'Treinado em Medicina','Quando trata uma doença com sucesso e o paciente se recupera por completo, ele recebe +2 de circunstância nas salvaguardas contra a mesma doença por 1 semana.')
add('Keen Follower','Seguidor Perspicaz',3,233,'Nenhum','Ao Seguir o Especialista, recebe +3 de circunstância se o aliado for especialista e +4 se mestre. Se o aliado tiver Aliados Silenciosos ou outro talento que faça o grupo rolar uma única vez usando o pior modificador, ele pode usar o seu modificador mesmo que não seja o pior.',tracos=('geral',))
add('Lead Climber','Escalador Líder',2,233,'Especialista em Atletismo','Ao preparar rota de escalada para aliados que Seguem o Especialista, se algum falhar criticamente em Escalar, teste Atletismo contra a mesma CD. Em sucesso, a falha crítica vira falha. Se também falhar criticamente, ambos sofrem as consequências.')
add('Legendary Guide','Guia Lendário',15,233,'Lendário em Sobrevivência','Ao guiar o grupo por terreno selvagem, concede +3 m de circunstância ao Deslocamento usado para calcular viagem; terreno difícil não reduz a velocidade e terreno difícil maior reduz à metade em vez de um terço. Não altera deslocamento nem terreno durante encontros.')
add('Leverage Connections','Usar Conexões',2,233,'Especialista em Sociedade e Graças da Corte ou Experiência das Ruas','Uma vez por semana, em área com nobres/mercadores influentes ou rede criminosa apropriada, pode usar Sociedade para Pedir favor como se fossem amistosos. O pedido deve condizer com o círculo. Sucesso crítico ainda fornece conselho ou segredo que concede +2 de circunstância ao primeiro teste do grupo para agir sobre o favor. Falha crítica pode exigir serviço para recuperar a boa vontade.',tracos=('incomum','geral','pericia'),frequencia='uma vez por semana')
add('Numb to Death','Insensível à Morte',7,233,'Duro de Matar; ter morrido ao menos uma vez','Na primeira vez a cada dia que recupera PV enquanto está morrendo, recebe PV adicionais iguais ao nível e não ganha ferido nem aumenta essa condição.',tracos=('geral',),frequencia='uma vez por dia')
add('Pick Up the Pace','Acelerar o Passo',3,233,'Constituição +2','Ao Marchar Apressado em grupo na exploração, o grupo pode fazê-lo pelo tempo do integrante que conseguiria fazê-lo por mais tempo.',tracos=('geral',))
add("Pilgrim's Token",'Símbolo do Peregrino',1,233,'Treinado em Religião; seguidor de religião específica','Recebe gratuitamente um símbolo religioso de madeira. Enquanto o possuir, vence empates de iniciativa contra adversários. Substituir normalmente custa ao menos 1 pp e requer 10 minutos de oração para sintonizar; sintonizar outro encerra o benefício do anterior.')
add('Rapid Affixture','Fixação Rápida',7,234,'Mestre em Manufatura','Leva apenas 1 minuto para Fixar um Talismã. Se lendário em Manufatura, pode Fixar um Talismã como atividade de 3 ações.')
add('Risky Surgery','Cirurgia Arriscada',1,234,'Treinado em Medicina','Ao Tratar Ferimentos, pode causar 1d8 cortante no paciente imediatamente antes do efeito. Se fizer isso, recebe +2 de circunstância no teste de Medicina e transforma sucesso em sucesso crítico.')
add('Robust Health','Saúde Robusta',3,234,'Nenhum','Quando uma tentativa bem-sucedida de Tratar seus Ferimentos ou Medicina de Batalha recuperar seus PV, recebe PV adicionais iguais ao nível. Depois de Medicina de Batalha, sua imunidade temporária a ela dura apenas 1 hora em vez de 1 dia.',tracos=('geral',))
add('Rolling Landing','Aterrissagem Rolante',2,234,'Queda Felina','Quando cai sem sofrer dano, pode usar reação para dar um Passo ao aterrissar. Se especialista em Acrobacia, pode dar Passo ou Andar até metade do Deslocamento; se mestre, até o Deslocamento total; se lendário, Andar assim não aciona reações de movimento.',tracos=('geral','pericia'),acoes='reacao')
add('Root Magic','Magia de Raiz',1,234,'Treinado em Ocultismo','Nas preparações diárias, monta uma bolsa ritual e a entrega a um aliado que não seja você. Na primeira salvaguarda dele contra magia ou assombração naquele dia, recebe +1 de circunstância; +2 se você for especialista em Ocultismo e +3 se lendário.')
add('Sanctify Water','Santificar Água',2,234,'Especialista em Religião; adorar divindade que permita santificação sagrada ou profana','Escolha recipiente de água de volume leve seu ou de aliado ao alcance. Até o fim do próximo turno, torna-se água benta ou profana permitida pela divindade. Não ganha valor nem serve como custo. Se mestre, santifica dois recipientes; se lendário, três.',acoes=1)
add('Shadow Mark','Marca Sombria',2,234,'Especialista em Furtividade','Ao Evitar ser Percebido seguindo alvo específico, ele sofre −2 de circunstância na CD de Percepção; −3 se você for mestre e −4 se lendário. Se começar encontro enquanto o segue, a penalidade também se aplica à iniciativa e à CD para notar você ao Esgueirar-se.')
add('Signature Crafting','Manufatura Assinada',7,234,'Manufatura Mágica','Ao concluir com sucesso um item mágico permanente, faça teste simples CD 9. Sucesso crítico: escolha uma peculiaridade e detalhes; sucesso: recebe peculiaridade aleatória definida pelo mestre. Peculiaridades: dançante, limpo, ambiental, imundo, flutuante, cintilante, invisível, leal, coloração de humor ou habilidoso. Benefícios só se aplicam enquanto vestido ou empunhado.')
add('Slippery Prey','Presa Escorregadia',2,235,'Treinado em Acrobacia ou Atletismo','Ao Escapar com Acrobacia ou Atletismo, a penalidade por ataques múltiplos é −4/−8 se treinado, −3/−6 se mestre e nenhuma penalidade se lendário. Escapar ainda tem ataque e interage com outras ações de ataque normalmente.')
add('Snare Crafting','Manufatura de Armadilhas',1,235,'Treinado em Manufatura','Pode usar Fabricar para criar armadilhas. Ao adquirir, acrescenta imediatamente ao livro de fórmulas as fórmulas de quatro armadilhas comuns de 1º nível.')
add('Sow Rumor','Semear Rumor',2,235,'Especialista em Dissimulação','Gaste o tempo normal de Obter Informação, geralmente 2 horas, para espalhar rumor; o mestre faz Dissimulação secreta com CD pela plausibilidade e rumores concorrentes. Sucesso crítico: preferência ao Obter Informação, dura 1 mês e concede +2 de circunstância em Dissimulação, Diplomacia e Intimidação ao invocá-lo. Sucesso: entra entre rumores possíveis, dura 1 semana e concede +1. Falha: desaparece. Falha crítica: −4 para repetir na região por 1 semana e surge rumor sobre alguém espalhando falsidades.',tracos=('incomum','geral','secreto','pericia'))
add('Supertaster','Superpaladar',7,235,'Mestre em Percepção','Ao comer ou beber, tenta identificar ingredientes automaticamente; mestre faz Percepção secreta contra CD pelo nível do veneno. Em sucesso detecta veneno, mas não qual, e pode cuspir a tempo de evitar essa exposição. Quando provar algo ajuda em Investigar ou Recordar Conhecimento, recebe +2 de circunstância.')
add('Terrifying Resistance','Resistência Aterrorizante',2,235,'Especialista em Intimidação','Depois de Desmoralizar uma criatura com sucesso, por 24 horas recebe +1 de circunstância em salvaguardas contra as magias dela.')
add('Thorough Search','Busca Minuciosa',3,235,'Especialista em Percepção','Pode gastar o dobro do tempo ao Buscar, normalmente até um quarto do Deslocamento e máximo de 45 m por minuto, ou 22,5 m se verificar tudo antes de entrar. Recebe +2 de circunstância nos testes secretos de Percepção para Procurar e transforma sucesso em sucesso crítico.',tracos=('geral',))
add('True Perception','Percepção Verdadeira',19,235,'Lendário em Percepção','Fica constantemente sob os efeitos de Visão Verdadeira de 6ª graduação, usando seu modificador de Percepção no teste de neutralização.',tracos=('geral','revelacao'))
add('Tumbling Teamwork','Trabalho em Equipe Acrobático',2,235,'Especialista em Acrobacia','Quando Atravessa Acrobaticamente o espaço de um inimigo com sucesso, aliado adjacente a ele pode dar um Passo como reação, mas deve continuar adjacente.')
add('Tumbling Theft','Furto Acrobático',7,236,'Especialista em Acrobacia e Ladroagem','Ao obter sucesso crítico em Atravessar Acrobaticamente o espaço inimigo, pode tentar Roubar como reação com +1 de circunstância. Só pode pegar item imediatamente acessível de volume leve ou desprezível na pessoa, não dentro de recipiente nem empunhado; mestre decide o que é acessível.',acoes='reacao')
add('Underground Network','Rede Subterrânea',2,236,'Especialista em Sociedade; Experiência das Ruas','Em área onde tenha rede, normalmente assentamento em que passou uma semana ou um dia de recesso construindo-a, pode usar Sociedade para Obter Informação diretamente em cerca de 1 hora e com menos atenção. Depois de consultar com sucesso, recebe +1 de circunstância no próximo Recordar Conhecimento sobre o assunto, ou +2 com Saber do Submundo; mestre pode trocar o Saber conforme a rede.')
add('Water Sprint','Corrida sobre a Água',7,236,'Mestre em Atletismo','Ao Andar em linha reta e percorrer ao menos metade do Deslocamento em solo, pode percorrer o restante sobre superfície de água nivelada; se não terminar em solo, cai na água. Se lendário, desde que comece em solo, qualquer parte do movimento pode cruzar água e não precisa ser reta, mas ainda cai se não terminar em solo.')

assert len(ROWS)==59, len(ROWS)
assert len({x['id'] for x in ROWS})==len(ROWS)
out=pathlib.Path(__file__).with_name('talentos-gerais-completo-qa.json')
out.write_text(json.dumps({'talentos':ROWS,'cobertura':'59 talentos gerais e de perícia das páginas físicas 227–236, traduzidos manualmente e mantidos somente para consulta até executores próprios.'},ensure_ascii=False,indent=2)+'\n')
print(f'{len(ROWS)} talentos gerais/perícia revisados')
