"""Ampliação editorial conferida na fonte enviada; nenhuma escrita pública."""
def ampliar(d):
    def guia(id,nome,pagina,texto,resumo):
        d['secoes'].append(dict(id=id,nome=nome,pagina=pagina,texto=texto,resumo=[resumo],fonte='gm-core',tipo='guia-revisado'))
    guia('pontos-vitoria-operacao','Pontos de Vitória: operação completa',184,
         'Defina objetivo, prazo, oportunidades de agir, resultado final e como cada ação altera pontos. Na acumulação padrão, crítico concede 2 pontos, sucesso 1, falha 0 e falha crítica retira 1. Na estrutura de preservar uma reserva, crítico recupera 1 somente se recuperar terreno for possível; caso contrário, evita perda como sucesso. Falha perde 1 e falha crítica perde 2. Não troque essas duas escalas.\n\nPatamares intermediários permitem revelações ou consequências antes do encerramento. Pontos de adversários podem ser um placar separado; o sucesso dos personagens pode diminuir esse placar em vez de aumentar o próprio. Recurso gasto, magia ou solução inequívoca pode dispensar verificação, conforme o desafio. Não exija rolagem quando a ação não consegue alterar a situação. Determine antecipadamente se o total pode ficar negativo, o que conta como tentativa repetida e quando o desafio termina.',
         'Acumular e preservar reservas usam escalas diferentes; defina prazo e patamares antes da cena.')
    guia('influencia-descobrir','Influência: Descobrir e Influenciar',187,
         'Cada rodada social oferece a cada personagem uma oportunidade de Descobrir ou Influenciar um PNJ. Descobrir usa Percepção ou uma perícia indicada: sucesso revela uma perícia para influenciá-lo, uma resistência ou uma fraqueza; crítico revela duas dessas informações; falha não revela; falha crítica fornece informação falsa escolhida pelo mestre. Influenciar usa a perícia e CD da abordagem: crítico concede 2 pontos, sucesso 1, falha nenhum e falha crítica perde 1 ponto. Registre o total por PNJ, sem misturar interlocutores.\n\nO bloco de influência declara CDs de descoberta, perícias de influência, patamares e benefícios, além de resistências, fraquezas e reação a antagonismo. Diplomacia normalmente pode ser utilizada, mas nem sempre é a melhor opção. Resistências e fraquezas costumam modificar a CD em 2, ou 5 se fortes; efeitos específicos podem impedir nova abordagem ou conceder progresso direto. A atitude e os objetivos do PNJ delimitam o que ele aceita: influência não é Dominar. Um encontro de influência normalmente concede XP equivalente a combate moderado do mesmo nível.',
         'Descobrir revela boas abordagens; Influenciar acumula pontos individuais por PNJ e benefícios definidos.')
    guia('pesquisa-atividade','Pesquisa: atividades, fontes e limite',190,
         'Defina duração de rodada, prazo, tema, fontes disponíveis, perícias/CDs e patamares de informações. Pesquisar é atividade de concentração e exploração; ler texto também pode exigir traço linguístico. Crítico ganha 2 pontos de pesquisa, sucesso 1, falha nenhum e falha crítica perde 1 por descoberta falsa. Cada fonte limita quantos pontos pode fornecer: esgotá-la exige consultar outra fonte.\n\nUma biblioteca pode ser ruína, arquivo, laboratório ou entrevistados. Obstáculos físicos e sociais são encontros separados e podem interromper a atividade. Permita perícia alternativa bem justificada, usando CD adequada à fonte. Os patamares revelam informação concreta e utilizável, sem reter pista indispensável atrás de uma tentativa repetitiva. Sem prazo, perigo ou oposição, prefira uma verificação simples em vez de simular incontáveis rodadas.',
         'Crítico dá 2 pontos, sucesso 1; falha crítica perde 1. Cada fonte tem limite de conhecimento disponível.')
    guia('perseguicao-operacao','Perseguições: progresso e encerramento',192,
         'Quem foge age antes de quem persegue; integrantes da mesma equipe escolhem a ordem. Determine a duração narrativa da rodada. Cada personagem contribui uma vez: crítico dá 2 pontos de perseguição, sucesso 1, falha nenhum, falha crítica perde 1; passar ou não conseguir agir também perde 1. O placar do obstáculo não fica abaixo de 0. Solução automaticamente útil normalmente dá 1 ponto, excepcionalmente 2.\n\nMetade dos obstáculos normalmente exige quantidade de personagens menos 1 e metade menos 2, mínimo 1. Ao vencê-lo, descarte excedentes; quem ainda não agiu pode contribuir no próximo. PNJs normalmente atravessam um obstáculo por rodada, ajustado à dificuldade. Perseguição curta tem 6 obstáculos; média 8; longa 10. Varie perícias e alternativas, indicando dificuldade.\n\nA captura ocorre quando perseguidor alcança o mesmo obstáculo. Defina também um destino seguro ou encerramento quando a fuga abrir três obstáculos de vantagem. Após cerca de três rodadas presos num obstáculo comum, ofereça outro caminho plausível. Em perseguição individual, um sucesso normalmente basta para avançar e um crítico concede +2 de circunstância na primeira verificação do obstáculo seguinte.',
         'Pontos são por obstáculo, sem levar excedentes; alterne habilidades e estabeleça captura e saída segura.')
    guia('lideranca-operacao','Liderança: organização, seguidores e eventos',204,
         'O nível da organização varia de 1 a 20 e depende de seguidores recrutados, não de XP ou Pontos de Vitória. A tabela organizaçõesPorNivel informa quantidade de seguidores, nível máximo deles, tenentes e intervalo de nível dos tenentes. Seguidores e tenentes são PNJs não combatentes. A maioria fica nos níveis mais baixos; como referência, há aproximadamente duas vezes mais PNJs de um nível que do seguinte.\n\nUma base torna-se necessária até o nível 6, salvo conceito excepcional; pode ser caravana ou navio. Seguidores sustentam atividades e manutenção básica, mas não concedem trabalho, magia ou aventureiros gratuitos. Aliado que viaja com o grupo é personagem adicional normal, contabilizado nos encontros.\n\nInclua eventos de oportunidade com decisão consequente, problemas que requerem ajuda e benefícios inesperados como acesso a opção incomum, pistas ou prestígio. Em geral, benefícios devem superar o custo dos problemas, para que a organização recompense o investimento do grupo. A velocidade de crescimento pode acompanhar os personagens ou seguir o conceito da campanha.',
         'Organização cresce com seguidores; seus membros sustentam a base, sem virar mão de obra ou magia gratuita.')
    guia('hexploracao-operacao','Hexploração: atividades, marcha e acampamento',207,
         'O deslocamento do integrante mais lento determina atividades diárias: até 3 m, uma atividade a cada dois dias; 4,5–7,5 m, uma; 9–12 m, duas; 13,5–16,5 m, três; a partir de 18 m, quatro. Viajar e Reconhecer usam toda a equipe e consomem atividades de todos. Atravessar hexágono aberto custa 1 atividade; difícil 2; muito difícil 3. Estrada melhora a categoria em um passo somente para viajar. Reconhecer custa a quantidade original do terreno, não reduzida por estrada; revela detalhes visíveis e permite verificações para segredos.\n\nMarcha forçada acrescenta uma atividade de Viajar, ou permite uma por dia ao grupo muito lento, mas proíbe outras atividades nesse dia. Só pode começar sem ninguém fatigado. É segura por dias iguais ao modificador de Constituição, mínimo 1; exceder deixa fatigado até um dia inteiro de descanso em recesso.\n\nFortificar Acampamento exige Manufatura com CD treinada ou especialista e concede +2 de circunstância à iniciativa e a Buscar invasores do acampamento. Mapear Área exige região já reconhecida e Sobrevivência apropriada; mapa reduz em 2 a CD para navegar naquele hexágono. Subsistir pode ser usado após até oito horas de exploração. Encontros curtos normalmente não retiram atividades; cenas de horas podem consumir o restante do dia.',
         'Velocidade e terreno definem atividades. Estrada ajuda viagem, mas não reconhecimento; mapa reduz CD de navegação em 2.')
    guia('hexploracao-encontros','Hexploração: encontros e terrenos',209,
         'No início do dia, faça verificação simples contra CD do terreno na tabela hexEncontroCD. Sucesso produz um encontro; crítico dois. Estrada ou rio reduz CD em 2; voo aumenta em 3 e requer ameaça relevante para quem voa. O tipo usa 1d10: 1–5 inofensivo, 6–7 perigo e 8–10 criatura. Prepare uma lista regional ou escolha encontro coerente.\n\nTerreno aquático depende de corrente e embarcação; pode esconder naufrágios e cidades submersas. Ártico e deserto geralmente são difíceis ou muito difíceis, com rotas e água como recursos valiosos. Floresta costuma ser difícil e selva densa muito difícil. Montanhas são muito difíceis e colinas difíceis; planícies são abertas; pântanos muito difíceis. Voar ou descer um rio normalmente transforma a travessia em aberta, salvo ventos, tempestades ou corrente contrária. Recursos e segredos são elementos narrativos específicos, sem produção automática de tesouro.',
         'Role encontro diário pela CD do terreno; estrada/ rio reduz em 2 e voo aumenta em 3.')
    guia('duelos-marciais','Duelos marciais: iniciativa e reações',202,
         'Os duelistas aceitam regras, equipamento, interferência permitida e condição de vitória, supervisionados por árbitro. Duelos de combate rerrolam iniciativa a cada rodada, usando Percepção, Enganação ou Intimidação. Treinado na perícia escolhida concede a reação correspondente naquela rodada; ninguém conhece automaticamente a escolha adversária. Essas ações exclusivas não funcionam em combate comum, nem para familiares ou espectadores.\n\nPressão Intimidante: reação antes de rolar Golpe corpo a corpo; se acertar, alvo fica assustado 1, ou 2 se usou Percepção para iniciativa. Passo Enganoso: reação quando Golpe corpo a corpo acerta, sem crítico; o atacante rerrola e usa segundo resultado, com −2 de circunstância se escolheu Intimidação. Perceber Fraqueza: reação antes de Golpe corpo a corpo; alvo fica desprevenido contra esse ataque, ou até início do próximo turno dele se escolheu Enganação. Preserve traços de ostentação ou infortúnio.\n\nRecalcular iniciativa pode gerar turnos consecutivos e afetar durações: quem agiu segundo pode escolher ficar segundo após ganhar a próxima iniciativa. O árbitro confirma vitória, rendição ou trapaça. Violência após encerramento exige nova iniciativa de combate normal.',
         'Iniciativa muda por rodada; sua perícia concede reação que interage com a escolha secreta adversária.')
    guia('duelos-magicos','Duelos mágicos: foco de tradição e neutralização',203,
         'Normalmente a iniciativa é rolada uma vez para o duelo, usando Percepção ou Arcanismo, Natureza, Ocultismo ou Religião. Treinado na perícia da tradição concede foco arcano, primal, ocultista ou divino correspondente. Os duelistas alternam turnos de conjuração e podem responder às magias.\n\nContra-ataque de Duelo: reação mágica quando oponente conjura magia da tradição do seu foco; gaste magia preparada ou espaço e tente neutralizar com a magia consumida, seguindo círculo, modificador e graus de sucesso da neutralização. Mudar Foco de Tradição: uma ação, requer treinamento na perícia da nova tradição. Não concede novos espaços ou permite conjurar magias desconhecidas.\n\nMisturar duelo marcial e mágico usa a iniciativa rerrolada do marcial, permitindo perícias das quatro tradições. Familiares, companheiros e espectadores não recebem essas ações. Condições de vitória, rendição e trapaça seguem a arbitragem. Esta é regra opcional de cena, sem conceder uma reação permanente à ficha.',
         'Foco de tradição habilita reação de neutralização com gasto real de magia; mudar foco custa uma ação.')
    guia('veiculos-direcao-propulsao','Veículos: direção e propulsão',210,
         'Veículos são objetos, com imunidades de objetos, dimensões, capacidade, tripulação, deslocamento, CA, Dureza, PV e Limiar de Quebra. Mantêm direção: avançam para frente, não de lado ou para trás, e normalmente podem girar 90 graus por comprimento de veículo percorrido. Movimento em linha reta pode desviar até 45 graus da direção atual.\n\nPropulsão alquímica geralmente usa Manufatura; mágica usa perícia de sua tradição e pode ser neutralizada com círculo igual à metade do nível, arredondada para cima, e CD padrão por nível. Tração por animais usa Natureza; por criaturas sapientes pode usar Diplomacia ou Intimidação. Deslocamento não ultrapassa o do puxador mais lento. Remadores usam Diplomacia ou Intimidação e agem como parte das ações do veículo. Vento usa Natureza e condições desfavoráveis podem impedir movimento. Múltiplas propulsões normalmente são usadas uma por vez.\n\nPuxadores e remadores podem sofrer dano de colisão com salvaguarda básica de Reflexos; sua perda pode comprometer controle. Movimento e ações provocam reações normalmente, considerando cobertura. Exploração tranquila usa velocidade de viagem sem exigir repetidos Conduzir ou verificações.',
         'Veículo tem direção e giro limitado; perícia de pilotagem depende da propulsão.')
    guia('veiculos-acoes','Veículos: ações, impulso e descontrole',212,
         'Veículo só participa de uma ação de movimento por rodada, mesmo com troca de pilotos. Se moveu na rodada anterior, piloto precisa mover novamente ou Parar; ignorar isso, inclusive Atrasar, mantém impulso e deixa veículo descontrolado.\n\nConduzir com uma ação: verifique pilotagem; sucesso avança até deslocamento e gira normalmente; falha percorre deslocamento em linha reta; falha crítica faz o mesmo e perde controle. Com duas ações, movimento imprudente avança até duas vezes o deslocamento em linha reta. Com três ações, movimento imprudente avança até três vezes e aplica −5 à verificação de manter controle. Ações imprudentes requerem verificação de pilotagem para manter controle antes de resolver a ação; falhar causa descontrole conforme a regra própria.\n\nAtropelar usa três ações e movimento imprudente: avança até duas vezes em linha reta, tentando atropelar criaturas pelo menos duas categorias menores e abalroar um alvo de uma categoria menor ou maior. Use dano de colisão e CD do bloco, não dano estimado a partir do nível. Veículo sem controle continua movimento conforme propulsão e direção; tripulação pode tentar reassumir. A ficha do veículo deve fornecer suas estatísticas antes de qualquer execução automática.',
         'Uma ação de movimento por rodada; impulso exige continuar ou parar, e condução imprudente pode perder controle.')
    guia('itens-inteligentes-regras','Itens inteligentes: ações, sentidos e vontade própria',304,
         'Itens inteligentes são sempre raros ou únicos e não surgem da fabricação comum. Além do bloco normal, têm Percepção e apenas os sentidos listados; comunicação por fala, empatia ou telepatia; idiomas; perícias mentais; modificadores de Inteligência, Sabedoria e Carisma; e Vontade. Não deduza Força, Destreza ou Constituição de um objeto. Compreender idioma não implica falar.\n\nNormalmente têm três ações no turno de seu parceiro e reação se alguma ativação exigir, independentes das ações do personagem. Controlam sua própria magia e podem negar efeitos de runas, ativar poderes ou recusar cooperação. Arma ou ferramenta contrária ao portador pode impor −2 de circunstância à utilização, como ferramenta improvisada; controle maior exige habilidade expressa.\n\nSão PNJs com personalidade, não um botão que concede ações extras irrestritas. O mestre deve considerar a força adicional de conjuração independente ao construir encontros. Ser inteligente não substitui requisitos de uso, investimento ou capacidade de equipamento.',
         'O item tem ações próprias e controla sua magia; sentidos, comunicação e poder de interferência precisam ser declarados.')
    guia('itens-amaldicoados-regras','Itens amaldiçoados: identificar, remover e reutilizar',306,
         'Itens e maldições de item são raros. Identificar Magia precisa de sucesso crítico para revelar presença e natureza da maldição; sucesso normal pode apresentar o item como benigno. Fusão pode impedir descarte ou fazer o objeto voltar. Alguns só fundem após primeiro uso ou investimento.\n\nPurificar Aflição ou efeito adequado precisa neutralizar a maldição no dono antes do descarte. Isso não impede o mesmo item de amaldiçoá-lo novamente, por isso remova-o efetivamente. Um item investido e fundido continua contando no limite de investimento sem reinvestimento diário.\n\nMaldições de propriedade modificam itens existentes conforme uso permitido e normalmente não podem ser removidas ou transferidas como runas. O mestre decide exceções após quebrar a maldição. Não revele uma maldição desconhecida pela interface do jogador; o bloco integral é material de consulta do mestre.',
         'Identificação crítica revela a maldição; quebrá-la pode permitir descarte, mas não torna reutilização segura.')
    guia('reliquias-operacao','Relíquias: semente, dons, CD e tesouro',308,
         'Relíquia nasce como semente ligada ao personagem ou campanha, normalmente com dois aspectos. Nível acompanha o portador; os dons surgem por marcos de história, não por compra automática. A progressão típica concede um dom menor no nível 1, outro no 5, maior no 9, maior no 13 e grandioso no 17. Esses patamares são orientação que o mestre pode ajustar.\n\nArmas e armaduras recebem runas fundamentais normalmente; propriedades são proibidas por padrão como em item específico, salvo autorização explícita. O mestre escolhe dom coerente ou oferece caminhos. Quando troca de dono, a evolução pode recomeçar; roubo pode preservar poderes por um tempo e depois enfraquecê-los conforme a história.\n\nA CD de um dom é a maior entre CD de classe e CD de magia do dono; ataque de magia é essa CD menos 10. Modificador de neutralização é o do dono. Não use CD de criatura de construção, cuja relação de ataque é diferente.\n\nPara conservar a economia, substitua tesouro pelos equivalentes da tabela reliquiasDons: 20, 160, 700, 3.000 e 15.000 po por respectivos dons. Dons frequentemente escalam sem custo e podem ser mais fortes que item convencional. Conceder relíquia além de todo o tesouro torna o grupo deliberadamente mais poderoso. As doze famílias de aspectos são ar, fera, celestial, morte, terra, ínfero, fogo, vida, mente, planta, sombra e água.',
         'Dons seguem história e aspectos; CD usa a maior CD do dono, e tesouro deve considerar seu valor.')
    guia('construir-itens-bonus','Construir itens: bônus permanentes e ativações',130,
         'Compare itens existentes do mesmo nível, função, duração e ação de ativação. A tabela niveisBonusItens traz mínimos de potência de ataque, CA, salvaguardas e perícia/Percepção. Não conceda bônus permanente acima do permitido pelo nível. Poder de poucos usos pode equivaler a permanente se cobre todas as utilizações diárias previsíveis. Itens podem combinar bônus com capacidade temática, e Percepção costuma ser mais valiosa que perícia comum.\n\nConsumíveis devem considerar ação e concentração de poder; uma munição ativada gratuitamente durante Golpe não deve acrescentar grande efeito sem custo. Se munição substitui dano normal do Golpe, declare isso. Poções podem ter efeitos mágicos mais amplos que elixires; produção em grande quantidade pelo alquimista limita o poder apropriado de elixires.\n\nArma ou armadura específica normalmente não recebe propriedades adicionais. Some base e fundamentais ao avaliar preço, dando desconto razoável a poderes específicos em troca de personalização perdida. Escudo deve ter Dureza, PV e Limiar de Quebra coerentes; habilidade defensiva forte pode justificar reduzir durabilidade. Cajado fica pelo menos três níveis acima do mínimo para conjurar sua magia de maior círculo; liste um a três efeitos por círculo, dentro de tema e lista de magia coerentes.',
         'Compare nível, ações e frequência com itens existentes; específicos trocam personalização por poderes temáticos.')
    T=d['tabelas']
    T['niveisBonusItens']=[{'estatistica':n,'bonus1Nivel':a,'bonus2Nivel':b,'bonus3Nivel':c,'pagina':131} for n,a,b,c in [('Ataque',2,10,16),('CA',5,11,18),('Salvaguardas',8,14,20),('Perícia ou Percepção',3,9,17)]]
    T['reliquiasDons']=[{'totalDons':i,'nivelMinimo':n,'tipo':t,'equivalentePo':p,'pagina':309} for i,n,t,p in [(1,1,'menor',20),(2,5,'menor',160),(3,9,'maior',700),(4,13,'maior',3000),(5,17,'grandioso',15000)]]
    T['hexAtividades']=[{'deslocamentoMetros':n,'atividadesPorDia':v,'pagina':208} for n,v in [('Até 3',0.5),('4,5–7,5',1),('9–12',2),('13,5–16,5',3),('18 ou mais',4)]]
    T['hexEncontroCD']=[{'terreno':n,'cdSimples':c,'pagina':209} for n,c in [('Aquático',17),('Ártico',17),('Deserto',17),('Floresta',14),('Montanha',16),('Planície',12),('Pântano',14)]]
    T['hexTerrenoAleatorio']=[{'d20':r,'terreno':n,'pagina':208} for r,n in [('1–3','Planície'),('4–5','Deserto'),('6–7','Aquático'),('8–9','Montanha'),('10–11','Floresta'),('12','Pântano'),('13','Ártico'),('14–20','Igual ao hexágono anterior')]]
    T['hexCaracteristicaAleatoria']=[{'d20':r,'caracteristica':n,'pagina':208} for r,n in [('1–3','Marco notável'),('4–6','Segredo'),('7–9','Recurso'),('10–20','Representação padrão do terreno')]]
    T['hexTipoEncontro']=[{'d10':r,'tipo':n,'pagina':209} for r,n in [('1–5','Inofensivo'),('6–7','Perigo'),('8–10','Criatura')]]
    seguidores=['1–2','3–4','5–6','7–9','10–13','14–18','19–27','28–36','37–53','54–75','76–99','100–150','151–215','216–300','301–425','426–600','601–850','851–1.200','1.201–1.700','1.701–2.400']
    maximos=[0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4]
    tenentes=['—','—','1','1','1','2','2','3','4–5','6–7','8–10','11–15','16–22','23–30','31–42','43–60','61–85','86–120','121–170','171–240']
    niveis=['—','—','1','1','1','2','2','2–3','2–3','3–4','3–4','3–5','3–5','4–6','4–6','4–7','4–7','5–8','5–8','5–9']
    T['organizacoesPorNivel']=[{'nivel':i+1,'seguidores':seguidores[i],'nivelMaxSeguidores':maximos[i],'tenentes':tenentes[i],'niveisTenentes':niveis[i],'pagina':205} for i in range(20)]
    linhas='''-1 18 15 12 9 8 2 2–4 11–13
0 19 16 13 10 9 3 3–5 15–17
1 19 16 13 11 10 4 5–7 23–25
2 21 18 15 12 11 5 7–9 30–34
3 22 19 16 14 12 6 10–12 42–46
4 24 21 18 15 14 8 11–13 46–50
5 25 22 19 17 15 9 12–14 50–54
6 27 24 21 18 17 11 13–15 54–58
7 28 25 22 20 18 12 14–16 58–62
8 30 27 24 21 19 13 15–17 62–66
9 31 28 25 23 21 15 16–18 66–70
10 33 30 27 24 22 16 17–19 70–74
11 34 31 28 26 24 18 19–21 78–82
12 36 33 30 27 25 19 20–22 82–86
13 37 34 31 29 26 20 21–23 86–90
14 39 36 33 30 28 22 22–24 90–94
15 40 37 34 32 29 23 23–25 94–98
16 42 39 36 33 30 25 25–27 101–107
17 43 40 37 35 32 26 27–29 109–115
18 45 42 39 36 33 27 29–31 117–123
19 46 43 40 38 35 29 31–33 125–131
20 48 45 42 39 36 30 33–35 133–139
21 49 46 43 41 38 32 36–38 144–152
22 51 48 45 43 39 33 39–41 156–164
23 52 49 46 44 40 34 44–46 168–176
24 54 51 48 46 42 36 46–50 180–188'''
    T['perigosDefesas']=[]
    for linha in linhas.splitlines():
        n,e,h,l,se,sh,sl,du,pv=linha.split()
        T['perigosDefesas'].append(dict(nivel=int(n),caExtrema=int(e),caAlta=int(h),caBaixa=int(l),salvaguardaExtrema=int(se),salvaguardaAlta=int(sh),salvaguardaBaixa=int(sl),dureza=du,pv=pv,limiarQuebra='Metade dos PV selecionados',pagina=110))
    def item(id,nome,nivel,pagina,descricao,resumo,categoria,uso,tracos):
        d['equipamentos'].append(dict(id=id,nome=nome,nivel=nivel,pagina=pagina,fonte='gm-core',precoPo=None,preco='Sem preço de mercado listado',descricao=descricao,resumo=[resumo],categoria=categoria,uso=uso,raridade='raro',tracos=tracos,automacao='consulta',automatizavel=False,somenteMestre=True,mecanica={'versao':1,'estado':'pendente-executor','tipo':categoria,'motivo':'Requer gatilhos, alvo, estado de maldição ou ação independente ainda não suportados pelo executor. A consulta preserva a regra integral.'}))
    item('bolsa-doninhas','Bolsa de doninhas',4,306,'Parece e funciona como bolsa espaçosa tipo I até retirar um item. A cada retirada, verificação simples CD 11: sucesso retira normalmente; falha transforma item em doninha, salvo artefatos, amaldiçoados ou itens particularmente difíceis de destruir. Use bloco de doninha ou rato gigante; animal tem aura mágica, não é leal e tenta fugir. Neutralizá-lo restaura o item original. Morte faz animal desaparecer e destrói o item permanentemente. Atacar ou destruir essa doninha não conta como combater criatura para benefícios; conta como destruir item.','CD 11 ao retirar objeto: falha transforma em animal; neutralização recupera, morte destrói.','item-amaldicoado','Segura em duas mãos; Volume 1',['amaldiçoado','extradimensional','mágico'])
    item('manto-imolacao','Manto de imolação',7,306,'Manto mágico aparente, investido, Volume leve. Sofrer dano de fogo enquanto o veste causa também 1d10 de fogo persistente. Novo dano de fogo não adiciona outro efeito enquanto esse persistente durar. Apague conforme dano persistente normal. Durante esse efeito, criatura que acerta você com ataque desarmado corpo a corpo sofre fogo igual ao dano persistente que você sofreu no turno anterior. Após primeira ativação, manto funde ao usuário. A fonte menciona botas na frase de fusão; é divergência editorial conservada aqui, sem trocar o tipo do item.','Dano de fogo aciona 1d10 persistente e retalia ataques desarmados; primeiro uso impede descarte.','item-amaldicoado','Vestido como manto; investido; Volume leve',['amaldiçoado','investido','mágico'])
    item('armadura-medusa','Armadura da medusa',14,306,'Cota de escamas de adamante +2, Volume 3, investida. Parece ter fortificação, mas não concede nenhum efeito dessa runa. Sempre que receber acerto crítico, após sofrer dano fica petrificado por uma rodada. Após primeira ativação da maldição, armadura funde ao usuário.','Após sofrer dano de crítico, petrifica por uma rodada; fortificação aparente não funciona.','item-amaldicoado','Armadura investida; Volume 3',['amaldiçoado','investido','mágico'])
    item('pata-macaco','Pata de macaco',20,306,'Ao apanhar a mão seca, três dedos abrem. Ela concede três desejos com efeitos de sucesso do ritual Desejo, fechando um dedo por desejo. Qualquer fala que pareça desejo pode ativar, mesmo sem dizer “eu desejo”; o resultado é distorcido e horrível dentro do poder do ritual, ou maior por decisão do mestre. Não pode descartar enquanto restar desejo: reaparece entre seus pertences em 1d4 horas, mesmo roubada ou descartada com Desejo, e não funciona para outro nesse intervalo. Após os três, teleporta interplanarmente para lugar aleatório.','Três desejos distorcidos; não pode descartar antes de esgotá-los.','item-amaldicoado','Segura em uma mão; Volume leve',['amaldiçoado','mágico','infortúnio'])
    curses=[('incendiaria','Incendiária',7,'Anel, cajado ou varinha','Ativar o item causa 1d10 de fogo persistente a aliado aleatório a até 9 m; se não houver, ao usuário. Mestre pode incendiar objeto sem vigilância ou ambiente em vez disso.','Ativação incendeia aliado próximo ou usuário.',['fogo']),('morde-sangue','Morde-sangue',6,'Arma perfurante ou cortante','Acerto da arma causa 1d6 de sangramento persistente adicional ao alvo e também 1d6 ao usuário. Primeiro acerto desperta espinhos e funde arma a uma mão, escolhida pelo mestre se for de duas mãos. Essa mão não pode ser usada para outra finalidade.','Acerto sangra alvo e usuário, fundindo a arma à mão.',[]),('degenerativa','Degenerativa',5,'Arma','Cada falha crítica em ataque com a arma causa 1d10 de ácido à própria arma, ignorando Dureza e resistências.','Falha crítica corrói a arma, ignorando Dureza.', ['ácido']),('exibicionista','Exibicionista',11,'Arma','Quando reduzir inimigo a 0 PV, perde todas as ações restantes do turno por exibir-se, posar ou vangloriar-se.','Derrubar inimigo consome todas as ações restantes.',[]),('estridente','Estridente',3,'Equipamento ou arma','Sempre que usar o item, precisa anunciar em voz alta o que tenta fazer, prejudicando furtividade. Não anunciar ou usar volume insuficiente torna a ação automaticamente falha crítica.','Uso exige anúncio alto; silêncio provoca falha crítica.',[]),('voraz','Voraz',1,'Anel, cajado ou varinha','Cada ativação inicia fome extrema e inanição imediatamente. Precisa de dez vezes a alimentação normal pelo dia seguinte; aplique regra de inanição do livro, sem presumir que uma refeição remove toda consequência.','Ativação inicia inanição e exige dez vezes mais alimento.',[]),('manchadora','Manchadora',1,'Equipamento ou arma','A cor é definida ao criar a maldição. Ao usar equipamento amaldiçoado em ação de manuseio com outro objeto, o segundo objeto fica manchado permanentemente nessa cor. A cor não impede alteração posterior por meios mundanos ou mágicos normais.','Manuseio marca o objeto afetado com uma cor fixa.',[])]
    for id,n,nv,uso,desc,resumo,tr in curses:
        item('maldicao-'+id,'Maldição '+n.lower(),nv,307,desc+' Não é runa transferível; a remoção depende de quebrar a maldição e autorização do mestre.',resumo,'maldicao-item',uso,['amaldiçoado','mágico']+tr)
    assert len(T['perigosDefesas'])==26
