"""Talismãs individuais do GM Core, pp. 263–267, em PT-BR."""


def ampliar(d):
    d["secoes"].append({"id":"talismas-regras","nome":"Talismãs e afixação","pagina":263,"fonte":"gm-core","tipo":"guia-revisado",
      "texto":"Talismã é um pequeno consumível mágico afixado a armadura, escudo ou arma. É preciso vestir ou empunhar o item para ativá-lo; após ativado, o talismã se esgota. Afixar ou remover exige 10 minutos, kit de reparo, superfície estável e as duas mãos. Cada talismã só pode estar num item e mais de um no mesmo item suprime todos até serem removidos e afixados novamente.",
      "resumo":["Afixar ou remover leva 10 minutos; ativar consome o talismã e exige usar o item afixado."]})
    def add(id_,nome,nivel,preco,pagina,desc,resumo,raridade="comum"):
      d["equipamentos"].append({"id":id_,"nome":nome,"nivel":nivel,"precoPo":preco,"pagina":pagina,"descricao":desc,"resumo":[resumo],"categoria":"talisma","fonte":"gm-core","raridade":raridade,"somenteConsulta":True,"automatizavel":False,"mecanica":{"versao":1,"tipo":"referencia","estado":"nao-implementado","motivo":"Talismã revisado para consulta; gatilho, consumo e efeito ainda não possuem executor completo."}})
    itens=[
    ("orbe-liga","Orbe de liga",3,10,263,"Afixado a arma metálica; uma ação. Escolhe ferro frio ou prata por 1 minuto, suprimindo material original; funciona até nível 8. Padrão (nível 8, 80 po) até nível 15. Padrão requintado incomum (nível 12, 400 po) também adamante ou prata da alvorada. Alto grau (nível 16, 1.500 po) qualquer nível; alto grau requintado incomum (nível 18, 4.500 po) também os três materiais.","Muda temporariamente o material da arma, com cinco versões."),
    ("olho-basilisco","Olho de basilisco",9,150,263,"Afixado a escudo; ação livre ao Bloquear ataque corpo a corpo. Atacante faz Fortitude CD 25 ou lento 1 por 1 minuto.","Ao Bloquear, pode deixar atacante lento 1, CD 25."),
    ("bico-sugue-sangue","Bico de suga-sangue",4,20,263,"Afixado a arma; ação livre ao acertar desprevenido. +1d4 precisão; se causou ataque furtivo, +1d4 sangramento persistente. Maior (nível 8, 100 po): ambos 2d4.","Aumenta precisão e, com ataque furtivo, sangramento."),
    ("pingente-touro-bronze","Pingente de touro de bronze",2,7,263,"Afixado a armadura; uma ação. Tenta Empurrar com +1 de item; desloca 3 m no sucesso ou 6 m no crítico.","Empurrar com +1 e distância ampliada."),
    ("pingente-anjo-chorando","Pingente do anjo chorando",2,7,263,"Afixado a armadura; duas ações. Presta Primeiros Socorros com +1. Estabilizar com sucesso também cura 1 PV e acorda; conter sangramento com sucesso encerra-o.","Melhora Primeiros Socorros e estabilização."),
    ("espiral-atordoante","Espiral atordoante",14,900,263,"Afixada a arma; ação livre ao ferir desprevenido. Vontade CD 31: falha atordoado 1, falha crítica atordoado 2.","Atordoa alvo desprevenido ferido, CD 31."),
    ("lasca-dissipadora","Lasca dissipadora",17,2400,264,"Afixada a arma; ação livre quando Golpe causa dano. Tenta neutralizar uma magia no alvo com Dissipar Magia de 8º círculo e +29; com Corte Dissipador tenta todas além da tentativa da façanha.","Neutraliza magia ativa no alvo com +29."),
    ("escama-tartaruga-dragao","Escama de tartaruga-dragão",4,13,264,"Afixada a armadura; exige Atletismo treinado. Por 1 minuto, natação igual a metade do terrestre; maior (nível 8, 75 po), igual ao terrestre.","Concede deslocamento de natação por 1 minuto."),
    ("ampola-efervescente","Ampola efervescente",2,7,264,"Afixada a armadura; exige Acrobatismo treinado. Até o fim do turno, move-se sobre líquidos como chão e não ativa placas de pressão por peso; ao terminar, afunda, cai ou ativa normalmente.","Move-se sobre líquidos e evita placas de peso até o fim do turno."),
    ("gafanhoto-esmeralda","Gafanhoto de esmeralda",5,30,264,"Afixado a armadura; Atletismo treinado. Salta até 12 m horizontal/3 m vertical e, se não pousar, desce sem dano a 18 m por rodada. Maior (nível 9, 150 po): 30 m/9 m e vale para outros Saltos no turno.","Salto longo e queda segura; versão maior amplia todos os Saltos do turno."),
    ("olho-apreensao","Olho da apreensão",12,400,264,"Afixado a armadura; ação livre antes de iniciativa por Percepção, exige mestre. Rola duas vezes e usa o maior.","Fortuna na iniciativa de Percepção."),
    ("faixa-desvanecimento","Faixa de desvanecimento",12,320,264,"Afixada a armadura; reação quando ataque erra, exige Furtividade treinada. Conjura Invisibilidade de 2º círculo.","Fica invisível após um ataque errar."),
    ("gema-medo","Gema do medo",4,20,264,"Afixada a arma; duas ações para Golpe corpo a corpo. Se ferir: assustado 1, ou 2 no crítico; com Golpe Intimidante, valores 2/3.","Golpe corpo a corpo causa assustado."),
    ("pedra-passo-pena","Pedra do passo de pena",3,8,264,"Afixada a armadura; ação livre ao Andar ou Dar Passo, exige Acrobatismo treinado. Ignora terreno difícil e muito difícil até fim do turno.","Ignora terreno difícil no turno."),
    ("dente-forca","Dente de forca",8,100,265,"Afixado a arma; uma ação. Golpe corpo a corpo contra adjacente; alvo desprevenido contra ele e até fim do turno.","Deixa o alvo desprevenido durante o turno."),
    ("po-fantasma","Pó fantasma",16,1800,265,"Afixado a armadura; Furtividade treinada. Conjura Invisibilidade de 4º círculo e permite Andar ou Dar Passo, ou usar escavação, escalada, voo ou natação disponível.","Invisibilidade de 4º círculo seguida de movimento."),
    ("trofeu-sinistro","Troféu sinistro",7,55,265,"Afixado a armadura; uma ação. Desmoraliza até dois alvos com a mesma rolagem; maior (nível 11, 250 po), até três.","Desmoraliza dois ou três alvos."),
    ("cubo-ferro","Cubo de ferro",6,50,265,"Afixado a arma; duas ações. Golpe corpo a corpo e, se ferir, Derrubar; derrubado sofre 2d6 contundente. Arma de duas mãos dispensa mão livre. Ambos contam para penalidade, que só aumenta depois. Com Derrubada, ignora limite de tamanho e pode usar dado da arma se maior.","Golpe seguido de Derrubar e dano adicional."),
    ("medalhao-ferro","Medalhão de ferro",10,175,265,"Afixado a armadura; ação livre antes de Vontade contra medo. +2 de estado na salvaguarda e contra medo por 1 minuto; falha vira sucesso, falha crítica vira falha.","Melhora um grau da salvaguarda contra medo e concede +2."),
    ("gato-jade","Gato de jade",2,6,265,"Afixado a armadura; ação livre ao cair ou Equilibrar, Acrobatismo treinado. Por 1 minuto quedas contam 6 m menores, não fica desprevenido ao Equilibrar e superfícies estreitas/irregulares não são terreno difícil.","Protege de quedas e facilita Equilibrar por 1 minuto."),
    ("trelica-reparo","Treliça de reparo",13,525,266,"Incomum; afixada a escudo ou arma; ação livre quando sofreria dano, Manufatura treinada. Nega o dano e repara completamente o item.","Nega dano e repara totalmente o item afixado.","incomum"),
    ("opala-hipnotica","Opala hipnótica",2,7,266,"Afixada a armadura; uma ação para Fintar. Sucesso vira crítico; falha crítica vira falha.","Melhora o grau de Fintar."),
    ("broche-macaco","Broche de macaco",2,6,266,"Afixado a armadura; uma ação Escalar com +1. No sucesso move deslocamento total nesse turno; falha crítica vira falha.","Escala com +1 e deslocamento total."),
    ("morcego-mumificado","Morcego mumificado",10,175,266,"Afixado a arma. Por 1 minuto ignora teste contra encoberto, usa CD 5 contra escondido, não fica desprevenido apenas por escondido e adjacente indetectado de nível igual ou menor vira escondido. Com Combate às Cegas, ecolocalização imprecisa 9 m.","Aprimora detecção de encobertos, escondidos e indetectados."),
    ("no-assassino","Nó do assassino",7,66,266,"Afixado a arma; ação livre ao ferir desprevenido. Causa 1d6 sangramento persistente e alvo fica desprevenido até sangramento acabar; com Torcer a Faca usa dano do ataque furtivo.","Sangramento persistente mantém alvo desprevenido."),
    ("pantera-onix","Pantera de ônix",2,7,266,"Afixada a armadura; uma ação Furtar-se com +1. Move deslocamento total nessa e em outras ações Furtar-se do turno.","Furtar-se com +1 e deslocamento total."),
    ("cristal-potencia","Cristal de potência",1,4,266,"Afixado a arma; ação livre antes do ataque. No Golpe e até fim do turno vira +1 impactante. Maior (nível 9, 150 po): +2 impactante maior. Superior (nível 15, 1.300 po): +3 impactante superior.","Concede runas fundamentais à arma até fim do turno."),
    ("garra-predador","Garra do predador",1,3,266,"Afixada a arma; ação livre em crítico. Concede o efeito de especialização crítica da arma.","Ativa especialização crítica da arma."),
    ("espinho-salvador","Espinho salvador",2,7,267,"Afixado a armadura; ação livre antes de Agarrar uma Beirada. +1 de item; sucesso vira crítico e falha crítica vira falha.","Melhora Agarrar uma Beirada."),
    ("amuleto-dente-tubarao","Amuleto de dente de tubarão",5,23,267,"Afixado a armadura; uma ação Escapar com Acrobatismo +1. Sucesso vira crítico, falha crítica vira falha. Se falhar contra criatura agarrando, ela solta como ação livre ou sofre 2d8 perfurante.","Melhora Escapar e pune criatura que mantém o agarrão."),
    ("chave-furtiva","Chave furtiva",5,22,267,"Afixada a armadura; Ladroagem treinada. +1 de estado para Abrir Fechadura por 1 minuto; primeiro sucesso ou crítico dá um sucesso adicional em fechadura complexa.","Ajuda Abrir Fechadura e concede progresso adicional."),
    ("cabochao-bloqueio-veloz","Cabochão de bloqueio veloz",7,70,267,"Incomum; afixado a escudo; reação ao sofrer dano físico. Usa Bloqueio com Escudo mesmo sem escudo erguido ou reação normal, +5 Dureza contra o ataque e o escudo permanece erguido.","Permite Bloqueio imediato com +5 Dureza.","incomum"),
    ("menuki-tigre","Menuki de tigre",5,30,267,"Afixado a arma; ação livre ao Golpear. Arma recebe enérgica e varredura no Golpe e nos demais por 1 minuto.","Concede enérgica e varredura por 1 minuto."),
    ("moeda-desaparecimento","Moeda de desaparecimento",10,160,267,"Afixada a armadura; ação livre antes de iniciativa com Furtividade, exige treinado. Invisibilidade de 2º círculo até fim do próximo turno.","Fica invisível durante o começo do encontro."),
    ("presa-vibora","Presa de víbora",14,850,267,"Afixada a arma; reação a manipulação, movimento, ataque à distância ou saída de quadrado, exige mestre. Golpe corpo a corpo sem penalidade múltipla; crítico interrompe manipulação. Com Ataque Reativo ativa livremente. Acerto expõe a veneno: Fortitude CD 32, máximo 4 rodadas, estágio 1: 3d10 e enfraquecido 1.","Ataque reativo sem penalidade e veneno CD 32."),
    ("presa-lobo","Presa de lobo",1,4,267,"Afixada a armadura; ação livre após Derrubar. Causa contundente igual ao modificador de Força ao alvo.","Derrubar causa dano igual à Força.")]
    for it in itens:add(*it)
