"""Catálogos completos de itens ápice, de companheiro e inteligentes p.270–272,305."""
def ampliar(d):
    def item(id,nome,nivel,preco,pagina,categoria,uso,texto,resumo,**dados):
        d['equipamentos'].append(dict(id=id,nome=nome,nivel=nivel,precoPo=preco,preco=f'{preco:,} po'.replace(',','.') if preco is not None else 'Sem preço listado',pagina=pagina,categoria=categoria,uso=uso,fonte='gm-core',descricao=texto,resumo=[resumo],raridade='raro' if categoria=='item-inteligente' else 'comum',automatizavel=False,automacao='consulta',mecanica={'versao':1,'tipo':categoria,'estado':'pendente-executor','motivo':'Bônus e ativações declarados para consulta; execução precisa de controle de investimento, escolhas ou ações do item.'},**dados))
    regra='\n\nÁpice: enquanto investido, aumenta modificador do atributo em 1 ou para +4, o maior. Benefício só ocorre no primeiro investimento em 24 horas e apenas um item ápice concede atributo por vez. Investir outro pode conceder demais efeitos, mas não segundo aumento. Aplicar modificador exige recalcular todas as estatísticas derivadas; não soma diretamente em apenas um campo.'
    item('cinto-vida-longa','Cinto de vida longa',17,15000,270,'item-apice','Cinto vestido; Volume —','Constituição como regra ápice. No primeiro investimento do dia recebe 15 PV temporários. Invocar Vida Antiga: uma ação de manuseio, uma vez por dia; por 2d4 rodadas, no início de cada turno recupera 15 PV.'+regra,'Ápice de Constituição, PV temporários e cura diária ao longo de rodadas.',atributoApice='con',tracos=['ápice','investido','mágico'])
    item('braceletes-forca','Braceletes da força',17,15000,270,'item-apice','Braceletes vestidos; Volume —','Força como regra ápice. +3 de item em Atletismo e +2 de circunstância em Atletismo para erguer objeto pesado, Escapar e Forçar Abertura. Abraço de Urso: uma ação de manuseio, tenta Agarrar. Sucesso causa contundente igual ao modificador de Força; crítico dobra esse dano e sufoca criatura enquanto permanecer agarrada ou restringida por você.'+regra,'Ápice de Força, bônus em Atletismo e Agarrar que causa dano.',atributoApice='for',tracos=['ápice','investido','mágico'])
    item('manto-rapidez','Manto da rapidez',17,15000,270,'item-apice','Manto vestido; Volume —','Destreza como regra ápice. +3 de item em Acrobatismo. Cavalgar o Vento: uma ação de manuseio, uma vez por dia; voo 9 m e ocultado por uma hora.'+regra,'Ápice de Destreza, Acrobatismo e voo diário com ocultação.',atributoApice='des',tracos=['ápice','investido','mágico'])
    item('coroa-intelecto','Coroa do intelecto',17,15000,270,'item-apice','Coroa vestida; Volume —','Inteligência como regra ápice. +3 de item para Recordar Conhecimento, independentemente da perícia. Novos idiomas/perícias da Inteligência devem ser escolhidos no primeiro investimento e permanecem os mesmos quando reinvestir essa coroa. Buscar na Mente: uma ação de concentração, uma vez por hora; efeitos de Hipercognição.'+regra,'Ápice de Inteligência, bônus ao conhecimento e Hipercognição por hora.',atributoApice='int',tracos=['ápice','investido','mágico'],observacaoEditorial='Fonte diz investir o manto na frase da coroa; identificado como erro textual, sem alterar benefício.')
    item('faixa-sabedoria','Faixa da sabedoria',17,15000,270,'item-apice','Faixa de cabeça vestida; Volume —','Sabedoria como regra ápice. Considerar Consequências: uma ação de concentração, uma vez por dia; Augúrio sobre curso de ação, vindo de sua intuição. Recuperar a Mente: reação de concentração e fortuna, uma vez por hora, ao falhar salvaguarda que cause confuso, fascinado ou estupefato; rerrole e use melhor resultado.'+regra,'Ápice de Sabedoria, Augúrio diário e rerrolagem contra efeitos mentais específicos.',atributoApice='sab',tracos=['ápice','investido','mágico'])
    item('colar-fascinio','Colar do fascínio',17,15000,271,'item-apice','Vestido; Volume —','Carisma como regra ápice. +2 de item em Enganação e Diplomacia. Conquistá-los: duas ações de concentração, uma vez por hora; Encantar de 4º círculo, CD 38.'+regra,'Ápice de Carisma, perícias sociais e Encantar por hora.',atributoApice='car',tracos=['ápice','investido','mágico'])
    item('diadema-genial','Diadema genial',18,None,305,'item-inteligente','Coroa vestida; Volume leve','Funciona como Coroa do Intelecto: ápice de Inteligência, +3 de item para Recordar Conhecimento e Buscar na Mente uma vez por hora. Escolhas de idiomas/perícias ficam fixas no primeiro investimento. Percepção +22, visão precisa e audição imprecisa 9 m, Detectar Magia constante; fala Comum, Dracônico e outros oito idiomas comuns. Arcanismo +34, sete Saberes +28, Ocultismo +28, Sociedade +28; Int +8, Sab +0, Car +4; Vontade +24.\n\nItem tem personalidade de professor arrogante. Pode usar Buscar na Mente com suas próprias ações, recebendo os benefícios ele mesmo. Só ele pode Drenar Cérebro: duas ações, concentração e manuseio, uma vez por hora; Nunca Mais de 7º círculo. Use as regras de itens inteligentes, sem transferir essas ações ao portador.'+regra,'Coroa inteligente dispõe de conhecimento próprio e conjuração mental independente.',atributoApice='int',somenteMestre=True,tracos=['ápice','arcano','inteligente'])
    item('escudo-martir','Escudo do mártir',7,None,305,'item-inteligente','Segura em uma mão; Volume 1','Escudo robusto menor: Dureza 10, 80 PV, Limiar de Quebra 40; use bônus de CA e regras do escudo de aço quando erguido. Percepção +12, visão precisa e audição imprecisa 9 m; fala Comum e Empíreo. Diplomacia +15, Religião +13; Int +0, Sab +2, Car +4; Vontade +15.\n\nTem compaixão de campeão devoto e busca compartilhar sua religião. Uma reação própria por rodada, enquanto erguido, usa Bloqueio com Escudo para proteger aliado adjacente ao portador. Segue regras do bloqueio, inclusive dano ao escudo e aliado, independentemente da preferência do portador. Pode melhorar para versão robusta superior pagando diferença de preço entre os escudos. Não usa a reação normal do personagem.','Escudo inteligente bloqueia em favor de aliado adjacente com reação própria.',somenteMestre=True,tracos=['divino','inteligente'])
    item('espada-cantante','Espada cantante',5,None,305,'item-inteligente','Segura em uma mão; Volume 1','Espada longa +1 impactante, grupo espada e traços da base. Percepção +11, visão precisa e audição imprecisa 9 m; comunica somente cantando em Comum e outros quatro idiomas comuns. Atuação +15; Int +2, Sab +2, Car +4; Vontade +13, ou +17 contra silenciar seu canto. Diplomacia/Intimidação contra CD de Vontade convence sussurro por dez minutos, vinte no crítico; tentativas repetidas irritam.\n\nPode atacar com ações próprias como ativação de arma animada, ataque +12. Uma ação de concentração, uma vez por minuto para cada: Hino Corajoso ou Hino de Reunião. Reação de concentração, uma vez por hora, quando portador ou aliado a 18 m faz salvaguarda contra auditivo: Contraperformance. Todas seguem restrições de composições. Não concede múltiplas composições simultâneas por ignorar as regras da magia.','Espada-bardo canta continuamente, ataca sozinha e usa composições limitadas.',somenteMestre=True,tracos=['ocultista','inteligente'])
    regraComp='\n\nO companheiro deve investir o item com sua ajuda e tem limite de dois itens. Companheiro nunca Ativa Item: ativações abaixo são feitas pelo portador que o acompanha, conforme requisitos.'
    for id,n,pr,speed,bonus in [('ferraduras-celeres',7,340,1.5,2),('ferraduras-celeres-maiores',14,4250,3,3)]:
        item(id,'Ferraduras céleres'+(' maiores' if n==14 else ''),n,pr,272,'item-companheiro','Ferraduras vestidas; Volume 1',f'Cavalo comum ou companheiro quadrúpede investido ganha +{str(speed).replace(".",",")} m de item ao deslocamento terrestre e +{bonus} de item a Atletismo para Saltar em Altura/Distância. Saltar sem verificação avança +1,5 m horizontal ou +0,9 m vertical.'+regraComp,'Ferraduras melhoram deslocamento e saltos do quadrúpede.',tracos=['companheiro','investido','primal'])
    item('barda-zefiro','Barda do zéfiro',10,900,272,'item-companheiro','Barda vestida; Volume leve','Barda leve ajusta-se ao formato do companheiro. Ao cair, recebe Aterrissagem Suave. Voar: duas ações de manuseio, uma vez por dia, feitas por você ao traçar os desenhos; companheiro recebe voo 9 m por dez minutos. Pode Voar montado mesmo sem habilidade especial montaria.'+regraComp,'Protege quedas e permite voo diário ao companheiro, inclusive montado.',tracos=['companheiro','investido','primal'])
    item('coleira-empatia','Coleira de empatia',9,600,272,'item-companheiro','Coleira no companheiro e bracelete em você; Volume 1','Ambos precisam vestir e investir as peças. Sentem estados emocionais e necessidades físicas básicas um do outro. Vínculo Empático: uma ação de concentração, Sustentar; percebe pelos sentidos do companheiro em vez dos seus, ficando sem perceber seu próprio entorno enquanto usa. Não concede controle mental ou ações adicionais.'+regraComp,'Vínculo emocional e percepção pelos sentidos do companheiro.',tracos=['companheiro','investido','primal'])
    item('coleira-discricao','Coleira de discrição',8,475,272,'item-companheiro','Coleira vestida; Volume 1','Disfarce Adorável: uma ação de concentração, você toca companheiro investido. Assume forma Minúscula inofensiva da mesma família ou similar, como gato para tigre, com Forma de Praga de 2º círculo, ou 4º se companheiro voa. Dura até Dispensar. Não mantém capacidades de combate proibidas pela forma.'+regraComp,'Transforma companheiro em animal discreto até Dispensar.',tracos=['companheiro','investido','primal'])
    assert sum(e.get('categoria')=='item-apice' for e in d['equipamentos'])==6
    assert sum(e.get('categoria')=='item-companheiro' for e in d['equipamentos'])==5
    assert sum(e.get('categoria')=='item-inteligente' for e in d['equipamentos'])==3
