import json,pathlib,re,hashlib
R=pathlib.Path(__file__).resolve().parents[3]
d={'fonte':{'id':'gm-core','nome':'GM Core — Livro do Mestre','edicao':'remaster','idiomaOriginal':'en','paginas':338,'estado':'parcial','nota':'Guia de consulta e entradas revisadas. A tradução integral das 338 páginas ainda está pendente.'},'classes':[],'ancestralidades':[],'biografias':[],'talentos':[],'magias':[],'equipamentos':[],'secoes':[],'tabelas':{},'lacunas':['Tradução integral das 338 páginas não concluída; os guias presentes não substituem todo o livro.','Catálogo contém somente entradas explicitamente revisadas: ainda faltam armas específicas, alquimia, talismãs, itens vestidos, amaldiçoados e relíquias.','Tabelas completas de criação de criaturas, perigos e itens ainda não transcritas; os guias não geram estatísticas oficiais por aproximação.','Geografia, facções, divindades e cosmologia ainda não traduzidas integralmente.','Variantes e subsistemas são consulta; nenhuma mudança automática na ficha padrão.']}
def s(id,n,p,t,r):d['secoes'].append({'id':id,'nome':n,'pagina':p,'texto':t,'resumo':r,'fonte':'gm-core','tipo':'guia-revisado'})
s('papel-mestre','O papel do mestre e a preparação',6,'O mestre descreve o mundo, interpreta personagens não jogadores, apresenta desafios e resolve regras. Prepare situações, objetivos dos adversários e consequências possíveis, deixando os jogadores escolherem o caminho. Combine proposta, limites e opções disponíveis antes da campanha.\n\nAntes da sessão, revise acontecimentos, objetivos, lugares e encontros prováveis. Apresente o que os personagens podem perceber. Quando houver dúvida, tome uma decisão clara para a situação, consulte a regra depois e mantenha decisões futuras consistentes.',['Prepare situações e consequências, deixando as escolhas conduzirem a história.'])
s('raridade-acesso','Raridade e acesso às opções',22,'Raridades: comum, incomum, raro e único; sem indicação, a opção é comum. Raridade descreve disponibilidade, não força. O mestre decide quais opções incomuns ou raras se encaixam na campanha.\n\nUma condição de acesso permite obter aquela opção quando cumprida, sem torná-la comum para todos. Descoberta, treinamento e organizações podem oferecer acesso. Identificação ou conhecimento podem ter CD ajustada por raridade: incomum +2, raro +5 e único +10, quando a tarefa manda aplicar o ajuste.',['Raridade significa disponibilidade; acesso e autorização são definidos por opção.'])
s('cds','Escolher uma Classe de Dificuldade',52,'Use CD simples para uma dificuldade própria da tarefa: 10 destreinado, 15 treinado, 20 especialista, 30 mestre e 40 lendário. Esses nomes indicam dificuldade, não exigem proficiência mínima por si só. Uma tarefa envolvendo criatura, item ou perigo com nível usa a CD daquele nível. Para identificar ou aprender magia, use a CD por círculo.\n\nAjustes: incrivelmente fácil −10, muito fácil −5, fácil −2, difícil +2, muito difícil +5 e incrivelmente difícil +10. Não torne uma tarefa simples mais difícil só porque o personagem subiu de nível. Requisitos mínimos explícitos, como em fechaduras e perigos, continuam obrigatórios. Normalmente, tarefas até nível 2 não exigem especialista, até nível 6 não exigem mestre e até nível 14 não exigem lendário.',['CD simples para a tarefa; CD por nível para um elemento com nível.'])
s('recordar-conhecimento','Recordar Conhecimento e identificar',54,'Conhecimento geral usa CD simples. Criatura, perigo ou assunto com nível usa CD por nível, ajustada por raridade. Um Saber realmente adequado ou assunto notório pode reduzir a dificuldade; uma perícia alternativa menos direta pode aumentá-la.\n\nIdentificar criatura com sucesso revela uma característica conhecida importante; crítico acrescenta algo mais sutil, como fraqueza ou gatilho de reação. Após sucesso, verificações adicionais podem revelar mais, mas ficam mais difíceis. Depois de falha ou de tentativa incrivelmente difícil, novas tentativas deixam de render informação. Identificar Magia, Identificar Alquimia e Aprender Magia usam CD do círculo ou nível do item, ajustada por raridade.',['Sucesso revela uma característica útil; crítico acrescenta informação sutil.'])
s('experiencia','Experiência, avanços e feitos',56,'O avanço padrão exige 1.000 XP por nível; subtraia 1.000 e conserve excedentes. O grupo pode combinar 800 XP para avanço rápido, 1.200 para lento ou avanço por marcos.\n\nXP de encontros vai integralmente a cada personagem, sem divisão. Ajustar orçamento para tamanho do grupo não muda a recompensa equivalente para quatro personagens. Triviais normalmente não concedem XP. Feitos menores, moderados e maiores concedem 10, 30 e 80 XP; moderados e maiores também costumam justificar Ponto de Heroísmo. Não permita repetição trivial para gerar XP indefinidamente.',['Cada personagem recebe o prêmio inteiro; avanço padrão exige 1.000 XP.'])
s('heroismo','Pontos de Heroísmo',57,'Comece cada sessão com 1 Ponto de Heroísmo, máximo de 3. O mestre costuma conceder aproximadamente um por hora de jogo para contribuições heroicas, criativas ou memoráveis. Pontos restantes expiram no fim da sessão.\n\nGaste 1 para rerrolar uma verificação, usando o segundo resultado: efeito de fortuna. Ou gaste todos, pelo menos 1, quando seu valor de morrendo aumentaria, para perder morrendo e estabilizar em 0 PV sem ganhar ferido por esse resgate. Contribuições importantes não precisam ser ataques; distribua reconhecimento entre papéis diferentes.',['Um ponto permite rerrolagem; todos permitem evitar morrer.'])
s('encontros','Construir encontros e ajustar o grupo',75,'Para quatro personagens, escolha ameaça e orçamento: trivial até 40 XP, baixa 60, moderada 80, severa 120, extrema 160. Cada personagem além de quatro acrescenta 10, 20, 20, 30 ou 40 XP, respectivamente; cada personagem faltante subtrai o mesmo ajuste.\n\nCompare nível de criatura e grupo: diferenças de −4 a +4 custam 10, 15, 20, 30, 40, 60, 80, 120 e 160 XP. Some criaturas e perigos conforme suas tabelas. Geralmente use esse intervalo de níveis. Grupo de criaturas menores e adversário único muito forte produzem desafios diferentes.\n\nModerada exige bons recursos e táticas. Severa pode matar personagens; extrema pode derrotar o grupo todo. Considere terreno, preparação, retirada e descanso. O ajuste de tamanho altera orçamento, mas o prêmio continua equivalente a quatro personagens.',['Some custos e compare ao orçamento; severa e extrema exigem intenção.'])
s('variar-encontros','Variedade de encontros',76,'Alterne terreno, dificuldade, quantidade de inimigos e objetivos. Cobertura, plataformas, água e portas tornam movimento relevante. Confrontos podem começar com negociação ou aproximação furtiva e terminar com rendição ou fuga.\n\nVitória pode significar proteger alguém, impedir ritual ou sobreviver até ajuda. Guarde complexidade alta para momentos importantes. Apresente sinais de ameaças para permitir decisões: esconder toda informação transforma escolhas em arbitrariedade.',['Varie cenário, adversários e objetivos, incluindo retirada e negociação.'])
s('tesouro-grupo','Tesouro por nível do grupo',58,'A tabela indica tesouro para quatro personagens durante um nível inteiro de aventuras, não por encontro. Valor total é aproximado; permanentes, consumíveis e moeda sugerem sua composição. Moeda inclui arte, gemas e materiais vendáveis.\n\nPor personagem extra, acrescente um permanente do nível do grupo ou um acima, dois consumíveis geralmente desses níveis e a moeda da coluna adicional. Em grupos menores, pode subtrair o equivalente ou conservar um pouco mais para compensar papéis ausentes. Entregue itens úteis: moeda sem acesso a compra ou fabricação não garante equipamento adequado. Compare preços e efeitos ao trocar níveis.',['Tesouro vale para um nível inteiro; equipamento útil importa tanto quanto dinheiro.'])
s('riqueza-novo-personagem','Equipar novos personagens em níveis maiores',61,'Escolha os permanentes e moeda da tabela ou, se o mestre permitir, o valor único alternativo em moeda. Não receba ambas as alternativas. Permanentes indicados são versões básicas: propriedades e materiais preciosos são adicionais.\n\nEscolher item de nível menor não devolve moeda automaticamente. Na alternativa em moeda, nível máximo de item é um abaixo do personagem. Incomuns e raros dependem do mestre. Pode acrescentar um item do nível atual se a campanha já avançou bastante nele; considere equipamento de mortos ou aposentados mantido pelo grupo para não duplicar riqueza.',['Escolha itens mais moeda ou valor único; propriedades e materiais são adicionais.'])
s('comprar-vender','Compra, venda e mercado',48,'Compra e venda geralmente ocorrem no recesso. Venda normal rende metade do preço; arte, gemas e materiais brutos costumam valer o preço integral. A disponibilidade depende do povoado e história.\n\nNível do assentamento ajuda a determinar itens e serviços. Dinheiro não garante acesso a item raro ou de nível alto. Pode abstrair vendas ou exigir compradores específicos quando relevante; combine o detalhamento com o grupo.',['Venda normal pela metade; arte, gemas e materiais podem valer preço integral.'])
s('perigos','Perigos simples e complexos',98,'Perigos podem ser armadilhas mecânicas, mágicas, ambientais ou assombrações. Furtividade fornece CD de detecção ou modificador de iniciativa de complexo; somar 10 ao modificador fornece CD quando necessário. Proficiência mínima continua obrigatória.\n\nSimples geralmente usam reação uma vez; complexos rolam iniciativa e executam rotina com ações indicadas. Leia gatilho, desarme, rotina e reinício. Superar por desarme, evasão ou resistência concede XP uma vez; reativar não concede de novo.\n\nQuando danificável, aplique Dureza, PV e Limiar de Quebra. Quebrado deixa de funcionar mas pode ser reparado; 0 PV significa destruído e não reparável. Não invente estatísticas ausentes. Atacar pode ativar a armadilha; destruir em um golpe quase nunca ativa.',['Simples usa reação; complexo tem iniciativa e rotina; recompensa uma única vez.'])
s('construir-perigos','Criar perigos',109,'Defina cena, gatilho, sinais, efeito e formas de lidar com o perigo. Escolha nível, simples ou complexo e métodos de desarme. Compare CDs, defesa e dano às tabelas de criação, sem usar a ficha de um personagem como modelo numérico.\n\nDescreva partes ou sucessos necessários; neutralização mágica precisa de círculo e CD. Registre gatilho, reação, iniciativa, rotina, duração e reinício para um procedimento verificável.',['Informe gatilho, detecção, desarme, efeito e reinício.'])
s('criaturas-pnjs','Criar criaturas e PNJs',112,'Crie estatísticas adequadas ao nível, não uma ficha completa de jogador. Escolha conceito, função e estatísticas altas, moderadas e baixas. Compare defesa, ataques, dano, CDs e PV às tabelas. Não maximize tudo.\n\nHabilidades especiais precisam de ações, alcance, gatilho, salvaguarda, duração e limites. Revise especialmente incapacitação e remoção de ações. PNJs podem ter competência profissional maior que seu nível de combate; registre separadamente. Criaturas e PNJs ficam no bestiário, sem misturar às fichas pessoais.',['Estatísticas por nível e função, com pontos fortes e fracos.'])
s('criar-itens','Criar e avaliar itens',130,'Compare com itens publicados de nível semelhante, analisando bônus, dano, defesa, ações, frequência e duração. Preço sozinho não determina equilíbrio. Mesmo sem acumular bônus do mesmo tipo, uma opção que concede ações ou elimina limitações pode ser muito forte.\n\nPermanentes que reproduzem magia precisam considerar frequência e círculo; consumíveis têm outra economia. Artefatos podem superar padrões e não entram automaticamente em mercado comum.',['Compare efeitos, frequência e ações, além do preço.'])
s('fabricar-melhorar','Fabricação e melhoria',223,'Melhorar uma versão permitida geralmente cobra a diferença entre preços. Segue Manufaturar e os requisitos da entrada; o efeito novo só funciona depois de terminar. Itens mágicos exigem capacidade apropriada.\n\nUse a atividade Remaster do Livro do Jogador para tempo, fórmula e custo: este PDF ainda cita tempos antigos em exemplos. Não automatize essas comparações. Os preços do catálogo são aquisição total; melhoria cobra a diferença válida.',['Melhorias cobram diferença quando permitidas; use Manufaturar Remaster.'])
s('runas','Runas fundamentais e de propriedade',224,'Armas usam potência para ataques e impactante para dados de dano. Armaduras usam potência para CA e resiliente para salvaguardas. Escudos usam reforçadora, limitada pela versão.\n\nPotência +1, +2 e +3 permite uma, duas ou três propriedades. Fundamentais não ocupam esses espaços. Escudos não aceitam propriedades ou runas de arma/armadura. Roupa de explorador aceita runas de armadura, mas não as que exigem categoria que ela não tem.\n\nNível final é o maior entre base e runas. Versões da mesma runa não se somam, salvo exceção explícita para energias distintas. Armadura com runas precisa de investimento.',['Potência limita propriedades; nível final é o maior entre base e runas.'])
s('transferir-runas','Transferir e trocar runas',225,'Use Manufaturar e capacidade de fabricar itens mágicos. Pode mover uma runa ou trocar duas; ambas devem ser fundamentais ou ambas propriedades. Destino incompatível causa falha crítica automática.\n\nCD usa nível e custo é 10% do preço, salvo transferência de pedra rúnica, gratuita. Trocas usam maior nível e preço entre as runas. Transferir demora um dia, podendo continuar para desconto conforme atividade. Propriedades excedendo capacidade ficam dormentes até potência suficiente ou transferência.',['Um dia; 10% do preço, salvo pedra rúnica; exige destino compatível.'])
s('pergaminhos','Pergaminhos mágicos',262,'Guarda uma magia em círculo específico, sem truques, foco ou rituais. Uma mão e ações normais de conjuração; deve estar na lista do usuário e usa seu ataque e CD. É consumido na conjuração. Custos físicos foram pagos na fabricação, mas locus exigido continua necessário.\n\nMagia comum da lista ou conhecida é identificada automaticamente com Recordar Conhecimento; outras exigem Identificar Magia. Raridade segue a magia. Fabricar exige uma conjuração por pergaminho a partir de espaço, não de outro item. Lote de quatro deve ter mesma magia e círculo. O bloco imprime frequência de varinha por engano: não concede sobrecarga ao consumível.',['Uma conjuração usando suas estatísticas; pergaminho é consumido.'])
s('varinhas','Varinhas e sobrecarga',282,'Uma mão, magia na sua lista e ações normais; usa seu ataque e CD. Não guarda truques, foco ou rituais. Custos de magia são pagos ao usar e locus continua necessário.\n\nUma conjuração por dia. Pode sobrecarregar uma segunda vez: conjura e faz verificação simples CD 10; sucesso quebra, falha destrói. Outra sobrecarga no mesmo dia destrói sem conjurar, mesmo após reparar. Raridade segue a magia; fabricar exige conjuração de espaço mas não pagamento do custo próprio da magia. Varinhas especiais alteram essas regras conforme entrada.',['Uma magia diária; sobrecarga arrisca quebra ou destruição.'])
s('pocoes','Poções e uso em outra criatura',259,'Beber ou alimentar outra criatura normalmente usa Interagir, uma ação com uma mão, consumindo a poção. Só pode alimentar alguém ao alcance disposto ou tão indefeso que não resista.\n\nA entrada determina duração e efeito. Cura mágica de poção é diferente de elixir alquímico. Não transforme efeito temporário em permanente nem elimine ação para beber.',['Uma ação Interagir, consumida; só alimente criatura disposta ou indefesa.'])
s('investimento-ativacao','Investir e ativar itens',219,'Itens investidos exigem investimento para benefícios; máximo normal de dez por dia. Item mágico sem esse traço não ocupa limite. Investir não substitui requisito de ativação.\n\nConfira ações, traços, frequência, gatilho e requisitos. Reação exige gatilho; trocar dono não multiplica usos diários. Bônus de item do mesmo tipo não somam para a mesma estatística; geralmente vale o maior.',['Até dez investidos; ações, frequência e gatilhos continuam obrigatórios.'])
s('aflicoes','Aflições, doenças e maldições',86,'Leia exposição, início, estágio, intervalo, duração e salvaguardas. A exposição pode ter efeito imediato ou atraso. Cada resultado altera estágio conforme a regra da aflição.\n\nCurar PV não remove automaticamente doença ou maldição. Registre estágio, próximo intervalo e efeitos atuais separadamente para não repetir dano. Não invente campos ausentes.',['Controle estágio e intervalo; recuperar PV não remove a aflição.'])
s('ambiente','Ambiente, terreno e desastres',90,'Apresente riscos e proteções de frio, calor, água, altura, terreno, portas e paredes, exceto surpresa legítima da cena. Objetos usam Dureza, PV e Limiar de Quebra de seu material. Exposição usa regras próprias do ambiente.\n\nDesastres podem ser perigos ou cenas com objetivos. Evite dano repetido sem escolhas; ofereça sinais e formas de escapar ou proteger pessoas.',['Ambiente deve oferecer riscos compreensíveis e escolhas.'])
s('pontos-vitoria','Pontos de Vitória',184,'Defina objetivo, atividades, CDs, oportunidades e patamares antes da cena. Pode haver prazo ou oposição. Acúmulo padrão: crítico +2, sucesso +1, falha 0, falha crítica −1.\n\nReserva decrescente: crítico recupera 1 se possível, sucesso preserva, falha perde 1, falha crítica perde 2. São modelos; subsistemas podem mudar resultados. Nomeie pontos conforme cena e permita competências diferentes.',['Defina objetivo e patamares; pontos representam progresso verificável.'])
s('influencia','Influência social',187,'A cena usa rodadas com oportunidades para investigar interlocutores ou influenciá-los. PNJs têm preferências, resistências, perícias adequadas e patamares de resultado. Descobrir preferências permite boas abordagens.\n\nPontos produzem benefícios definidos, não controle mental nem obediência irrestrita. Registre participantes e patamares separadamente.',['Descobertas melhoram abordagens; influência não significa obediência universal.'])
s('pesquisa','Pesquisa com prazo',190,'Defina coleção, perícias, CDs, tempo e informações reveladas por patamares de pesquisa. Diferentes fontes permitem métodos e conhecimento diferentes. Avanços devem entregar informação útil.\n\nNão gere conhecimento ilimitado na mesma fonte. Uma revelação pode indicar novo lugar ou método; prazos precisam de consequências compreensíveis.',['Fontes, tempo e patamares estruturam revelações úteis.'])
s('perseguicoes','Perseguições',192,'Obstáculos sucessivos têm formas de superação e pontos necessários. Defina distância inicial, prazo e efeitos de perder terreno.\n\nPermita alternativas plausíveis, como escalar, saltar, negociar ou abrir caminho. Resultados seguem cada obstáculo e preservam decisões. A cena vai além de comparar deslocamentos.',['Obstáculos com alternativas e progresso tornam escolhas relevantes.'])
s('infiltracao','Infiltração, alerta e vantagens',196,'Contra obstáculo, crítico dá 2 pontos de infiltração, sucesso 1; falha gera 1 de alerta e falha crítica 2. Ajuda automática geralmente concede 1 ou 2 quando excepcional.\n\nAlerta padrão: 5 aumenta CDs em 1 e gera complicação na primeira vez; 10 gera outra; 15 aumenta total de CD para +2 e nova complicação; 20 causa falha da missão. Tempo pode elevar alerta. Vantagens obtidas na preparação convertem falha ou falha crítica em sucesso gastando um ponto, respeitando restrições da vantagem.',['Progresso e alerta separados; vantagem pode corrigir uma falha específica.'])
s('reputacao','Reputação com organizações',200,'Pontos de reputação variam de −50 a +50 por facção. Favores menores, moderados e maiores normalmente dão 1, 2 e 5 pontos; prejuízos retiram equivalentes, podendo superar 5 se especialmente graves.\n\nPatamares: ignorados −4 a +4; apreciados +5 a +14; admirados +15 a +29; reverenciados +30 a +50; malvistos −5 a −14; odiados −15 a −29; caçados −30 a −50. Patamares limitam favores e prejuízos relevantes conforme tabela. Opinião individual pode variar; mudanças decisivas na história justificam reconsiderar reputação.',['Reputação separada por facção; benefícios e limites seguem o patamar.'])
s('duelos','Duelos combinados',202,'Combine ferramentas, participantes, interferência e penalidades antes do duelo. Quebrar regra e ser descoberto causa derrota conforme combinado.\n\nA variante permite escolhas de iniciativa como Enganação, Intimidação ou Percepção por rodada e reações para treinados. Pode criar dois turnos seguidos; considere durações até início do próximo turno. Não mude todos os combates por causa desse subsistema.',['Duelos têm acordo próprio e não mudam automaticamente o combate padrão.'])
s('hexploracao','Exploração em hexágonos',206,'Hexágonos organizam viagem, reconhecimento e outras tarefas. Terreno, velocidade, tamanho e tempo determinam atividades diárias.\n\nVisitar não significa investigar tudo. Marque áreas exploradas e pontos de interesse; aplique recursos, descanso e clima consistentemente.',['Passar por uma região não revela tudo; investigação exige atividades.'])
s('veiculos','Veículos',210,'Veículo tem espaço, tripulação, passageiros, propulsão, deslocamento, defesa e estrutura. Use atividades e perícia próprias de pilotagem, não regras automáticas de montaria.\n\nControle ações do piloto, direção e obstáculos em encontros; Dureza, PV e Limiar de Quebra determinam danos. Colisões e passageiros seguem suas regras. Viagem tranquila pode usar exploração.',['Ficha do veículo e pilotagem controlam movimento e danos.'])
s('arquetipo-livre','Variante: arquétipo livre',84,'Concede trilha extra de talentos de arquétipo nos níveis pares, separada de talentos de classe. O mestre pode permitir escolha ampla ou tema comum.\n\nDepende de autorização; requisitos de talentos e dedicações continuam, salvo adaptação expressa do mestre. Não concede níveis de outra classe nem substitui talentos normais.',['Talentos extras nos níveis pares quando autorizados, preservando a progressão normal.'])
s('progressao-bonus','Variante: progressão automática de bônus',83,'Substitui muitos bônus de item por potência conforme nível, removendo necessidade de runas de potência, impactante e resiliente, mas preservando bônus básico da armadura à CA. Itens podem continuar com propriedades especiais.\n\nMuda ataque, dados, defesa, percepção, salvaguardas e perícias escolhidas. Ajuste recompensas; não some com runas substituídas. O trecho de ápice no PDF usa pontuações antigas, não modificadores Remaster; consulte errata antes de aplicar. Variante não está automatizada.',['Substitui bônus, não acumula com eles; exige ajuste de tesouro.'])
s('proficiencia-sem-nivel','Variante: proficiência sem nível',85,'Remover nível da proficiência exige ajustar criaturas, perigos, CDs e encontros, não apenas fichas de jogador. Muda distribuição de críticos e intervalo de adversários ameaçadores.\n\nUse tabelas próprias da variante e aplique a todo grupo. Permanece fora da automação padrão enquanto os caminhos afetados não forem consistentes.',['Muda o grupo e adversários; não é preferência isolada de uma ficha.'])
T=d['tabelas']
T['cdSimples']=[{'grau':i,'nome':n,'cd':v} for i,(n,v) in enumerate(zip(['Destreinado','Treinado','Especialista','Mestre','Lendário'],[10,15,20,30,40]))]
T['cdPorNivel']=[{'nivel':i,'cd':v} for i,v in enumerate([14,15,16,18,19,20,22,23,24,26,27,28,30,31,32,34,35,36,38,39,40,42,44,46,48,50])]
T['cdPorCirculo']=[{'circulo':i+1,'cd':v} for i,v in enumerate([15,18,20,23,26,28,31,34,36,39])]
T['ajustesCd']=[{'nome':n,'ajuste':v} for n,v in [('Incrivelmente fácil',-10),('Muito fácil',-5),('Fácil',-2),('Difícil',2),('Muito difícil',5),('Incrivelmente difícil',10)]]
T['orcamentoEncontro']=[{'id':i,'nome':n,'xp':x,'ajustePorPersonagem':a,'grupoBase':4} for i,n,x,a in [('trivial','Trivial',40,10),('baixo','Baixa',60,20),('moderado','Moderada',80,20),('severo','Severa',120,30),('extremo','Extrema',160,40)]]
T['xpCriaturas']=[{'diferencaNivel':i-4,'xp':v} for i,v in enumerate([10,15,20,30,40,60,80,120,160])]
T['xpPerigos']=[{'diferencaNivel':i-4,'simples':s,'complexo':c} for i,(s,c) in enumerate(zip([2,3,4,6,8,12,16,24,30],[10,15,20,30,40,60,80,120,150]))]
T['ajustesRaridade']=[{'raridade':'Comum','ajusteCd':0},{'raridade':'Incomum','ajusteCd':2},{'raridade':'Raro','ajusteCd':5},{'raridade':'Único','ajusteCd':10}]
T['xpPerigosNota']='A fonte p. 57 e 99 imprime +4 como 30/150, em conflito com regra textual de simples um quinto e complexo igual à criatura (32/160). Preservado para consulta, separado do orçamento de criaturas; confrontar errata ou decisão do mestre antes de automatizar.'
T['feitos']=[{'nome':n,'xp':v} for n,v in [('Menor',10),('Moderado',30),('Maior',80)]]
vals=[175,300,500,850,1350,2000,2900,4000,5700,8000,11500,16500,25000,36500,54500,82500,128000,208000,355000,490000];coins=[40,70,120,200,320,500,720,1000,1400,2000,2800,4000,6000,9000,13000,20000,30000,48000,80000,140000];extra=[10,18,30,50,80,125,180,250,350,500,700,1000,1500,2250,3250,5000,7500,12000,20000,35000]
T['tesouroPorNivel']=[]
for n in range(1,21):
 perm=[{'nivel':n+1,'quantidade':2},{'nivel':n,'quantidade':2}] if n<20 else [{'nivel':20,'quantidade':4}]
 cons=[{'nivel':n+1,'quantidade':2},{'nivel':n,'quantidade':2},{'nivel':n-1,'quantidade':2}] if 2<=n<20 else ([{'nivel':2,'quantidade':2},{'nivel':1,'quantidade':3}] if n==1 else [{'nivel':20,'quantidade':4},{'nivel':19,'quantidade':2}])
 T['tesouroPorNivel'].append({'nivel':n,'valorTotalPo':vals[n-1],'permanentes':perm,'consumiveis':cons,'moedaPo':coins[n-1],'moedaPorPersonagemExtraPo':extra[n-1],'grupoBase':4})
wealth=[15,20,25,30,50,80,125,180,250,350,500,700,1000,1500,2250,3250,5000,7500,12000,20000];lump=[15,30,75,140,270,450,720,1100,1600,2300,3200,4500,6400,9300,13500,20000,30000,45000,69000,112000]
T['riquezaNovoPersonagem']=[]
for n in range(1,21):
 q=[] if n==1 else ([1] if n==2 else ([1,2] if n==3 else ([1,2,1] if n==4 else [1,2,1,2])))
 T['riquezaNovoPersonagem'].append({'nivel':n,'permanentes':[{'nivel':n-1-i,'quantidade':v} for i,v in enumerate(q)],'moedaPo':wealth[n-1],'valorUnicoAlternativoPo':lump[n-1]})
T['infiltracaoAlerta']=[{'pontos':5,'ajusteCdTotal':1,'complicacaoPrimeiraVez':True},{'pontos':10,'ajusteCdTotal':1,'complicacaoPrimeiraVez':True},{'pontos':15,'ajusteCdTotal':2,'complicacaoPrimeiraVez':True},{'pontos':20,'falha':True}]
T['reputacao']=[{'nome':n,'minimo':lo,'maximo':hi,'sobeCom':up,'desceCom':down} for n,lo,hi,up,down in [('Caçados',-50,-30,['moderado','maior'],['maior']),('Odiados',-29,-15,['menor','moderado','maior'],['maior']),('Malvistos',-14,-5,['menor','moderado','maior'],['moderado','maior']),('Ignorados',-4,4,['menor','moderado','maior'],['menor','moderado','maior']),('Apreciados',5,14,['moderado','maior'],['menor','moderado','maior']),('Admirados',15,29,['maior'],['menor','moderado','maior']),('Reverenciados',30,50,['maior'],['moderado','maior'])]]
E=d['equipamentos']
def item(id,nome,nivel,preco,pagina,desc,resumo,categoria='runa',uso='Gravada em item compatível',ativacao='',raridade='comum',**kw):
 a={'id':id,'nome':nome,'nivel':nivel,'precoPo':preco,'preco':f'{preco} po' if preco is not None else 'Sem preço de mercado','pagina':pagina,'fonte':'gm-core','descricao':desc,'resumo':[resumo] if isinstance(resumo,str) else resumo,'categoria':categoria,'uso':uso,'ativacao':ativacao,'raridade':raridade,'automacao':'consulta'};a.update(kw);E.append(a)
for v,n,pr,g in [(1,2,35,'especialista'),(2,10,935,'mestre'),(3,16,8935,'lendário')]:
 item(f'runa-potencia-arma-{v}',f'Runa de potência de arma +{v}',n,pr,236,f'Concede +{v} de item aos ataques da arma e permite {v} runa(s) de propriedade. Fabricar exige {g} em Manufatura. Melhoria cobra diferença entre versões; bônus não somam.',f'+{v} de item ao ataque; até {v} propriedade(s).',bonusAtaqueItem=v,limiteRunasPropriedade=v)
for id,n,pr,dice in [('impactante',4,65,2),('impactante-maior',12,1065,3),('impactante-superior',19,31065,4)]:item('runa-'+id,'Runa '+id.replace('-',' '),n,pr,236,f'Aumenta para {dice} os dados de dano da arma, sem multiplicar modificadores e todos os danos extras. É fundamental e não ocupa propriedade. Melhoria exige fórmula maior e diferença de preço.',f'{dice} dados de dano de arma; não multiplica todos os bônus.',dadosDanoArma=dice)
for v,n,pr,g in [(1,5,160,'especialista'),(2,11,1060,'mestre'),(3,18,20560,'lendário')]:item(f'runa-potencia-armadura-{v}',f'Runa de potência de armadura +{v}',n,pr,226,f'Aumenta em {v} o bônus de item da armadura à CA e permite {v} propriedade(s). Fabricar exige {g} em Manufatura. Precisa investir a armadura; runa fundamental não ocupa propriedade.',f'+{v} à CA de item e até {v} propriedade(s).',bonusCaItem=v,limiteRunasPropriedade=v)
for id,n,pr,v in [('resiliente',8,340,1),('resiliente-maior',14,3440,2),('resiliente-superior',20,49440,3)]:item('runa-'+id,'Runa '+id.replace('-',' '),n,pr,226,f'Enquanto usa a armadura investida, concede +{v} de item às salvaguardas. Não soma com bônus de item à mesma salvaguarda e não ocupa propriedade por ser fundamental.',f'+{v} de item às salvaguardas com armadura investida.',bonusSalvaguardaItem=v)
for id,n,pr,h,hp,bt,mh,mhp,mbt in [('minima',4,75,3,44,22,8,64,32),('menor',7,300,3,52,26,10,80,40),('moderada',10,900,3,64,32,13,104,52),('maior',13,2500,5,80,42,15,120,60),('superior',16,8000,5,84,42,17,136,68),('suprema',19,32000,7,108,54,20,160,80)]:
 item('runa-reforcadora-'+id,'Runa reforçadora '+('mínima' if id=='minima' else id),n,pr,232,f'Aumenta Dureza em {h}, PV em {hp} e Limiar de Quebra em {bt}, com máximos finais de {mh}, {mhp} e {mbt}. Escudos só recebem runa reforçadora, não propriedades ou runas de arma/armadura.',f'+{h} Dureza, +{hp} PV, +{bt} Limiar de Quebra, respeitando limites.',reforco={'dureza':h,'pv':hp,'limiarQuebra':bt,'maxDureza':mh,'maxPv':mhp,'maxLimiarQuebra':mbt},**({'observacaoEditorial':'Fonte imprime +42 LQ com +80 PV; preservado, sem corrigir silenciosamente.'} if id=='maior' else {}))
item('runa-antimagia','Runa antimagia',15,6500,226,'+1 de estado às salvaguardas contra magia. Reação diária quando magia afeta você tenta neutralizar como Dissipar Magia de 7º círculo, modificador +26. Fabricar exige uma conjuração de Dissipar Magia.','+1 contra magia; reação diária neutraliza com círculo 7 e +26.',raridade='incomum',ativacao='Reação; uma vez por dia; gatilho: magia afeta você')
for id,n,pr,v in [('resistente-energia',8,420,5),('resistente-energia-maior',12,1650,10)]:item('runa-'+id,'Runa resistente a energia'+(' maior' if n==12 else ''),n,pr,226,f'Resistência {v} a ácido, frio, eletricidade ou fogo, escolhido ao fabricar. Várias runas desta família coexistem se protegerem contra tipos diferentes; cada uma ocupa propriedade. Não somam resistência ao mesmo tipo.',f'Resistência {v} a uma energia definida na fabricação.',uso='Gravada em armadura')
for id,n,pr,cd in [('fortificacao',12,2000,17),('fortificacao-maior',18,24000,14)]:item('runa-'+id,'Runa de fortificação'+(' maior' if n==18 else ''),n,pr,226,f'Quando receber crítico, faça verificação simples CD {cd}; sucesso transforma em acerto normal. Aumenta Volume em 1 e requisito de Força para reduzir penalidades em 2. Só armadura média ou pesada.',f'CD simples {cd} converte crítico em acerto; aumenta Volume e Força exigida.',uso='Gravada em armadura média ou pesada')
for id,n,pr,freq in [('invisibilidade',8,500,1),('invisibilidade-maior',10,1000,3)]:item('runa-'+id,'Runa de invisibilidade'+(' maior' if n==10 else ''),n,pr,226,f'Uma ação de concentração concede Invisibilidade de 2º círculo por 1 minuto, com suas limitações. {freq} uso(s) por dia. Só armadura leve. Fabricar exige uma conjuração de Invisibilidade.',f'Invisibilidade por 1 minuto, {freq} uso(s) diário(s), uma ação.',uso='Gravada em armadura leve',ativacao='Uma ação; concentração')
item('runa-vestimenta','Runa de vestimenta',5,140,226,'Uma ação de concentração muda aparência da armadura para roupas comuns ou finas imaginadas, sem alterar estatísticas. Só criatura com Visão da Verdade ou equivalente pode desacreditar, CD 25.','Disfarça armadura em roupa, sem mudar estatísticas; CD 25 com visão especial.',uso='Gravada em armadura',ativacao='Uma ação; concentração')
for id,n,pr in [('prontidao',6,200),('prontidao-maior',11,1200)]:
 desc='Veste armadura leve em uma ação ou média/pesada em duas.' if n==6 else 'Veste qualquer armadura gravada em uma ação.'
 item('runa-'+id,'Runa de prontidão'+(' maior' if n==11 else ''),n,pr,226 if n==6 else 227,desc+' As peças se atraem magicamente; estatísticas não mudam.',desc,uso='Gravada em armadura')
for id,n,pr,b in [('sombra',5,55,1),('sombra-maior',9,650,2),('sombra-superior',17,14000,3)]:item('runa-'+id,'Runa de '+id.replace('-',' '),n,pr,227,f'+{b} de item em Furtividade usando armadura leve ou média. Aparência escura e difusa; não soma bônus de item à mesma verificação.',f'+{b} de item em Furtividade com armadura leve ou média.',uso='Gravada em armadura leve ou média')
for id,n,pr,b in [('escorregadia',5,45,1),('escorregadia-maior',8,450,2),('escorregadia-superior',16,9000,3)]:item('runa-'+id,'Runa '+id.replace('-',' '),n,pr,227,f'+{b} de item em Acrobatismo para Escapar e Espremer-se, não em toda utilização da perícia. A superfície parece coberta por óleo fino.',f'+{b} de item para Escapar e Espremer-se.',uso='Gravada em armadura')
item('runa-mudar-tamanho','Runa de mudança de tamanho',7,350,227,'Uma ação de concentração, uma vez por dia, conjura Ampliar ou Encolher no usuário, à escolha. Armadura muda junto; aplique limitações da magia.','Conjura Ampliar ou Encolher, uma vez por dia.',uso='Gravada em armadura',ativacao='Uma ação; concentração; uma vez por dia')
for id,n,pr,greater in [('alada',13,2500,False),('alada-maior',19,35000,True)]:
 desc='Duas ações de concentração e manuseio tornam asas tangíveis, concedendo voo de 7,5 metros ou deslocamento terrestre, o menor. '+('Dura indefinidamente, podendo Dispensar e reativar sem espera.' if greater else 'Uma vez por hora; dura 5 minutos ou até Dispensar. Asas etéreas reaparecem uma hora depois do fim.')
 item('runa-'+id,'Runa '+id.replace('-',' '),n,pr,227,desc,'Voo até 7,5 metros ou deslocamento terrestre, o menor; '+('duração indefinida.' if greater else '5 minutos por hora.'),uso='Gravada em armadura',ativacao='Duas ações; concentração e manuseio')
for id,n,pr,b in [('amedrontadora',5,160,1),('amedrontadora-maior',12,2000,2)]:item('runa-'+id,'Runa '+id.replace('-',' '),n,pr,237,f'Crítico com a arma aplica assustado {b}. Traços emoção, medo, mágico e mental; não ocorre em acerto normal.',f'Acerto crítico deixa alvo assustado {b}.',uso='Gravada em arma')
for name,label,dtype,extra,more in [('flamejante','flamejante','fogo','Crítico causa 1d10 de fogo persistente.','Crítico aumenta persistente para 2d10. Todo fogo da arma, inclusive persistente, ignora resistência.'),('corrosiva','corrosiva','ácido','Crítico causa 3d6 de ácido à armadura, antes da Dureza; escudo erguido sofre em vez dela.','Ignora resistência a ácido; dano à armadura/escudo em crítico passa a 6d6.'),('eletrica','elétrica','eletricidade','Crítico ricocheteia igual dano elétrico em até duas criaturas escolhidas a 3 metros do alvo.','Ignora resistência elétrica do alvo e das criaturas do ricochete.')]:
 for n,pr,gr in [(8,500,False),(15,6500,True)]:item('runa-'+name+('-maior' if gr else ''),'Runa '+label+(' maior' if gr else ''),n,pr,239 if name=='eletrica' else 237,'Golpe bem-sucedido causa +1d6 de '+dtype+'. '+extra+(' '+more if gr else ''),'+1d6 de '+dtype+'; '+(more if gr else extra),uso='Gravada em arma')
for n,pr,gr in [(8,500,False),(15,6500,True)]:
 cd=34 if gr else 24
 item('runa-gelo'+('-maior' if gr else ''),'Runa de gelo'+(' maior' if gr else ''),n,pr,237,f'+1d6 de frio em Golpe. Crítico aplica lento 1 até fim do seu próximo turno, salvo Fortitude CD {cd}.'+(' Frio da arma ignora resistência.' if gr else ''),f'+1d6 frio; crítico exige Fortitude {cd} para evitar lento 1.',uso='Gravada em arma')
 item('runa-trovao'+('-maior' if gr else ''),'Runa trovejante'+(' maior' if gr else ''),n,pr,239,f'+1d6 sônico em Golpe. Crítico exige Fortitude CD {cd}; '+('falha causa surdez permanente. Ignora resistência sônica.' if gr else 'falha causa surdez por 1 minuto, falha crítica por 1 hora.'),f'+1d6 sônico; crítico exige Fortitude {cd} contra surdez.',uso='Gravada em arma')
 item('runa-decadente'+('-maior' if gr else ''),'Runa decadente'+(' maior' if gr else ''),n,pr,237,'+1d4 de vazio no acerto. Crítico causa '+('4d4' if gr else '2d4')+' persistente de vazio ao alvo e ao escudo erguido. Portador rola verificação simples para cessar dano do escudo; mestre rola se sem portador. Corrói também objetos e constructos.'+(' Ignora resistência e imunidade a vazio.' if gr else ''),'+1d4 vazio, '+('4d4' if gr else '2d4')+' persistente no crítico; corrói objetos.',uso='Gravada em arma')
for id,name,n,pr,page,desc,summary,rarity,use,act in [
('toque-fantasma','toque fantasma',4,75,238,'Permite ferir criaturas incorpóreas, conforme suas vulnerabilidades específicas. Incorpóreas podem tocar, segurar e empunhar a arma. Não remove todas as resistências automaticamente.','Atinge e pode ser empunhada por incorpóreos.','comum','Arma',''),
('retornante','retornante',3,55,238,'Depois de Golpe de arremesso, retorna à mão. Se mãos cheias, cai no chão no seu espaço.','Retorna após arremesso; precisa de mão livre.','comum','Arma de arremesso',''),
('afiada','afiada',13,3000,238,'19 natural é crítico somente se resultado total já for sucesso. Não melhora resultado de falha.','19 natural vira crítico apenas se já houver sucesso.','incomum','Arma corpo a corpo perfurante/cortante',''),
('golpe-rapido','golpe rápido',16,10000,238,'Enquanto empunha, fica acelerado, mas ação adicional só para Golpear com esta arma. Não soma várias fontes de acelerado.','Ação extra apenas para Golpear com esta arma.','raro','Arma',''),
('feridora','feridora',7,340,239,'Acerto causa +1d6 persistente de sangramento. Aplique regras de persistente, sem somar fontes do mesmo tipo automaticamente.','+1d6 de sangramento persistente no acerto.','comum','Arma corpo a corpo perfurante/cortante',''),
('transformadora','transformadora',6,225,238,'Uma ação de manuseio transforma em outra arma corpo a corpo com mesmo número básico de mãos. Runas e material permanecem; propriedades incompatíveis ficam suprimidas. Traço duas mãos não altera requisito básico para esta escolha. Não altera mãos atualmente usadas.','Troca a forma mantendo requisito de mãos; propriedades incompatíveis são suprimidas.','comum','Arma corpo a corpo','Uma ação; manuseio'),
('vorpal','vorpal',17,15000,239,'Reação de concentração, morte e incapacitação quando obtiver 20 natural, crítico e dano cortante contra alvo com cabeça. Fortitude CD 37 ou decapitação. Mata quem precisa de cabeça; com várias, normalmente só a última mata.','20 natural e crítico cortante permite reação: Fortitude 37 contra decapitação.','raro','Arma corpo a corpo cortante','Reação; gatilho específico')]:
 item('runa-'+id,'Runa '+name,n,pr,page,desc,summary,raridade=rarity,uso='Gravada em '+use.lower(),ativacao=act)
for n,pr,reach in [(9,700,18),(13,3000,36)]:item('runa-extensora'+('-maior' if n==13 else ''),'Runa extensora'+(' maior' if n==13 else ''),n,pr,237,f'Duas ações de manuseio fazem um Golpe com alcance {reach} metros, somente para esse Golpe. Não muda outros ataques/reação permanentemente.',f'Duas ações: único Golpe com {reach} metros de alcance.',uso='Gravada em arma corpo a corpo',ativacao='Duas ações; manuseio')
for holy in [True,False]:
 id='sagrada' if holy else 'profana';opposite='profano' if holy else 'sagrado'
 desc=f'Golpes ganham traço {id} e +1d4 espiritual, ou +2d4 contra {opposite}. Usuário {opposite} fica enfraquecido 2 carregando ou empunhando. Não aceita arma com traço oposto; fabricar exige você possuir traço compatível. Uma vez por dia, após crítico contra criatura {opposite}, reação de concentração '+('cura você em PV iguais ao dobro do nível do alvo; traços cura e vitalidade.' if holy else 'causa ao alvo sangramento persistente de 1d8 por dado de dano da arma.')
 item('runa-'+id,'Runa '+id,11,1400,238 if holy else 239,desc,'+1d4 espiritual, +2d4 contra oposto; reação diária após crítico.',uso='Gravada em arma compatível',ativacao='Reação; uma vez por dia; gatilho específico')
for n,pr,gr in [(5,150,False),(14,4300,True)]:item('runa-vitalizante'+('-maior' if gr else ''),'Runa vitalizante'+(' maior' if gr else ''),n,pr,239,'Contra mortos-vivos, +'+('2d6' if gr else '1d6')+' de vitalidade persistente. Crítico '+('aplica enfraquecido 1 e estupefato 1 enquanto persistir o dano.' if gr else 'aplica enfraquecido 1 até fim do seu próximo turno.'),'Vitalidade persistente contra mortos-vivos; crítico aplica condições.',uso='Gravada em arma')
for i,(n,pr,dice) in enumerate([(1,4,'1d8'),(3,12,'2d8+5'),(6,50,'3d8+10'),(12,400,'6d8+20'),(18,5000,'8d8+30')]):
 id=['minima','menor','moderada','maior','superior'][i];label='mínima' if id=='minima' else id
 item('pocao-cura-'+id,'Poção de cura '+label,n,pr,259,f'Recupera {dice} PV ao beber com uma ação de manuseio, consumindo a poção. Traços consumível, cura, mágico, poção e vitalidade. Pode alimentar criatura disposta ou indefesa ao alcance.',f'Cura {dice} PV, uma ação e consumo.',categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio',cura=dice)
for circ,pr in enumerate([4,12,30,70,150,300,600,1300,3000,8000],1):item(f'pergaminho-magico-{circ}',f'Pergaminho mágico de {circ}º círculo',circ*2-1,pr,262,f'Guarda uma magia de {circ}º círculo da lista do usuário. Uma mão e ações normais para conjurar usando seu ataque e CD; consumido ao conjurar. Não guarda truques, foco ou rituais. Custos foram pagos ao fabricar e acrescentam ao preço, mas locus continua necessário. Raridade segue a magia. Fabricar exige conjuração de espaço por pergaminho; lotes de quatro têm mesma magia e círculo.',f'Magia de {circ}º círculo usando suas estatísticas, uma única vez.',categoria='pergaminho',uso='Uma mão; Volume leve',ativacao='Conjurar uma Magia; consumido',circulo=circ,magiaEscolhidaObrigatoria=True,observacaoEditorial='Fonte imprime frequência de varinha por erro; seção determina consumo único, sem sobrecarga.')
for circ,pr in enumerate([60,160,360,700,1500,3000,6500,15000,40000],1):item(f'varinha-magica-{circ}',f'Varinha mágica de {circ}º círculo',circ*2+1,pr,282,f'Guarda magia de {circ}º círculo da lista do usuário, sem truques, foco ou rituais. Uma mão e ações normais, usando seu ataque e CD; paga custos e exige locus ao usar. Uma conjuração diária. Segunda pode sobrecarregar: conjura e CD simples 10; sucesso quebra e falha destrói. Nova sobrecarga no mesmo dia destrói sem conjurar, mesmo reparada. Fabricar exige magia de espaço sem custo próprio da magia; raridade segue a magia.',f'Magia de {circ}º círculo por dia; sobrecarga arrisca quebrar ou destruir.',categoria='varinha',uso='Uma mão; Volume leve',ativacao='Conjurar uma Magia; uma vez por dia mais sobrecarga',circulo=circ,magiaEscolhidaObrigatoria=True)
for label,n,pr,damage,cd in [('menor',7,70,'4d6',23),('moderada',12,400,'6d6',29),('maior',17,3000,'10d6',37)]:item('pocao-sopro-energia-'+label,'Poção de sopro de energia '+label,n,pr,259,f'Por 1 hora após beber, ganha ação Sopro de Energia: uma ação causa {damage}, salvaguarda básica CD {cd}; recarga 1d4 rodadas. Tipo definido na criação: ácido/eletricidade linha 9 metros Reflexos; frio/fogo cone 4,5 metros Reflexos; sônico cone 4,5 metros Fortitude. Tem traço da energia.',f'Sopro {damage}, CD {cd}, recarga 1d4 rodadas por 1 hora.',categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação para beber e por sopro')
for id,nome,n,pr,page,desc,summary,rare in [
('lagartixa','lagartixa',1,3,259,'Por 5 minutos, +1 de item para Escalar, Ocultar um Objeto na Mão e CD de Reflexos contra Desarmar. Não vale para todas as utilizações das perícias.','+1 para escalar, ocultar na mão e resistir a Desarmar, 5 minutos.','comum'),
('invisibilidade','invisibilidade',4,20,259,'Recebe Invisibilidade de 2º círculo com duração e limitações da magia.','Invisibilidade de 2º círculo com suas restrições.','incomum'),
('carvalho','carvalho',4,15,259,'Pele engrossa como casca; recebe Resiliência de Carvalho de 2º círculo por 10 minutos.','Resiliência de Carvalho por 10 minutos.','comum'),
('panaceia','panaceia',13,450,259,'Tenta neutralizar todas as maldições e doenças, e cego/surdo causados por magias. Círculo de neutralização 7, modificador +20; não é remoção automática.','Neutralização de círculo 7, +20, contra doenças e maldições.','incomum'),
('fuga-emergencial','fuga emergencial',1,3,259,'Fica em fuga por 1 minuto; +12 metros de estado a todos os deslocamentos enquanto em fuga. Anda imediatamente e continua limitado pela condição.','Em fuga, +12 metros por 1 minuto e Anda imediatamente.','comum'),
('salto','salto',5,21,260,'Por 1 minuto, cada Salto recebe efeito de Saltar de 1º círculo.','Saltar de 1º círculo em cada Salto por 1 minuto.','comum'),
('rapidez','rapidez',8,90,260,'Recebe Acelerar por 1 minuto; ação extra continua limitada pela magia.','Acelerar por 1 minuto, com restrições normais da ação extra.','comum'),
('memorias-compartilhadas','memórias compartilhadas',1,4,260,'Para armazenar, segura e concentra-se 1 minuto em evento, pessoa, lugar ou experiência de aproximadamente 1 minuto. Consumidor lembra vividamente como experiência própria; indisposto pode recusar.','Armazena uma memória breve; consumidor pode recebê-la ou recusar.','comum'),
('fala-universal','fala universal',12,320,260,'Por 4 horas, fala e entende todos os idiomas, sem capacidade de ler suas formas escritas.','Fala e entende todos os idiomas por 4 horas, sem ler.','incomum'),
('indetectabilidade','indetectabilidade',18,4400,260,'Por 10 minutos, impede detecção como Mente Oculta, sem bônus contra efeitos mentais. Também Invisibilidade de 4º círculo protegida contra Ver o Invisível até 8º círculo e CD 36 contra Visão da Verdade.','Impede detecção e concede invisibilidade protegida por 10 minutos.','comum'),
('respirar-na-agua','respirar na água',3,11,260,'Recebe Respirar na Água de 2º círculo por 1 hora.','Respiração aquática por 1 hora.','comum'),
('escudo-temporal','escudo temporal',13,600,261,'Fora do tempo por 2d4 rodadas: não age nem pode ser alvo, imune a tudo e desaparece. Suspende durações atuais. Retorna ao espaço anterior ou desocupado mais próximo e retoma efeitos como se não passou tempo. Novas áreas e mudanças do ambiente afetam você ao voltar.','Sai do tempo por 2d4 rodadas sem agir; volta e retoma durações.','comum'),
('visao-verdade','visão da verdade',16,1500,261,'Recebe Visão da Verdade de 7º círculo, neutralização +25; aplique regras da magia.','Visão da Verdade de 7º círculo com +25.','comum'),
('verdade','verdade',6,46,261,'Vontade CD 19 ao beber, podendo escolher falhar. Sucesso ou crítico não afeta. Falha impede mentir por 10 minutos. Falha crítica também exige Vontade 19 contra perguntas: falha obriga resposta verdadeira se possível; sucesso protege contra repetição da mesma pergunta durante duração.','CD 19 pode impedir mentiras por 10 minutos; crítico falho pode obrigar respostas.','incomum')]:item('pocao-'+id,'Panaceia' if id=='panaceia' else 'Poção de '+nome,n,pr,page,desc+' Beber usa uma ação de manuseio e consome a poção.',summary,categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio',raridade=rare)
for id,n,pr,t in [('voo',8,100,'1 minuto'),('voo-maior',15,1000,'1 hora')]:item('pocao-'+id,'Poção de '+id.replace('-',' '),n,pr,259 if n==8 else 260,f'Concede deslocamento de voo de 12 metros por {t}. Ações e verificações de voo continuam necessárias. Consumida ao beber.',f'Voo 12 metros por {t}.',categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio')
for id,n,pr,t in [('natacao',6,50,'10 minutos'),('natacao-maior',11,250,'1 hora')]:item('pocao-'+id,'Poção de natação'+(' maior' if n==11 else ''),n,pr,260,f'Natação igual ao deslocamento terrestre por {t}. Não concede respiração aquática. Consumida ao beber.',f'Natação igual ao terrestre por {t}, sem respirar na água.',categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio')
for label,n,pr,v in [('menor',6,45,5),('moderada',10,180,10),('maior',14,850,15)]:item('pocao-resistencia-'+label,'Poção de resistência '+label,n,pr,260,f'Resistência {v} por 1 hora a ácido, frio, eletricidade, fogo ou sônico, escolhido na criação, não pelo usuário a cada uso. Consumida ao beber.',f'Resistência {v} a uma energia por 1 hora.',categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio')
for n,pr,gr in [(4,15,False),(8,90,True)]:item('pocao-encolhimento'+('-maior' if gr else ''),'Poção de encolhimento'+(' maior' if gr else ''),n,pr,261,'Encolhe você e equipamento. '+('Após início de 1 minuto, dura 10 minutos.' if not gr else 'Sem início, Encolher de 4º círculo dura 1 hora e concede +2 de item em Furtividade enquanto encolhido.'),'Encolhe usuário e equipamento; '+('10 minutos após início de 1 minuto.' if not gr else '1 hora sem início, +2 em Furtividade.'),categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio')
item('soro-mudanca-sexual','Soro de mudança sexual',7,60,260,'Muda instantaneamente biologia para características sexuais escolhidas, com controle limitado dos detalhes e semelhança com aparência anterior. Nova anatomia saudável e funcional, reprodução conforme ancestralidade. Não pode neutralizar; outro soro reverte ou muda novamente. Sem efeito na gravidez ou ancestralidade sem diferenciação sexual.','Muda características sexuais instantaneamente; outro soro pode reverter.',categoria='poção',uso='Uma mão; Volume leve',ativacao='Uma ação; manuseio')
item('selo-pai-forja','Selo do Pai da Forja',24,None,300,'Criado por Torag para seus artesãos e guerreiros, também tem versões para outras divindades com magia de reação diferente. Em pedra rúnica, soa como martelo em bigorna. Só armadura que comporte duas ou mais propriedades; ocupa dois espaços.\n\nUsando a armadura, resistência a fogo 40, ignora penalidades de verificação e deslocamento; leve/média aumenta bônus de item à CA em 1. Escudo empunhado recupera 10 PV no início de cada turno.\n\nRepulsão Retributiva — reação de manuseio, uma vez por hora, quando atingido por ataque: reduz dano em 100 e conjura Terremoto CD 40 centrado no atacante. Escolhe área do tamanho da criatura até explosão de 18 metros. Versão de Sarenrae usa Explosão Solar.\n\nSelo de Reparação — três ações de manuseio, uma vez por dia: Refazer restaura todos os PV de item ao alcance, mesmo destruído, se maior parte estiver disponível. Inclui mágicos e artefatos do nível do selo ou menor. Reparação automática de escudos fica inativa até preparação diária seguinte.\n\nSacrifício Inabalável — ação livre de concentração, antes de agir no turno: criaturas escolhidas a 18 metros recuperam todos os PV; mortas voltam com metade dos PV máximos. +4 de estado à CA e salvaguardas e cura acelerada 15 por 1 hora. Pode ressuscitar quem exige Desejo ou intervenção divina, mas nesse caso não escolhe outras criaturas. Você vira estátua de pedra ou metal e nunca pode ser restaurado. Selo permanece e pode ser transferido.\n\nDestruição: ressuscitar um semideus maligno com o selo provoca explosão que destrói selo e estátua, apagando todo conhecimento do usuário da existência; o semideus volta. Maligno é a expressão narrativa impressa, sem criar alinhamento na ficha Remaster.',['Resistência a fogo 40, defesa, reparação e reação de Terremoto.','Sacrifício cura ou ressuscita aliados, tornando usuário estátua irreversível.'],categoria='artefato',uso='Armadura; dois espaços de propriedade',ativacao='Reação, três ações ou ação livre, conforme entrada',raridade='raro',somenteMestre=True)
item('espelho-sorshen','Espelho de Sorshen',25,None,301,'Espelho oval de vidro prateado, moldura escura com gemas verdes e duas figuras humanoides. Vincula-se a conjurador lendário em Arcanismo ou Ocultismo. Dono percebe tudo refletido e usa ativações independentemente da distância enquanto vínculo existir.\n\nCriatura inteligente vê imagem pessoalmente atraente, diferente por observador. Cada rodada exige Vontade CD 35 ou fica fascinada. Na falha, encara enquanto visível e, depois, o último lugar por vários minutos. Emoção, incapacitação e visual. Hostilidade contra ela ou aliados não encerra automaticamente: permite Vontade CD 30 para terminar. Mestre pode tornar imune quem for verdadeiramente inocente ou renunciou aos prazeres mundanos.\n\nSegundo Olhar — duas ações de concentração, emoção, incapacitação e visual: força criatura olhando a fazer nova salvaguarda contra fascinação, mesmo após sucesso anterior.\n\nDesejo Irresistível — três ações de concentração, emoção, incapacitação e mental, alvo fascinado: controle por 30 dias como falha crítica contra Dominar. Ver o espelho antes do fim renova por 30 dias desde novo olhar. Sem salvaguarda inicial; CD para libertar-se por ordem contrária à natureza é 35.\n\nDestruição: criatura inteligente e completamente inocente resiste à atração e derruba acidentalmente, quebrando em mil pedaços.',['Vincula conjurador lendário, fascina observadores e controla alvo fascinado por 30 dias.','Destruição exige inocente resistir e derrubá-lo acidentalmente.'],categoria='artefato',uso='Vinculado; Volume leve',ativacao='Duas ou três ações, conforme entrada',raridade='unico',somenteMestre=True)
item('extrator-filosofal','Extrator filosofal',28,None,301,'Arranjo de frascos, tubos e instrumentos, Volume 8; kit alquímico excepcional com +4 de item à Manufatura alquímica. Fabricar nele ou usá-lo na preparação diária com reagentes infundidos cria itens impecáveis: máximo resultado numérico de rolagens, duração dobrada e sem desvantagens.\n\nSíntese Acelerada — três ações de manuseio, uma vez por minuto: cria item alquímico do seu nível ou menor cuja fórmula conheça. Total diário de 56 níveis de itens: dois de nível 19 mais dois de 9, ou oito de 7, por exemplo.\n\nTransmutação da Essência — uma hora de manuseio: filtra ao menos dois terços da massa original de criatura, produzindo mutagênico transmutador. Até dez simultaneamente se massa suficiente. Beber concede por 1 hora habilidade fisiológica escolhida pelo mestre, como sopro, voo, visão no escuro, presença aterradora ou imunidade a sono. Não concede magia/conjuração. Usa CD de classe ou magia do consumidor, a maior.\n\nPodem coexistir vários, ao contrário de mutagênicos/polimorfia comuns. Diferentes espécies dão suas habilidades; doses da mesma espécie dão habilidade adicional e +1 hora de duração para aquele tipo. Com outro ativo, após beber faz CD simples igual ao total ativo. Falha transforma completamente na espécie da dose mais recente e quase sempre provoca fúria descontrolada; mestre decide memórias e personalidade restantes.\n\nDestruição: introduzir simultaneamente partes grandes de éon, anjo, arconte, azata, daemon, demônio, diabo, proteano e psicopompo, todos nível 14+, com pedra filosofal, faz explodir. Criaturas a 18 metros fazem Reflexos CD 55 ou mistura as transforma em combinação de ao menos duas criaturas usadas.',['Produz alquimia impecável e até 56 níveis de itens por dia.','Mutagênicos fisiológicos coexistem, com risco de transformação descontrolada.'],categoria='artefato',uso='Volume 8; kit alquímico',ativacao='Três ações por síntese ou uma hora por transmutação',raridade='raro',somenteMestre=True,observacaoEditorial='Fonte cita reagentes infundidos anteriores à revisão do alquimista em Player Core 2. Preservado para consulta, sem converter automaticamente a novos recursos.')
item('serithtial','Serithtial',23,None,302,'Iomedae teria forjado esta espada inteligente: bastarda +4 impactante superior sagrada, Volume 1, uma mão em forma básica. Aço também conta como ferro frio e prata. Percepção +28; visão/audição normais 18 metros; empatia só com parceiro; Saber de Iomedae +29, Religião +26, Saber de Zon-Kuthon +29; INT +2, SAB +1, CAR +2, Vontade +30.\n\nLuz de tocha pode ser suspensa/retomada por você ou espada com uma ação de concentração. +2d6 de dano contra adoradores de Zon-Kuthon. Empunhando, contra efeitos de seguidores dele recebe Movimento Desimpedido, +4 de estado contra morte/vazio, resistência vazio 10 e suprime condenado. Proteções têm limite de fonte do efeito.\n\nSem portador, volta a bastarda. Detecta preferência e usa ação para virar adaga, espada curta/longa, cimitarra, falcione, espada de duas mãos, rapieira ou bastarda quando empunhada. Usuário pode pedir outra forma por ação de concentração; ela usa ação para mudar.\n\nAceita parceiro dedicado a derrotar Kazavon e Zon-Kuthon. Se abandonar objetivos, tenta tomar corpo: Vontade CD 45 para resistir, normalmente controla até achar parceiro melhor; nova salvaguarda a cada dia.\n\nGraça da Herdeira — concentração, uma vez por hora: a espada usa ações apropriadas e conjura Curar de 9º círculo ou Anel da Verdade, CD 45.\n\nDestruição: Kazavon ou grande dragão das sombras adorador de Zon-Kuthon usa sopro sobre a espada não empunhada, derretendo em ferro comum.',['Espada inteligente +4 com poderes contra seguidores de Zon-Kuthon.','Pode curar e tentar controlar portador que abandone sua missão.'],categoria='artefato',uso='Uma mão; Volume 1; inteligente',ativacao='Ações e ativações da espada conforme entrada',raridade='unico',somenteMestre=True,observacaoEditorial='Potência +4 é exceção do artefato, não quarta versão comum de runa.')
item('projetil-primeiro-cofre','Projétil do Primeiro Cofre',23,None,303,'Munição de Abadar que adapta-se a qualquer arma à distância ao ser pega e reconhece dono até outra criatura pegá-la. Dono pode ativar após disparo. Em vez de rolar dados da arma, usa 25 como resultado e soma bônus/danos adicionais; tipo é o normal.\n\nAo danificar, fragmenta e ricocheteia contra outros inimigos a 9 metros com mesmo bônus de ataque. Fragmentos ficam presos, causando desajeitado 2. Remover exige três Interagir no total em si ou adjacente, ou uma ação com Medicina CD 30; crítico falho causa 10 de sangramento persistente.\n\nOrdem de Recarga — uma ação de concentração: volta e recarrega a arma; fragmentos presos arrancam-se causando 15 de sangramento persistente aos alvos antes de se reunir.\n\nDepósito no Cofre — três ações de manuseio, carregado ou à mão se recarga 0: faz Golpe e tenta levar alvo ao Cofre. Salvo crítico falho do ataque, Reflexos CD 45 com incapacitação. Crítico: sem efeito. Sucesso: move 1d20 × 15 metros na direção do tiro; colisão sólida causa 50 contundente. Falha: lugar aleatório em Axis. Falha crítica: Primeiro Cofre, provavelmente sem escapar sozinho. Projétil retorna ao Cofre independentemente do resultado.\n\nDestruição: dez projéteis acertam o mesmo grupo de proteanos keketar ou izfiitar em até 1 minuto e são chamados de volta; colidem ao recompor e viram pó.',['Usa 25 nos dados da arma e ricocheteia, deixando fragmentos.','Pode recarregar a si mesmo ou transportar alvo a Axis/Primeiro Cofre.'],categoria='artefato',uso='Munição de qualquer arma à distância',ativacao='Uma ação para recarga; três para depósito',raridade='raro',somenteMestre=True)
# Regras canônicas: selecionar referência não aplica efeito. Runas exigem o item-base equipado.
for entrada in E:
    entrada['automatizavel'] = False
    entrada['mecanica'] = {'versao':1, 'tipo':'referencia', 'estado':'nao-implementado', 'motivo':'Efeito específico ainda sem executor completo; leitura disponível, sem conceder efeito calculado por aproximação.'}
    identidade = entrada['id']
    categoria = familia = None
    valor = None
    if identidade.startswith('runa-potencia-arma-'):
        categoria, familia, valor = 'arma', 'potencia', entrada['bonusAtaqueItem']
    elif identidade.startswith('runa-impactante'):
        categoria, familia, valor = 'arma', 'impactante', entrada['dadosDanoArma']
    elif identidade.startswith('runa-potencia-armadura-'):
        categoria, familia, valor = 'armadura', 'potencia', entrada['bonusCaItem']
    elif identidade.startswith('runa-resiliente'):
        categoria, familia, valor = 'armadura', 'resiliente', entrada['bonusSalvaguardaItem']
    elif identidade.startswith('runa-reforcadora-'):
        categoria, familia = 'escudo', 'reforcadora'
    if familia:
        entrada['tipo'] = 'runa'
        entrada['mecanica'] = {'versao':1,'tipo':'runa','estado':'dados-revisados','categoria':categoria,'familia':familia,'valor':valor,'exigeBase':True,'exigeInvestimento':categoria=='armadura','aplicacao':'passiva','tipoBonus':'item'}
        if familia == 'reforcadora':
            entrada['mecanica']['reforco'] = entrada['reforco'].copy()
            entrada['mecanica']['valor'] = entrada['reforco']['dureza']
        entrada['automatizavel'] = identidade != 'runa-reforcadora-maior'
        entrada['automacao'] = 'estruturada' if entrada['automatizavel'] else 'pendente-errata'
        if not entrada['automatizavel']:
            entrada['mecanica']['estado'] = 'pendente-errata'
            entrada['mecanica']['motivo'] = 'Limiar de Quebra da fonte diverge de seus PV. Não aplicar valores por aproximação ou correção silenciosa.'
    elif identidade.startswith('pocao-cura-'):
        dados = re.fullmatch(r'(\d+)d(\d+)(?:\+(\d+))?',entrada['cura'])
        entrada['tipo'] = 'consumivel'
        entrada['automatizavel'] = True
        entrada['automacao'] = 'estruturada'
        entrada['mecanica'] = {'versao':1,'tipo':'consumivel','estado':'dados-revisados','categoria':'pocao','acao':'curar','aplicacao':'ao-usar','acoes':1,'consomeQuantidade':1,'exigeAlvo':True,'alvo':'usuario-ou-criatura-disposta-ou-indefesa-ao-alcance','cura':{'expressao':entrada['cura'],'quantidadeDados':int(dados[1]),'facesDados':int(dados[2]),'fixo':int(dados[3] or 0)},'tracos':['manuseio','consumivel','cura','magico','pocao','vitalidade']}

d['fonte']['entradasEquipamentoRevisadas']=len(E)
d['fonte']['paginasConsultaRevisadas']=sorted({x['pagina'] for x in d['secoes']})
d['fonte']['creditos']='Pathfinder GM Core © 2023 Paizo Inc. Projeto de Logan Bonner e Mark Seifter. Adaptação de consulta em português a partir do PDF enviado, sem afirmar tradução oficial.'
d['fonte']['licenca']={'nome':'ORC','avisoOriginal':'docs/pathfinder/gm-core/ORC-aviso-original.txt','resumoPt':'O livro licencia seu Material Licenciado sob ORC e reserva marcas, nomes próprios, ilustrações, personagens e narrativa. O aviso original é preservado; tradução não altera titularidade.'}
assert len(d['secoes'])==36,len(d['secoes'])
assert len(E)==120,len(E)
assert len({a['id'] for a in E})==len(E)
assert all(re.fullmatch('[a-z0-9-]+',x['id']) for x in E+d['secoes'])
assert all(x['resumo'] and not any('…' in t or '...' in t for t in x['resumo']) for x in E+d['secoes'])
assert all(len(x['descricao'])>40 for x in E)
(R/'public/pathfinder/gm-core.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
print(f"GM Core reconstruído: {len(d['secoes'])} seções, {len(E)} equipamentos, {sum(isinstance(v,list) for v in T.values())} tabelas.")
