"""Os 23 blocos de veículos das páginas 213–217, em português."""
def ampliar(d):
    def v(id,nome,nivel,preco,pagina,tamanho,espaco,tripulacao,passageiros,pilotagem,ca,fort,dureza,pv,lq,movimento,dano,cd,especial='',raridade='comum',fraqueza=''):
        texto=f'Tamanho {tamanho}; espaço {espaco}; tripulação {tripulacao}; passageiros {passageiros}. Pilotagem: {pilotagem}. CA {ca}, Fortitude +{fort}, Dureza {dureza}, PV {pv}, Limiar de Quebra {lq}. Imunidades de objetos. Deslocamento: {movimento}. Colisão: {dano} contundente, Reflexos básico CD {cd}.'
        if fraqueza:texto+=' Fraqueza: '+fraqueza+'.'
        if especial:texto+='\n\n'+especial
        texto+='\n\nVeículo usa ações do piloto e direção própria; não é criatura ou montaria. Se precisar de salvaguarda não listada, piloto faz pilotagem contra a mesma CD. Quebrado recebe −2 à CA, salvaguardas e CD de colisão, +5 às CDs de pilotagem e metade do deslocamento.'
        d['equipamentos'].append({'id':'veiculo-'+id,'nome':nome,'nivel':nivel,'precoPo':preco,'preco':str(preco)+' po','pagina':pagina,'fonte':'gm-core','categoria':'veiculo','uso':'Pilotagem e tripulação conforme bloco','raridade':raridade,'descricao':texto,'resumo':[f'{tamanho}; {passageiros} passageiro(s); {movimento}.','Pilotagem, defesa e colisão têm valores próprios; não concede ações de criatura.'],'mecanica':{'versao':1,'tipo':'veiculo','estado':'dados-revisados-sem-executor','ca':ca,'fortitude':fort,'dureza':dureza,'pv':pv,'limiarQuebra':lq,'colisao':{'expressao':dano,'cdReflexos':cd}},'automacao':'consulta','automatizavel':False,'somenteMestre':True})
    lento='Lento para virar: precisa mover duas vezes seu comprimento para cada giro de 90 graus.'
    manobravel='Com todos os remadores habilidosos, pode girar no lugar ou antes de um comprimento, pagando +1,5 m por giro de 90 graus. Pode remar para trás até metade do deslocamento, sem girar enquanto recua.'
    v('dirigivel','Dirigível',12,6000,213,'Imenso','27 × 9 × 18 m','1 piloto e 5 outros',15,'Arcanismo, Manufatura ou Natureza CD 32; Saber de Pilotagem CD 30',28,22,20,210,105,'voo 15 m, alquímica ou mágica','9d10',30,lento,'raro','fogo 15 até ficar quebrado')
    v('planador','Planador',0,15,214,'Grande','1,5 × 3 × 0,6 m','1 piloto',0,'Saber de Pilotagem CD 14 ou Natureza CD 16',10,6,0,16,8,'voo 7,5 m, vento','2d4',14,'Decolagem exige lançar-se de inclinação íngreme com vento favorável. Começa sem controle, caindo 18 m por rodada até piloto Assumir Controle; atingir chão antes causa dano de queda ao veículo e piloto.','incomum','fogo 5')
    v('balao','Balão de ar quente',2,100,214,'Enorme','4,5 × 4,5 × 15 m','1 piloto',5,'Saber de Pilotagem CD 16 ou Natureza CD 18',13,8,0,40,20,'voo 6 m, vento','2d8',16,'À deriva: não tem direção própria e depende de correntes favoráveis. Ao perder controle, vento carrega até quatro vezes seu deslocamento por rodada, conforme mestre.','incomum','fogo 10')
    for id,nome,nivel,preco,espaco,passag,pilo,ca,fort,dur,pv,lq,dano,cd,pux in [('aereo-leve','Carro aéreo leve',7,1000,'3 × 4,5 × 2,4 m',1,'Arcanismo CD 25, Natureza CD 25–33 conforme puxador, Saber de Pilotagem CD 23',20,14,15,80,40,'5d10',23,'2 Grandes ou 1 Enorme'),('aereo-medio','Carro aéreo médio',10,3000,'3 × 6 × 2,4 m',3,'Arcanismo CD 29, Natureza CD 29–37 conforme puxador, Saber de Pilotagem CD 27',25,19,15,160,80,'7d10',27,'4 Grandes, 2 Enormes ou 1 Imenso'),('aereo-pesado','Carro aéreo pesado',13,9000,'6 × 6 × 2,4 m',7,'Arcanismo CD 33, Natureza CD 33–41 conforme puxador, Saber de Pilotagem CD 31',29,23,20,230,115,'9d10',31,'6 Grandes, 2 Enormes ou 1 Imenso')]:
        v(id,nome,nivel,preco,214,'Grande' if nivel==7 else 'Enorme',espaco,'1 piloto',passag,pilo,ca,fort,dur,pv,lq,'voo igual ao puxador mais lento; tração por '+pux,dano,cd,'Também imune a críticos e dano de precisão. Puxadores precisam voar, como morcegos gigantes, grifos, hipogrifos, dracos ou pterossauros.','incomum')
    v('carruagem','Carruagem',2,100,214,'Grande','3 × 3 × 2,1 m','1 piloto',4,'Saber de Condução CD 16; Natureza CD 18–26 conforme puxador',13,8,5,40,20,'puxador mais lento; tração por 2 Grandes','2d8',16)
    v('carroca','Carroça',0,3,215,'Grande','3 × 1,5 × 1,2 m','1 piloto',1,'Saber de Condução CD 14; Natureza CD 16–24 conforme puxador',10,6,5,14,7,'puxador; tração por 1 Grande','1d10',14)
    v('carro-pesado','Carro de guerra pesado',3,150,215,'Grande','3 × 3 × 1,2 m','1 piloto',3,'Saber de Condução CD 18; Natureza CD 20–28 conforme puxador',14,9,5,40,20,'puxador mais lento; tração por 2 Grandes','2d10',18)
    v('carro-leve','Carro de guerra leve',0,10,215,'Grande','1,5 × 1,5 × 1,2 m','1 piloto',0,'Saber de Condução CD 14; Natureza CD 16–24 conforme puxador',10,6,5,14,7,'puxador; tração por 1 Grande','1d12',14)
    v('treno-estreito','Trenó estreito',0,3,215,'Médio','1,5 × 0,3 × 0,9 m','1 piloto',0,'Saber de Condução CD 14; Natureza CD 16–24 conforme puxador',10,6,5,14,7,'puxador mais lento; tração por 2 Médios ou 4 Pequenos','1d12',14,'Gelo e neve não são terreno difícil; todo outro terreno é difícil. '+lento)
    v('treno','Trenó',1,50,215,'Grande','3 × 1,5 × 1,2 m','1 piloto',1,'Saber de Condução CD 15; Natureza CD 17–25 conforme puxador',11,7,5,18,9,'puxador mais lento; tração por 2 Grandes ou 6 Médios','2d6',15,'Gelo e neve não são terreno difícil; todo outro terreno é difícil. '+lento)
    v('gigante-vapor','Gigante a vapor',14,12500,216,'Enorme','6 × 6 × 7,5 m','1 piloto e 3 outros',4,'Saber de Condução CD 32; Manufatura CD 34',33,28,20,200,100,'6 m, alquímica','10d10',29,'Jato de Chamas: dois tripulantes gastam três ações cada em seus turnos; no fim do turno do segundo, cone de 9 m de qualquer canto do veículo causa 6d8 fogo, Reflexos básico CD 32. Não funciona quebrado.','raro')
    v('andador','Andador',7,1200,216,'Grande','3 × 3 × 7,5 m','1 piloto',2,'Arcanismo ou Manufatura CD 25; Saber de Engenharia ou Pilotagem CD 23',24,13,10,120,60,'9 m, alquímica ou mágica','3d10',24,'Passo Longo: ao Andar, pode atravessar vão de até 9 m.','incomum')
    v('velocipede','Velocípede',1,60,216,'Médio','1,5 × 0,6 × 1,2 m','1 piloto',0,'Atletismo CD 15; Saber de Pilotagem CD 17',11,6,5,15,7,'igual ao piloto; pedalado, tratado como remado','1d8',15,'Frágil: terreno difícil acrescenta 2 à CD e traço imprudente ao Conduzir. Portátil: Médio pode puxar pela roda no chão, ficando sobrecarregado.','incomum')
    v('vagao','Vagão',1,25,216,'Grande','3 × 3 × 2,1 m','1 piloto',4,'Saber de Condução CD 15; Natureza CD 17–25 conforme puxador',11,7,5,18,9,'puxador mais lento; tração por 2 Grandes','2d6',15)
    v('batisfera','Batisfera',5,480,216,'Grande','4,5 × 4,5 × 4,5 m','1 piloto',4,'Manufatura CD 22; Saber de Engenharia ou Pilotagem CD 20',18,12,10,80,40,'natação 6 m, alquímica, somente submersa','2d10',20,'Cabo de superfície limita movimento vertical. Soltar Lastro: duas ações do piloto; sobe três vezes deslocamento ao fim do turno. Boia de ar permite respirar submerso até 150 m de profundidade.','incomum')
    v('cutter','Cúter',6,750,216,'Enorme','9 × 4,5 × 6 m','1 piloto e 3 outros',6,'Natureza CD 24; Saber de Navegação CD 22',19,14,10,100,50,'natação 9 m, vento','4d10',22,lento,fraqueza='fogo 10 até ficar quebrado')
    v('gale','Galé',10,3000,217,'Imenso','39 × 6 × 7,5 m','1 piloto e 20 remadores',6,'Saber de Navegação CD 27; Diplomacia ou Intimidação CD 29',25,19,15,170,85,'natação 9 m, remos ou vento','7d10',27,manobravel,fraqueza='fogo 15 até ficar quebrado')
    v('dracar','Dracar',8,1500,217,'Imenso','19,5 × 4,5 × 7,5 m','1 piloto e 10 remadores',4,'Saber de Navegação CD 26; Diplomacia ou Intimidação CD 28',21,16,15,140,70,'natação 12 m, remos ou vento','6d10',24,manobravel,fraqueza='fogo 15 até ficar quebrado')
    porte='Pode ser carregado em terra por dois Médios ou um Grande, que ficam sobrecarregados.'
    v('jangada','Jangada',-1,3,217,'Grande','3 × 3 × 0,6 m','1 piloto',4,'Atletismo CD 14; Saber de Navegação CD 12',10,5,1,16,8,'natação 3 m, remos','1d4',14,porte)
    v('barco-remos','Barco a remos',0,15,217,'Grande','3 × 1,5 × 0,9 m','1 piloto',2,'Atletismo CD 16; Saber de Navegação CD 14',10,6,5,16,8,'natação 6 m, remos','2d4',14,porte)
    v('veleiro','Veleiro',9,2000,217,'Imenso','22,5 × 6 × 7,5 m','1 piloto e 8 outros',10,'Saber de Navegação CD 26; Diplomacia ou Intimidação CD 28',23,18,15,150,75,'natação 12 m, vento','6d10',26,lento,fraqueza='fogo 15 até ficar quebrado')
    assert sum(e.get('categoria')=='veiculo' for e in d['equipamentos'])==23
