import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validarCadastro,validarConcessao,apresentarAcervo,conferirQuantidade,conferirRetirada,mesmoPedido} from './regras.ts';
const cadastro={nome:'Retrato',descricao:'Uma descoberta.',categoria:'sapos',localizacaoMestre:'Sala secreta',imagemUrl:null,repetivel:true,retratoAnimado:true};
test('cadastro limita categoria, campos, imagens e retratos',()=>{assert.equal(validarCadastro(cadastro).nome,'Retrato');for(const imagemUrl of ['javascript:alert(1)','data:image/svg+xml,abc','//externo.test/arte','arquivo.png','https://usuario:senha@host.test/x'])assert.throws(()=>validarCadastro({...cadastro,imagemUrl}));for(const imagemUrl of ['/arte.svg','https://example.com/arte.webp'])assert.equal(validarCadastro({...cadastro,imagemUrl}).imagemUrl,imagemUrl);assert.throws(()=>validarCadastro({...cadastro,categoria:'__proto__'}));assert.throws(()=>validarCadastro({...cadastro,nome:'x'.repeat(161)}));assert.throws(()=>validarCadastro({...cadastro,repetivel:'true'}));assert.throws(()=>validarCadastro({...cadastro,categoria:'reliquias'}));});
test('desconhecidos não contêm spoilers; localização é sempre privada',()=>{const a={...validarCadastro(cadastro),id:'1'},b={...a,id:'2',nome:'SEGREDO',descricao:'SEGREDO',imagemUrl:'https://secret.test/segredo'};const r=apresentarAcervo([a,b],[{colecionavelId:'1',quantidade:3,descobertoEm:new Date('2026-10-09')}]);assert.deepEqual(r.itens[1],{id:'2',categoria:'sapos',adquirido:false,quantidade:0});assert.ok(!JSON.stringify(r).includes('SEGREDO'));assert.ok(!JSON.stringify(r).includes('Sala secreta'));assert.equal(r.progresso[0].descobertos,1);assert.equal(r.progresso[0].exemplares,3);assert.equal(r.progresso[0].total,2);});
test('exemplares únicos e repetidos respeitam limites',()=>{assert.equal(conferirQuantidade(false,0,1),1);assert.throws(()=>conferirQuantidade(false,1,1));assert.throws(()=>conferirQuantidade(false,0,2));assert.equal(conferirQuantidade(true,3,2),5);assert.throws(()=>conferirQuantidade(true,999,1));});
test('concessão exige IDs e quantidade inteira; idempotência liga ator e pedido',()=>{const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';const c={operacaoId:id,personagemId:id,colecionavelId:id,quantidade:2};assert.equal(validarConcessao(c).quantidade,2);for(const quantidade of [0,-1,1.5,100,'2'])assert.throws(()=>validarConcessao({...c,quantidade}));assert.throws(()=>validarConcessao({...c,personagemId:'teste'}));assert.ok(mesmoPedido({...c,concedidoPorId:id},c,id));assert.ok(!mesmoPedido({...c,concedidoPorId:'outro'},c,id));assert.ok(!mesmoPedido({...c,concedidoPorId:id},{...c,quantidade:1},id));});

test('visibilidade oculta não revela IDs nem contagem; revelada entra no progresso',()=>{const c={...validarCadastro({...cadastro,visibilidade:'oculto',raridade:'Rara',edicao:'1890',origemRevelada:'Hogsmeade',segredoMestre:'SEGREDO'}),id:'oculto'};const vazio=apresentarAcervo([c],[]);assert.equal(vazio.itens.length,0);assert.equal(vazio.progresso[0].total,0);const r=apresentarAcervo([c],[{colecionavelId:c.id,quantidade:1,descobertoEm:new Date()}]);assert.equal(r.progresso[0].total,1);assert.equal(r.itens[0].adquirido,true);assert.ok(JSON.stringify(r).includes('Hogsmeade'));assert.ok(!JSON.stringify(r).includes('SEGREDO'));assert.throws(()=>validarCadastro({...cadastro,visibilidade:'publico'}));});
test('retirada impede saldo negativo e idempotência diferencia tipos',()=>{assert.equal(conferirRetirada(3,2),1);assert.equal(conferirRetirada(1,1),0);assert.throws(()=>conferirRetirada(0,1));assert.throws(()=>conferirRetirada(2,3));const p={personagemId:'p',colecionavelId:'c',quantidade:1};assert.ok(!mesmoPedido({...p,tipo:'conceder',concedidoPorId:'u'},{...p,tipo:'retirar'},'u'));});
