"use client";

import { useCallback, useEffect, useState } from "react";

type Segredo={id:string;nome:string;descricao:string;reveladoEm:string|null};
type Familia={id:string;nome:string;tipo:string;condicaoFinanceira:string;tags:string[];conteudoFamiliar:string;acessoFamiliar:string;herancas:unknown;membros:{personagemId:string;personagem:{nome:string}}[];segredos:Segredo[]};

export function FamiliasHogwarts({campanhaId,ehMestre}:{campanhaId:string;ehMestre:boolean}){
  const [familias,setFamilias]=useState<Familia[]>([]),[erro,setErro]=useState(""),[carregando,setCarregando]=useState(true),[enviando,setEnviando]=useState(false),[aberta,setAberta]=useState<string|null>(null);
  const carregar=useCallback(async()=>{setErro("");try{const r=await fetch(`/api/campanhas/${campanhaId}/hogwarts-familias`,{cache:"no-store"}),c=await r.json();if(!r.ok)throw new Error(c.erro||"Não foi possível carregar.");setFamilias(c.familias||[]);}catch(e){setErro(e instanceof Error?e.message:"Não foi possível carregar as famílias.");}finally{setCarregando(false);}},[campanhaId]);
  useEffect(()=>{const inicio=window.setTimeout(()=>void carregar(),0);return()=>window.clearTimeout(inicio);},[carregar]);
  async function enviar(corpo:object){setEnviando(true);setErro("");try{const r=await fetch(`/api/campanhas/${campanhaId}/hogwarts-familias`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(corpo)}),c=await r.json();if(!r.ok)throw new Error(c.erro||"Não foi possível salvar.");await carregar();}catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setEnviando(false);}}
  return <section className="border-t border-ambar/25 px-4 py-5"><h3 className="font-titulo text-lg text-texto">Famílias e Heranças</h3><p className="text-xs text-texto-suave">Um único registro compartilhado por todos os irmãos da campanha.</p>
    {carregando&&<p className="mt-3 text-sm text-texto-suave">Carregando famílias…</p>}{erro&&<div role="alert" className="mt-3 rounded border border-red-400/40 bg-red-950/30 p-2 text-sm text-red-100">{erro}</div>}
    {!carregando&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{familias.map(f=><article key={f.id} className="rounded-lg border border-ambar/25 bg-fundo/50 p-3"><button onClick={()=>setAberta(aberta===f.id?null:f.id)} className="w-full text-left"><b className="text-texto">{f.nome}</b><span className="ml-2 text-xs text-texto-suave">{f.tipo} · {f.membros.length} membro(s)</span></button>{aberta===f.id&&<div className="mt-3 space-y-2 text-xs text-texto-suave"><div>{f.tags.map(t=><span key={t} className="mr-1 inline-block rounded-full border border-ambar/25 px-2 py-0.5">{t}</span>)}</div><p><b className="text-texto">Conteúdo:</b> {f.conteudoFamiliar}</p><p><b className="text-texto">Acesso:</b> {f.acessoFamiliar}</p>{f.membros.length>0&&<p><b className="text-texto">Membros:</b> {f.membros.map(m=>m.personagem.nome).join(", ")}</p>}<div>{f.segredos.map(s=><div key={s.id} className="mt-2 rounded border border-ambar/15 p-2"><b className="text-texto">{s.nome}</b>{(ehMestre||s.reveladoEm)&&<p>{s.descricao}</p>}{ehMestre&&!s.reveladoEm&&<button disabled={enviando} onClick={()=>void enviar({acao:"revelar",segredoId:s.id})} className="mt-1 rounded border border-ambar/30 px-2 py-1">Revelar à família</button>}</div>)}</div>{ehMestre&&<form className="grid gap-2" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void enviar({acao:"segredo",familiaId:f.id,nome:fd.get("nome"),descricao:fd.get("descricao")});e.currentTarget.reset();}}><input required name="nome" placeholder="Nome do segredo" className="rounded border border-ambar/30 bg-fundo px-2 py-1.5 text-texto"/><textarea required name="descricao" placeholder="Verdade completa — só o Mestre vê até revelar" className="rounded border border-ambar/30 bg-fundo px-2 py-1.5 text-texto"/><button disabled={enviando} className="rounded border border-ambar/30 px-2 py-1.5 text-ambar-forte">Guardar segredo</button></form>}</div>}</article>)}</div>}
    {ehMestre&&<details className="mt-4"><summary className="cursor-pointer text-sm text-ambar-forte">Criar família compartilhada</summary><form className="mt-3 grid gap-2 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);void enviar({acao:"criar",nome:fd.get("nome"),tipo:fd.get("tipo"),condicaoFinanceira:fd.get("condicao"),tags:String(fd.get("tags")||"").split(","),conteudoFamiliar:fd.get("conteudo"),acessoFamiliar:fd.get("acesso"),herancas:[fd.get("h1"),fd.get("h2"),fd.get("h3")].filter(Boolean)});e.currentTarget.reset();}}><input required name="nome" placeholder="Nome da família" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><input name="tipo" placeholder="Tipo: Original, Canônica…" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><input name="condicao" placeholder="Condição financeira" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><input name="tags" placeholder="Tags separadas por vírgula" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><textarea required name="conteudo" placeholder="Conteúdo Familiar" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><textarea required name="acesso" placeholder="Acesso Familiar" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><input name="h1" placeholder="Herança I — opcional" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><input name="h2" placeholder="Herança II — opcional" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><input name="h3" placeholder="Herança III — opcional" className="rounded border border-ambar/30 bg-fundo px-3 py-2 text-texto"/><button disabled={enviando} className="rounded border border-ambar/60 bg-ambar/15 px-4 py-2 text-ambar-forte sm:col-span-2">{enviando?"Salvando…":"Criar para toda a campanha"}</button></form></details>}
  </section>;
}
