import test from "node:test";
import assert from "node:assert/strict";
import { novaFicha, calcularFicha, prepararFichaWandsWizards, ganhosDoNivel } from "../../../public/wands-wizards/ficha-regras.mjs";
test("casa aplica bônus distintos e cálculos usam atributo do estilo",()=>{const d=novaFicha();const c=calcularFicha(d);assert.equal((c.atributos as Record<string,number>).constituicao,11);assert.equal((c.atributos as Record<string,number>).destreza,11);assert.equal(c.pvMaximos,10);assert.equal(c.ca,13);assert.equal(c.cdMagia,10);});
test("recusa compra acima de 27 e bônus da casa duplicado",()=>{const d=novaFicha();d.base={forca:15,destreza:15,constituicao:15,inteligencia:15,sabedoria:15,carisma:15};assert.match(prepararFichaWandsWizards({},d).erro!,/27/);d.base=novaFicha().base;d.bonusCasa="carisma";assert.match(prepararFichaWandsWizards({},d).erro!,/outro atributo/);});
test("salvamento substitui valores derivados forjados e não conclui criação parcial",()=>{const d=novaFicha();d.calculos={ca:999};const result=prepararFichaWandsWizards({},d);assert.equal(result.erro,undefined);assert.equal((result.dados!.calculos as Record<string,number>).ca,13);assert.equal(result.dados!.criacaoFinalizada,false);assert.deepEqual(result.dados!.resumoVida,{atual:10,maxima:10});});
test("prévia não aceita progressão inventada ou PV fora do cálculo",()=>{const d=novaFicha();d.nivel=2;assert.match(prepararFichaWandsWizards({},d).erro!,/nível 1/);d.nivel=1;d.vida={atual:999};assert.match(prepararFichaWandsWizards({},d).erro!,/PV/);});

test("prévia recusa IDs de magia inventados",()=>{const d=novaFicha();d.magias=["magia-inexistente"];assert.match(prepararFichaWandsWizards({},d).erro!,/seleção regular/);});

test("progressão aplica proficiência, PV e espaços de conjurador completo",()=>{const d=novaFicha();d.nivel=5;const c=calcularFicha(d);assert.equal(c.proficiencia,3);assert.equal(c.pvMaximos,34);assert.deepEqual(c.espacosPorCirculo,[4,3,2]);assert.equal(c.magias,8);assert.equal(c.pontosFeiticaria,5);});
test("evolução de campanha exige mestre e não permite saltos",()=>{const d=novaFicha(),next={...d,nivel:2};assert.match(prepararFichaWandsWizards(d,next,{emCampanha:true,ehMestre:false}).erro!,/mestre/);assert.equal(prepararFichaWandsWizards(d,next,{emCampanha:true,ehMestre:true}).erro,undefined);assert.match(prepararFichaWandsWizards(d,{...d,nivel:3}).erro!,/um nível/);});
test("aprimoramento de Constituição recalcula PV anteriores e protege o limite 20",()=>{const d=novaFicha();d.nivel=4;d.aumentos=[{nivel:4,atributos:{constituicao:2}}];const c=calcularFicha(d);assert.equal(c.pvMaximos,32);d.nivel=19;d.aumentos=[4,8,12,16,19].map(nivel=>({nivel,atributos:{constituicao:2}}));assert.throws(()=>calcularFicha(d),/20/);});
test("tabela de nível 20 possui 22 espaços e limites por estilo",()=>{const d=novaFicha();d.nivel=20;d.estilo="tecnica";const c=calcularFicha(d);assert.equal((c.espacosPorCirculo as number[]).reduce((a,b)=>a+b,0),22);assert.equal(c.metamagias,8);assert.equal(c.magias,25);assert.equal(c.pontosFeiticaria,25);});
test("evolução não confirma nível de aprimoramento sem escolha válida",()=>{const d=novaFicha();d.nivel=3;assert.match(prepararFichaWandsWizards(d,{...d,nivel:4}).erro!,/aprimoramentos/);});

test("Vontade concede metamagias gratuitas no 3 e assinatura no 20",()=>{const d=novaFicha();d.nivel=3;assert.ok(ganhosDoNivel(d).some(t=>t.includes("Magia Feroz")));d.nivel=20;assert.ok(ganhosDoNivel(d).some(t=>t.includes("Magias de Assinatura")));assert.equal(ganhosDoNivel(d).some(t=>t.includes("Restauração Feiticeira")),false);});
